CREATE TABLE [GDOut].[GD_Activity_Goal_Dim] (
    [Activity Goal Dim Id]           VARCHAR (20)   NOT NULL,
    [Activity Goal Dim Name]         VARCHAR (50)   NULL,
    [Activity Goal Dim URL]          NVARCHAR (200) NULL,
    [Created Date]                     DATETIME       NULL,
    [Modified Date]                    DATETIME       NULL,
    [Start Date]                       DATETIME       NULL,
    [End Date]                         DATETIME       NULL,
    [Activity Goal Id]               VARCHAR (20)   NULL,
    [Activity Goal Name]             VARCHAR (50)   NULL,
    [Activity Goal URL]              NVARCHAR (200) NULL,
    [Activity Goal Type]             VARCHAR (20)   NULL,
    [Activity Goal Group]            VARCHAR (20)   NULL,
    [Activity Goal Quantity]           VARCHAR (20)   NULL,
    [Activity Goal Owner Id]         VARCHAR (20)   NULL,
    [Activity Goal Owner URL]        NVARCHAR (200) NULL,
    [Activity Goal Owner Last Name]  VARCHAR (50)   NULL,
    [Activity Goal Owner First Name] VARCHAR (50)   NULL,
    [Activity Goal Owner Full Name]  VARCHAR (100)  NULL,
    [Activity Goal Owner Email]      VARCHAR (100)  NULL,
    [Activity Goal User Id]          VARCHAR (20)   NULL,
    [Activity Goal User URL]         NVARCHAR (200) NULL,
    [Activity Goal User Last Name]   VARCHAR (50)   NULL,
    [Activity Goal User First Name]  VARCHAR (50)   NULL,
    [Activity Goal User Full Name]   VARCHAR (50)   NULL,
    [Activity Goal User Email]       VARCHAR (100)  NULL,
    [Start_Date_Id]                    VARCHAR (50)   NULL,
    [End_Date_Id]                      VARCHAR (50)   NULL, 
    CONSTRAINT [PK_GD_Activity_Goal_Dim] PRIMARY KEY ([Activity Goal Dim Id])
);


