CREATE TABLE [GDOut].[GD_Acct_Univ_Dim_All] (
    [Account Dim Id]                    VARCHAR (18)   NOT NULL,
    [Account Dim Name]                  VARCHAR (100)  NULL,
    [Account Dim Granularity]           VARCHAR (15)   NULL,
    [Account Dim URL]                   NVARCHAR (200) NULL,
    [Account Hierarchy Dim Id]          VARCHAR (52)   NULL,
    [Account Retail Dim Id]             VARCHAR (52)   NULL,
    [Account Custom Dim Id]             VARCHAR (18)   NULL,
    [Created Date]                      VARCHAR (18)   NULL,
    [Modified Date]                     VARCHAR (18)   NULL,
    [Company Key]                       VARCHAR (15)   NULL,
    [Company Name]                      VARCHAR (30)   NULL,
    [Division Key]                      NVARCHAR (30)  NULL,
    [Division Name]                     VARCHAR (20)   NULL,
    [Region Key]                        VARCHAR (20)   NULL,
    [Region Name]                       VARCHAR (20)   NULL,
    [Territory Id]                      VARCHAR (18)   NULL,
    [Territory URL]                     NVARCHAR (200) NULL,
    [Territory Key]                     VARCHAR (100)  NULL,
    [Territory Name]                    VARCHAR (100)  NULL,
    [Territory Custom 1]                NVARCHAR (200) NULL,
    [Territory Custom 2]                NVARCHAR (200) NULL,
    [Account Owner Id]                  VARCHAR (18)   NULL,
    [Account Owner URL]                 NVARCHAR (200) NULL,
    [Account Owner Last Name]           VARCHAR (60)   NULL,
    [Account Owner First Name]          VARCHAR (60)   NULL,
    [Account Owner Full Name]           VARCHAR (100)  NULL,
    [Account Owner Email]               VARCHAR (100)  NULL,
    [Account Id]                        VARCHAR (25)   NULL,
    [Account Level]                     VARCHAR (25)   NULL,
    [Account URL]                       NVARCHAR (200) NULL,
    [Account URL2]                      NVARCHAR (200) NULL,
    [Account Key]                       VARCHAR (52)   NULL,
    [Account Name]                      VARCHAR (100)  NULL,
    [Account Name Number]               VARCHAR (50)   NULL,
    [Account Record Type]               VARCHAR (20)   NULL,
    [Account Street]                    NVARCHAR (50)  NULL,
    [Account City]                      VARCHAR (40)   NULL,
    [Account State]                     VARCHAR (20)   NULL,
    [Account Zip]                       NVARCHAR (25)  NULL,
    [Account Country]                   VARCHAR (50)   NULL,
    [Account County]                    VARCHAR (30)   NULL,
    [Account Phone]                     VARCHAR (20)   NULL,
    [Account Key Account]               VARCHAR (20)   NULL,
    [Account Groups]                    VARCHAR (20)   NULL,
    [Account Custom 1]                  NVARCHAR (200) NULL,
    [Account Custom 2]                  NVARCHAR (200) NULL,
    [Account Custom 3]                  NVARCHAR (200) NULL,
    [Account Custom 4]                  NVARCHAR (200) NULL,
    [Account Custom 5]                  NVARCHAR (200) NULL,
    [Account Segment Name]              VARCHAR (30)   NULL,
    [Account Segment Key]               VARCHAR (20)   NULL,
    [Account Segment Channel]           VARCHAR (30)   NULL,
    [Account Banner Name]               VARCHAR (100)  NULL,
    [Account Wine Indicator]            VARCHAR (5)    NULL,
    [Account Liquor Indicator]          VARCHAR (5)    NULL,
    [Account Beer Indicator]            VARCHAR (5)    NULL,
    [Account Franchise Indicator]       VARCHAR (5)    NULL,
    [Account Premise Type]              VARCHAR (20)   NULL,
    [Account Class of Trade]            VARCHAR (20)   NULL,
    [Account Food Type]                 VARCHAR (30)   NULL,
    [Account Trade Channel]             NVARCHAR (50)  NULL,
    [Account Trade Sub Channel]         NVARCHAR (30)  NULL,
    [Account Chain Ind]                 VARCHAR (20)   NULL,
    [Account On Premise Indicator]      VARCHAR (30)   NULL,
    [Account Store Status]              VARCHAR (20)   NULL,
    [Account Active Indicator]          VARCHAR (15)   NULL,
    [Account Marketing Group Code]      VARCHAR (20)   NULL,
    [Account Marketing Group Name]      VARCHAR (50)   NULL,
    [Account Marketing Group Ownership] VARCHAR (15)   NULL,
    [Account Ultimate Parent Code]      VARCHAR (30)   NULL,
    [Account Ultimate Parent Name]      VARCHAR (30)   NULL,
    [Account Immediate Parent Name]     VARCHAR (30)   NULL,
    [Account License Type]              VARCHAR (20)   NULL,
    [Account Customer Priority]         VARCHAR (10)   NULL,
    [Account Format]                    VARCHAR (20)   NULL,
    [Account Type]                      VARCHAR (30)   NULL,
    [Key Acct Chain 1 Dim Id]           VARCHAR (20)   NULL,
    [Key Acct Chain 2 Dim Id]           VARCHAR (20)   NULL,
    [Key Acct Chain Indicator]          VARCHAR (20)   NULL,
    [Marketing Group Dim Id]            VARCHAR (18)   NULL,
    [Account BDN Id]                    VARCHAR (18)   NULL,
    [Account Owner Key]                 VARCHAR (18)   NULL,
    [Division Id]                       VARCHAR (18)   NULL,
    [Region Id]                         VARCHAR (18)   NULL,
    [Acct Record Type Dim Id]           VARCHAR (18)   NULL,
    [Acct Segment Dim Id]               VARCHAR (18)   NULL,
    [Currency Dim Id]                   VARCHAR (18)   NULL,
    [Account Description]               VARCHAR (30)   NULL,
    [Account Custom Checkbox 1]         VARCHAR (18)   NULL,
    [Account Custom Checkbox 2]         VARCHAR (18)   NULL,
    [Account Custom 6]                  VARCHAR (18)   NULL,
    [Account Custom 7]                  VARCHAR (15)   NULL,
    [Account Custom 8]                  VARCHAR (20)   NULL,
    [Account Custom 9]                  VARCHAR (8)    NULL,
    [Account Custom 10]                 VARCHAR (32)   NULL,
    [Account Credit Available]          VARCHAR (5)    NULL,
    [Account Credit Limit]              VARCHAR (10)   NULL,
    [Account Credit Status]             VARCHAR (20)   NULL,
    [Account License Expiration]        VARCHAR (10)   NULL,
    [Account MSA Code]                  VARCHAR (10)   NULL,
    [Account MSA Name]                  VARCHAR (50)   NULL,
    [Account Resale Number]             NVARCHAR (100) NULL,
    [Account Currency Code]             VARCHAR (70)   NULL,
    [Account Custom Date 1]             VARCHAR (68)   NULL,
    [Account Custom Date 2]             VARCHAR (53)   NULL,
    [Account Delivery Time]             NVARCHAR (50)  NULL,
    [Account Source File]               VARCHAR (50)   NULL,
    [Account Warehouse]                 VARCHAR (50)   NULL,
    [Account Distributor Rep]           NVARCHAR (50)  NULL,
    [Account Distributor Team]          NVARCHAR (50)  NULL,
    [Account Distributor Name]          VARCHAR (50)   NULL,
    [Region Custom 1]                   NVARCHAR (200) NULL,
    [Region Custom 2]                   NVARCHAR (200) NULL,
    [Division Custom 1]                 NVARCHAR (200) NULL,
    [Division Custom 2]                 NVARCHAR (200) NULL,
    [Company Custom 1]                  NVARCHAR (200) NULL,
    [Company Custom 2]                  NVARCHAR (200) NULL,
    [Account Geocode Unavailable]       VARCHAR (20)   NULL,
    [Account Geocode]                   NVARCHAR (50)  NULL,
    [Account Geocode Latitude]          NVARCHAR (50)  NULL,
    [Account Geocode Longitude]         NVARCHAR (50)  NULL,
    [Account Decision Maker Name]       VARCHAR (30)   NULL,
    [Account Decision Maker Email]      VARCHAR (30)   NULL,
    [Account FIPS County Geocode]       NVARCHAR (50)  NULL,
    [Account FIPS County Name]          VARCHAR (50)   NULL,
    [KPI Segment Dim Id]                VARCHAR (28)   NULL,
    [Account Shipping Street]           NVARCHAR (50)  NULL,
    [Account Shipping City]             VARCHAR (30)   NULL,
    [Account Shipping State]            VARCHAR (30)   NULL,
    [Account Shipping Zip]              NVARCHAR (20)  NULL,
    [Account Shipping Country]          VARCHAR (14)   NULL,
    [Account Rank]                      VARCHAR (17)   NULL,
    [Territory Custom 3]                NVARCHAR (200) NULL,
    [Territory Custom 4]                NVARCHAR (200) NULL,
    [Territory Custom 5]                NVARCHAR (200) NULL,
    [Division Custom 3]                 NVARCHAR (200) NULL,
    [Division Custom 4]                 NVARCHAR (200) NULL,
    [Division Custom 5]                 NVARCHAR (200) NULL,
    [Account Beer Volume]               VARCHAR (20)   NULL,
    [Account Liquor Volume]             VARCHAR (20)   NULL,
    [Account Wine Volume]               VARCHAR (20)   NULL,
    [Acct Type Dim Id]                  VARCHAR (20)   NULL,
    [Account Owner Dim Id]              VARCHAR (18)   NULL,
    [Account Zip5]                      NVARCHAR (20)  NULL,
    [Account Shipping Zip5]             NVARCHAR (20)  NULL,
    [Company Id]                        VARCHAR (18)   NULL,
    [Create_Date_Id]                    NVARCHAR (50)  NULL, 
    CONSTRAINT [PK_GD_Acct_Univ_Dim_All] PRIMARY KEY ([Account Dim Id])
);

