CREATE TABLE [GDOut].[GD_Acct_Univ_Dim] (
    [Account Dim Id]                    char (18)  NULL,
    [Account Dim Name]                  VARCHAR (97)  NULL,
    [Account Dim Granularity]           VARCHAR (9)   NULL,
    [Account Dim URL]                   VARCHAR (50)  NULL,
    [Account Hierarchy Dim Id]          char (18)  NULL,
    [Account Retail Dim Id]             char (18)  NULL,
    [Account Custom Dim Id]             char (18)  NULL,
    [Created Date]                      DATETIME      NULL,
    [Modified Date]                     DATETIME      NULL,
    [Company Key]                       VARCHAR (4)   NULL,
    [Company Name]                      VARCHAR (12)  NULL,
    [Division Key]                      VARCHAR (7)   NULL,
    [Division Name]                     char (18)  NULL,
    [Region Key]                        VARCHAR (4)   NULL,
    [Region Name]                       VARCHAR (20)  NULL,
    [Territory Id]                      char (18)  NULL,
    [Territory URL]                     VARCHAR (50)  NULL,
    [Territory Key]                     VARCHAR (3)   NULL,
    [Territory Name]                    VARCHAR (20)  NULL,
    [Territory Custom 1]                VARCHAR (MAX) NULL,
    [Territory Custom 2]                VARCHAR (MAX) NULL,
    [Account Owner Id]                  char (18)  NULL,
    [Account Owner URL]                 VARCHAR (50)  NULL,
    [Account Owner Last Name]           VARCHAR (10)  NULL,
    [Account Owner First Name]          VARCHAR (8)   NULL,
    [Account Owner Full Name]           VARCHAR (17)  NULL,
    [Account Owner Email]               VARCHAR (28)  NULL,
    [Account Id]                        char (18)  NULL,
    [Account Level]                     VARCHAR (22)  NULL,
    [Account URL]                       VARCHAR (50)  NULL,
    [Account URL2]                      VARCHAR (50)  NULL,
    [Account Key]                       VARCHAR (20)  NULL,
    [Account Name]                      VARCHAR (97)  NULL,
    [Account Name Number]               VARCHAR (108) NULL,
    [Account Record Type]               VARCHAR (20)  NULL,
    [Account Street]                    VARCHAR (68)  NULL,
    [Account City]                      VARCHAR (25)  NULL,
    [Account State]                     VARCHAR (16)  NULL,
    [Account Zip]                       VARCHAR (10)  NULL,
    [Account Country]                   VARCHAR (13)  NULL,
    [Account County]                    VARCHAR (25)  NULL,
    [Account Phone]                     VARCHAR (19)  NULL,
    [Account Key Account]               VARCHAR (3)   NULL,
    [Account Groups]                    VARCHAR (6)   NULL,
    [Account Custom 1]                  VARCHAR (33)  NULL,
    [Account Custom 2]                  VARCHAR (28)  NULL,
    [Account Custom 3]                  VARCHAR (63)  NULL,
    [Account Custom 4]                  VARCHAR (55)  NULL,
    [Account Custom 5]                  VARCHAR (33)  NULL,
    [Account Segment Name]              VARCHAR (MAX) NULL,
    [Account Segment Key]               VARCHAR (MAX) NULL,
    [Account Segment Channel]           VARCHAR (MAX) NULL,
    [Account Banner Name]               VARCHAR (39)  NULL,
    [Account Wine Indicator]            VARCHAR (3)   NULL,
    [Account Liquor Indicator]          VARCHAR (3)   NULL,
    [Account Beer Indicator]            VARCHAR (3)   NULL,
    [Account Franchise Indicator]       VARCHAR (2)   NULL,
    [Account Premise Type]              VARCHAR (20)  NULL,
    [Account Class of Trade]            VARCHAR (17)  NULL,
    [Account Food Type]                 VARCHAR (14)  NULL,
    [Account Trade Channel]             VARCHAR (27)  NULL,
    [Account Trade Sub Channel]         VARCHAR (25)  NULL,
    [Account Chain Ind]                 VARCHAR (11)  NULL,
    [Account On Premise Indicator]      VARCHAR (3)   NULL,
    [Account Store Status]              VARCHAR (15)  NULL,
    [Account Active Indicator]          VARCHAR (9)   NULL,
    [Account Marketing Group Code]      VARCHAR (MAX) NULL,
    [Account Marketing Group Name]      VARCHAR (MAX) NULL,
    [Account Marketing Group Ownership] VARCHAR (MAX) NULL,
    [Account Ultimate Parent Code]      BIGINT        NULL,
    [Account Ultimate Parent Name]      VARCHAR (31)  NULL,
    [Account Immediate Parent Name]     VARCHAR (35)  NULL,
    [Account License Type]              VARCHAR (MAX) NULL,
    [Account Customer Priority]         VARCHAR (MAX) NULL,
    [Account Format]                    VARCHAR (90)  NULL,
    [Account Type]                      VARCHAR (16)  NULL,
    [Key Acct Chain 1 Dim Id]           char (18)  NULL,
    [Key Acct Chain 2 Dim Id]           BIGINT        NULL,
    [Key Acct Chain Indicator]          VARCHAR (MAX) NULL,
    [Marketing Group Dim Id]            BIGINT        NULL,
    [Acct Record Type Dim Id]           char (18)  NULL,
    [Acct Segment Dim Id]               BIGINT        NULL,
    [Currency Dim Id]                   VARCHAR (3)   NULL,
    [Account Description]               VARCHAR (136) NULL,
    [Account Custom Checkbox 1]         VARCHAR (3)   NULL,
    [Account Custom Checkbox 2]         VARCHAR (3)   NULL,
    [Account Custom 6]                  VARCHAR (83)  NULL,
    [Account Custom 7]                  VARCHAR (17)  NULL,
    [Account Custom 8]                  VARCHAR (7)   NULL,
    [Account Custom 9]                  VARCHAR (7)   NULL,
    [Account Custom 10]                 VARCHAR (32)  NULL,
    [Account Credit Available]          VARCHAR (MAX) NULL,
    [Account Credit Limit]              VARCHAR (MAX) NULL,
    [Account Credit Status]             VARCHAR (MAX) NULL,
    [Account License Expiration]        VARCHAR (MAX) NULL,
    [Account MSA Code]                  VARCHAR (4)   NULL,
    [Account MSA Name]                  VARCHAR (39)  NULL,
    [Account Resale Number]             VARCHAR (77)  NULL,
    [Account Custom Date 1]             VARCHAR (MAX) NULL,
    [Account Custom Date 2]             VARCHAR (MAX) NULL,
    [Account Delivery Time]             VARCHAR (23)  NULL,
    [Account Source File]               VARCHAR (25)  NULL,
    [Account Warehouse]                 VARCHAR (MAX) NULL,
    [Account Distributor Rep]           VARCHAR (39)  NULL,
    [Account Distributor Team]          VARCHAR (19)  NULL,
    [Account Distributor Name]          VARCHAR (36)  NULL,
    [Region Custom 1]                   VARCHAR (MAX) NULL,
    [Region Custom 2]                   VARCHAR (MAX) NULL,
    [Division Custom 1]                 VARCHAR (MAX) NULL,
    [Division Custom 2]                 VARCHAR (MAX) NULL,
    [Company Custom 1]                  VARCHAR (MAX) NULL,
    [Company Custom 2]                  VARCHAR (MAX) NULL,
    [Account Geocode Unavailable]       VARCHAR (5)   NULL,
    [Account Geocode]                   VARCHAR (21)  NULL,
    [Account Geocode Latitude]          FLOAT (53)    NULL,
    [Account Geocode Longitude]         FLOAT (53)    NULL,
    [Account Decision Maker Name]       VARCHAR (MAX) NULL,
    [Account Decision Maker Email]      VARCHAR (MAX) NULL,
    [Account FIPS County Geocode]       VARCHAR (14)  NULL,
    [Account FIPS County Name]          VARCHAR (23)  NULL,
    [KPI Segment Dim Id]                BIGINT        NULL,
    [Account Shipping Street]           VARCHAR (35)  NULL,
    [Account Shipping City]             VARCHAR (19)  NULL,
    [Account Shipping State]            VARCHAR (3)   NULL,
    [Account Shipping Zip]              BIGINT        NULL,
    [Account Shipping Country]          VARCHAR (3)   NULL,
    [Account Rank]                      FLOAT (53)    NULL,
    [Territory Custom 3]                VARCHAR (MAX) NULL,
    [Territory Custom 4]                VARCHAR (MAX) NULL,
    [Territory Custom 5]                VARCHAR (MAX) NULL,
    [Division Custom 3]                 VARCHAR (MAX) NULL,
    [Division Custom 4]                 VARCHAR (MAX) NULL,
    [Division Custom 5]                 VARCHAR (MAX) NULL,
    [Account Beer Volume]               VARCHAR (MAX) NULL,
    [Account Liquor Volume]             VARCHAR (MAX) NULL,
    [Account Wine Volume]               VARCHAR (MAX) NULL,
    [Acct Type Dim Id]                  VARCHAR (11)  NULL,
    [Account Owner Dim Id]              char (18)  NULL,
    [Account Zip5]                      VARCHAR (5)   NULL,
    [Account Shipping Zip5]             BIGINT        NULL,
    [Company Id]                        char (18)  NULL,
    [Division Id]                       char (18)  NULL,
    [Region Id]                         char (18)  NULL,
    [Create_Date_Id]                    BIGINT        NULL
);

