CREATE TABLE [GDOut].[GD_Acct_Listing_Fact](
	[Acct Listing Fact Id] [varchar](18) NOT NULL,
	[Acct Listing Fact Name] [varchar](100) NULL,
	[Acct Listing Fact URL] [nvarchar](200) NULL,
	[Acct Listing Fact Type] [varchar](50) NULL,
	[Acct Listing Type] [varchar](50) NULL,
	[Acct Listing Compliance] [nvarchar](50) NULL,
	[Acct Listing New] [nvarchar](50) NULL,
	[Acct Listing Current] [nvarchar](50) NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Transaction Type Id] [varchar](18) NULL,
	[Acct HQ Id] [varchar](18) NULL,
	[Person Dim Id] [varchar](18) NULL,
	[Product Dim Id] [varchar](18) NULL,
	[Start Date] [datetime] NULL,
	[End Date] [datetime] NULL,
	[Transaction Date] [datetime] NULL,
	[Fiscal Date] [datetime] NULL,
	[Fiscal Year] [varchar](20) NULL,
	[Fiscal Month] [varchar](20) NULL,
	[Authorization Id] [varchar](18) NULL,
	[Authorization URL] [nvarchar](200) NULL,
	[Authorization Name] [varchar](100) NULL,
	[Authorization Status] [varchar](50) NULL,
	[Authorization Mandated] [varchar](50) NULL,
	[Authorization Supported] [varchar](50) NULL,
	[Authorization Package Type] [varchar](50) NULL,
	[Authorization Custom 1] [nvarchar](200) NULL,
	[Authorization Custom 2] [nvarchar](200) NULL,
	[Authorization Custom 3] [nvarchar](200) NULL,
	[Placement Id] [varchar](18) NULL,
	[Placement URL] [nvarchar](200) NULL,
	[Placement Number] [nvarchar](50) NULL,
	[Placement Description] [varchar](100) NULL,
	[Placement Price] [nvarchar](50) NULL,
	[Placement Drink Name] [varchar](50) NULL,
	[Placement Display Location] [varchar](50) NULL,
	[Placement Display Cases] [nvarchar](50) NULL,
	[Placement Scan Amount] [nvarchar](50) NULL,
	[Placement POS Item Name] [varchar](100) NULL,
	[Placement POS Quantity] [varchar](50) NULL,
	[Placement POS Approved] [varchar](50) NULL,
	[Placement Custom 1] [nvarchar](200) NULL,
	[Placement Custom 2] [nvarchar](200) NULL,
	[Placement Custom 3] [nvarchar](200) NULL,
	[Placement Type] [varchar](50) NULL,
	[Authorization Custom Fact 1] [nvarchar](200) NULL,
	[Authorization Custom Fact 2] [nvarchar](200) NULL,
	[Placement Custom Fact 1] [nvarchar](200) NULL,
	[Placement Custom Fact 2] [nvarchar](200) NULL,
	[Acct Univ Dim Id] [varchar](18) NULL,
	[Acct Listing Fact Granularity] [varchar](40) NULL,
	[Fiscal Date Dim Id] [varchar](18) NULL,
	[Authorization Key] [varchar](50) NULL,
	[Authorization Custom Text 1] [nvarchar](200) NULL,
	[Authorization Custom Text 2] [nvarchar](200) NULL,
	[Authorization Custom Text 3] [nvarchar](200) NULL,
	[Authorization Custom Text 4] [nvarchar](200) NULL,
	[Authorization Custom Text 5] [nvarchar](200) NULL,
	[Authorization Custom Checkbox 1] [nvarchar](50) NULL,
	[Authorization Custom Checkbox 2] [nvarchar](50) NULL,
	[Authorization Custom Currency 1] [varchar](20) NULL,
	[Authorization Custom Currency 2] [varchar](20) NULL,
	[Placement Key] [varchar](18) NULL,
	[Placement Custom Text 1] [nvarchar](200) NULL,
	[Placement Custom Text 2] [nvarchar](200) NULL,
	[Placement Custom Checkbox 1] [nvarchar](50) NULL,
	[Placement Custom Checkbox 2] [nvarchar](50) NULL,
	[Currency Dim Id] [varchar](18) NULL,
	[Start_Date_Id] [varchar](20) NULL,
	[End_Date_Id] [varchar](20) NULL,
	[Txn_Date_Id] [varchar](20) NULL,
	[Fiscal_Date_Id] [varchar](20) NULL,
	[Spend Dim Id] [varchar](18) NULL, 
    CONSTRAINT [PK_GD_Acct_Listing_Fact] PRIMARY KEY ([Acct Listing Fact Id])
) ON [PRIMARY]
GO

