CREATE TABLE [GDOut].[GD_Acct_Univ_Retail_Dim] (
    [Account Retail Dim Id]                     VARCHAR (19)  NULL,
    [Created Date]                              VARCHAR (50)  NULL,
    [Modified Date]                             VARCHAR (50)  NULL,
    [Account Customer Number]                   VARCHAR (120) NULL,
    [Account BDN Id]                            VARCHAR (50)  NULL,
    [Account DBA Name]                          VARCHAR (100) NULL,
    [Account BDN Date of Data]                  VARCHAR (50)  NULL,
    [Account BDN Last Update]                   VARCHAR (50)  NULL,
    [Account BDN Add Date]                      VARCHAR (50)  NULL,
    [Account BDN Change Date]                   VARCHAR (50)  NULL,
    [Account Consumer Demographic]              VARCHAR (100) NULL,
    [Account Primary Contact]                   VARCHAR (51)  NULL,
    [Account Primary Email]                     VARCHAR (100) NULL,
    [Account Company Size]                      VARCHAR (50)  NULL,
    [Account Geo Precision Code]                VARCHAR (50)  NULL,
    [Account Latitude]                          VARCHAR (50)  NULL,
    [Account Longitude]                         VARCHAR (50)  NULL,
    [Account License Number]                    VARCHAR (20)  NULL,
    [Account Number of Locations]               VARCHAR (50)  NULL,
    [Account Family Owner Code]                 VARCHAR (50)  NULL,
    [Account Immediate Parent State]            VARCHAR (50)  NULL,
    [Account Immediate Parent State FIPS Code]  VARCHAR (50)  NULL,
    [Account Immediate Parent County FIPS Code] VARCHAR (50)  NULL,
    [Account Outlet Number]                     VARCHAR (50)  NULL,
    [Account Outlet Place Name]                 VARCHAR (100) NULL,
    [Account Number of FTEs]                    VARCHAR (50)  NULL,
    [Account Number of Registers]               VARCHAR (50)  NULL,
    [Account Square Footage]                    VARCHAR (50)  NULL,
    [Account Annual Volume]                     VARCHAR (50)  NULL,
    [Account Weekly Volume]                     VARCHAR (50)  NULL,
    [Account Distributor Name]                  VARCHAR (50)  NULL,
    [Account Distributor Team]                  VARCHAR (50)  NULL,
    [Account Distributor Rep]                   VARCHAR (42)  NULL
);

