CREATE TABLE [GDOut].[GD_Account_Dim](
	[Account Dim Id] VARCHAR(18) NOT NULL,
	[Account Dim Name] [nvarchar](250) NULL,
	[Account Dim Granularity] [varchar](100) NULL,
	[Account Dim URL] [nvarchar](100) NULL,
	[Account Hierarchy Dim Id] VARCHAR(18) NULL,
	[Account Retail Dim Id] VARCHAR(18) NULL,
	[Account Custom Dim Id] VARCHAR(18) NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Company Key] [nvarchar](50) NULL,
	[Company Name] [nvarchar](100) NULL,
	[Division Key] [nvarchar](30) NULL,
	[Division Name] [nvarchar](100) NULL,
	[Region Key] [nvarchar](50) NULL,
	[Region Name] [nvarchar](100) NULL,
	[Territory Id] VARCHAR(18) NULL,
	[Territory URL] [nvarchar](100) NULL,
	[Territory Key] [nvarchar](45) NULL,
	[Territory Name] [nvarchar](200) NULL,
	[Territory Custom 1] [nvarchar](200) NULL,
	[Territory Custom 2] [nvarchar](200) NULL,
	[Account Owner Id] VARCHAR(18) NULL,
	[Account Owner URL] [nvarchar](100) NULL,
	[Account Owner Last Name] [nvarchar](50) NULL,
	[Account Owner First Name] [nvarchar](50) NULL,
	[Account Owner Full Name] [nvarchar](80) NULL,
	[Account Owner Email] [nvarchar](75) NULL,
	[Account Id] VARCHAR(18) NULL,
	[Account Level] [varchar](80) NULL,
	[Account URL] [nvarchar](100) NULL,
	[Account URL2] [nvarchar](100) NULL,
	[Account Key] [varchar](70) NULL,
	[Account Name] [nvarchar](250) NULL,
	[Account Name Number] [nvarchar](400) NULL,
	[Account Record Type] [nvarchar](100) NULL,
	[Account Street] [nvarchar](250) NULL,
	[Account City] [nvarchar](50) NULL,
	[Account State] [nvarchar](35) NULL,
	[Account Zip] [nvarchar](20) NULL,
	[Account Country] [varchar](50) NULL,
	[Account County] [nvarchar](40) NULL,
	[Account Phone] [varchar](50) NULL,
	[Account Key Account] [varchar](10) NULL,
	[Account Groups] [nvarchar](200) NULL,
	[Account Custom 1] [nvarchar](255) NULL,
	[Account Custom 2] [nvarchar](255) NULL,
	[Account Custom 3] [nvarchar](255) NULL,
	[Account Custom 4] [nvarchar](255) NULL,
	[Account Custom 5] [nvarchar](255) NULL,
	[Account Segment Name] [nvarchar](100) NULL,
	[Account Segment Key] [nvarchar](100) NULL,
	[Account Segment Channel] [nvarchar](100) NULL,
	[Account Banner Name] [nvarchar](100) NULL,
	[Account Wine Indicator] [varchar](20) NULL,
	[Account Liquor Indicator] [varchar](10) NULL,
	[Account Beer Indicator] [varchar](60) NULL,
	[Account Franchise Indicator] [varchar](10) NULL,
	[Account Premise Type] [nvarchar](100) NULL,
	[Account Class of Trade] [nvarchar](100) NULL,
	[Account Food Type] [nvarchar](100) NULL,
	[Account Trade Channel] [nvarchar](100) NULL,
	[Account Trade Sub Channel] [nvarchar](100) NULL,
	[Account Chain Ind] [nvarchar](100) NULL,
	[Account On Premise Indicator] [nvarchar](100) NULL,
	[Account Store Status] [nvarchar](100) NULL,
	[Account Active Indicator] [varchar](25) NULL,
	[Account Marketing Group Code] [varchar](20) NULL,
	[Account Marketing Group Name] [nvarchar](100) NULL,
	[Account Marketing Group Ownership] [nvarchar](100) NULL,
	[Account Ultimate Parent Code] VARCHAR(18) NULL,
	[Account Ultimate Parent Name] [nvarchar](100) NULL,
	[Account Immediate Parent Name] [nvarchar](100) NULL,
	[Account License Type] [nvarchar](100) NULL,
	[Account Customer Priority] [nvarchar](150) NULL,
	[Account Format] [nvarchar](200) NULL,
	[Account Type] [varchar](200) NULL,
	[Key Acct Chain 1 Dim Id] VARCHAR(18) NULL,
	[Key Acct Chain 2 Dim Id] VARCHAR(18) NULL,
	[Key Acct Chain Indicator] [nvarchar](100) NULL,
	[Marketing Group Dim Id] [varchar](20) NULL,
	[Acct Record Type Dim Id] VARCHAR(18) NULL,
	[Acct Segment Dim Id] VARCHAR(18) NULL,
	[Currency Dim Id] [nvarchar](30) NULL,
	[Account Description] [nvarchar](2000) NULL,
	[Account Custom Checkbox 1] [nvarchar](100) NULL,
	[Account Custom Checkbox 2] [nvarchar](100) NULL,
	[Account Custom 6] [nvarchar](255) NULL,
	[Account Custom 7] [nvarchar](255) NULL,
	[Account Custom 8] [nvarchar](255) NULL,
	[Account Custom 9] [nvarchar](255) NULL,
	[Account Custom 10] [nvarchar](255) NULL,
	[Account Credit Available] [money] NULL,
	[Account Credit Limit] [money] NULL,
	[Account Credit Status] [nvarchar](100) NULL,
	[Account License Expiration] [date] NULL,
	[Account MSA Code] [varchar](5) NULL,
	[Account MSA Name] [varchar](200) NULL,
	[Account Resale Number] [nvarchar](250) NULL,
	[Account Custom Date 1] [date] NULL,
	[Account Custom Date 2] [date] NULL,
	[Account Delivery Time] [nvarchar](70) NULL,
	[Account Source File] [nvarchar](100) NULL,
	[Account Warehouse] [nvarchar](100) NULL,
	[Account Distributor Rep] VARCHAR(18) NULL,
	[Account Distributor Team] [nvarchar](100) NULL,
	[Account Distributor Name] [nvarchar](100) NULL,
	[Region Custom 1] [nvarchar](200) NULL,
	[Region Custom 2] [nvarchar](200) NULL,
	[Division Custom 1] [nvarchar](200) NULL,
	[Division Custom 2] [nvarchar](200) NULL,
	[Company Custom 1] [nvarchar](200) NULL,
	[Company Custom 2] [nvarchar](200) NULL,
	[Account Geocode Unavailable] [varchar](10) NULL,
	[Account Geocode] [decimal](14, 11) NULL,
	[Account Geocode Latitude] [decimal](14, 11) NULL,
	[Account Geocode Longitude] [decimal](14, 11) NULL,
	[Account Decision Maker Name] [nvarchar](110) NULL,
	[Account Decision Maker Email] [nvarchar](200) NULL,
	[Account FIPS County Geocode] [nvarchar](100) NULL,
	[Account FIPS County Name] [nvarchar](100) NULL,
	[KPI Segment Dim Id] [varchar](50) NULL,
	[Account Shipping Street] [nvarchar](250) NULL,
	[Account Shipping City] [nvarchar](50) NULL,
	[Account Shipping State] [nvarchar](30) NULL,
	[Account Shipping Zip] [nvarchar](20) NULL,
	[Account Shipping Country] [nvarchar](25) NULL,
	[Account Rank] [decimal](6, 1) NULL,
	[Territory Custom 3] [nvarchar](200) NULL,
	[Territory Custom 4] [nvarchar](200) NULL,
	[Territory Custom 5] [nvarchar](200) NULL,
	[Division Custom 3] [nvarchar](200) NULL,
	[Division Custom 4] [nvarchar](200) NULL,
	[Division Custom 5] [nvarchar](200) NULL,
	[Account Beer Volume] [nvarchar](100) NULL,
	[Account Liquor Volume] [nvarchar](100) NULL,
	[Account Wine Volume] [nvarchar](100) NULL,
	[Acct Type Dim Id] [nvarchar](100) NULL,
	[Account Owner Dim Id] VARCHAR(18) NULL,
	[Account Zip5] [nvarchar](20) NULL,
	[Account Shipping Zip5] [nvarchar](20) NULL,
	[Company Id] VARCHAR(18) NULL,
	[Division Id] VARCHAR(18) NULL,
	[Region Id] VARCHAR(18) NULL,
	[Create_Date_Id] [int] NULL,
	CONSTRAINT [PK_GD_Account_Dim] PRIMARY KEY ([Account Dim Id])
) ON [PRIMARY]
GO