CREATE TABLE [GDOut].[GD_Acct_Univ_Hier_Dim] (
    [Account Hierarchy Dim Id]     CHAR (18)      NOT NULL,
    [Created Date]                 CHAR (10)      NULL,
    [Modified Date]                CHAR (10)      NULL,
    [Acct HQ 4 Id]                 CHAR (18)      NULL,
    [Acct HQ 4 URL]                VARCHAR (250)  NULL,
    [Acct HQ 4 Name]               VARCHAR (200)  NULL,
    [Acct HQ 4 Record Type]        VARCHAR (100)  NULL,
    [Acct HQ 4 City]               VARCHAR (100)  NULL,
    [Acct HQ 4 State]              VARCHAR (50)   NULL,
    [Acct HQ 4 Key Account]        VARCHAR (20)   NULL,
    [Acct HQ 4 Owner Full Name]    VARCHAR (200)  NULL,
    [Acct HQ 4 Owner Email]        VARCHAR (300)  NULL,
    [Acct HQ 3 Id]                 CHAR (18)      NULL,
    [Acct HQ 3 URL]                VARCHAR (250)  NULL,
    [Acct HQ 3 Name]               VARCHAR (200)  NULL,
    [Acct HQ 3 Record Type]        VARCHAR (100)  NULL,
    [Acct HQ 3 City]               VARCHAR (100)  NULL,
    [Acct HQ 3 State]              VARCHAR (50)   NULL,
    [Acct HQ 3 Key Account]        VARCHAR (20)   NULL,
    [Acct HQ 3 Owner Full Name]    VARCHAR (200)  NULL,
    [Acct HQ 3 Owner Email]        VARCHAR (300)  NULL,
    [Acct HQ 2 Id]                 CHAR (18)      NULL,
    [Acct HQ 2 URL]                VARCHAR (250)  NULL,
    [Acct HQ 2 Name]               VARCHAR (200)  NULL,
    [Acct HQ 2 Record Type]        VARCHAR (100)  NULL,
    [Acct HQ 2 City]               VARCHAR (100)  NULL,
    [Acct HQ 2 State]              VARCHAR (50)   NULL,
    [Acct HQ 2 Key Account]        VARCHAR (20)   NULL,
    [Acct HQ 2 Owner Full Name]    VARCHAR (200)  NULL,
    [Acct HQ 2 Owner Email]        VARCHAR (300)  NULL,
    [Acct HQ 1 Id]                 CHAR (18)      NULL,
    [Acct HQ 1 URL]                VARCHAR (250)  NULL,
    [Acct HQ 1 Name]               VARCHAR (200)  NULL,
    [Acct HQ 1 Record Type]        VARCHAR (100)  NULL,
    [Acct HQ 1 City]               VARCHAR (100)  NULL,
    [Acct HQ 1 State]              VARCHAR (50)   NULL,
    [Acct HQ 1 Key Account]        VARCHAR (20)   NULL,
    [Acct HQ 1 Owner Full Name]    VARCHAR (200)  NULL,
    [Acct HQ 1 Owner Email]        VARCHAR (300)  NULL,
    [Acct HQ 1 Key]                VARCHAR (100)  NULL,
    [Acct HQ 1 Name Number]        VARCHAR (200)  NULL,
    [Acct HQ 2 Key]                VARCHAR (100)  NULL,
    [Acct HQ 2 Name Number]        VARCHAR (200)  NULL,
    [Acct HQ 3 Key]                VARCHAR (100)  NULL,
    [Acct HQ 3 Name Number]        VARCHAR (200)  NULL,
    [Acct HQ 4 Key]                VARCHAR (100)  NULL,
    [Acct HQ 4 Name Number]        VARCHAR (200)  NULL,
    [Acct HQ 1 URL2]               VARCHAR (250)  NULL,
    [Acct HQ 2 URL2]               VARCHAR (250)  NULL,
    [Acct HQ 3 URL2]               VARCHAR (250)  NULL,
    [Acct HQ 4 URL2]               VARCHAR (250)  NULL, 
    CONSTRAINT [PK_GD_Acct_Univ_Hier_Dim] PRIMARY KEY ([Account Hierarchy Dim Id])
);


