CREATE TABLE [GDOut].[GD_Account_Mktg_Group_Dim](
	[Marketing Group Dim Id] [varchar](18) NOT NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Marketing Group Id] [varchar](18) NULL,
	[Marketing Group URL] [nvarchar](200) NULL,
	[Marketing Group URL2] [nvarchar](200) NULL,
	[Marketing Group Name] [nvarchar](100) NULL,
	[Marketing Group Name Number] [nvarchar](50) NULL,
	[Marketing Group Record Type] [nvarchar](50) NULL,
	[Marketing Group Key] [nvarchar](50) NULL,
	[Marketing Group Code] [nvarchar](50) NULL,
	[Marketing Group City] [nvarchar](50) NULL,
	[Marketing Group State] [nvarchar](50) NULL,
	[Marketing Group Key Account] [nvarchar](50) NULL,
	[Marketing Group Custom 1] [nvarchar](200) NULL,
	[Marketing Group Custom 2] [nvarchar](200) NULL,
	[Marketing Group Custom 3] [nvarchar](200) NULL,
	[Marketing Group Custom 4] [nvarchar](200) NULL,
	[Marketing Group Custom 5] [nvarchar](200) NULL,
	[Marketing Group Owner Id] [varchar](18) NULL,
	[Marketing Group Owner URL] [nvarchar](200) NULL,
	[Marketing Group Owner Last Name] [nvarchar](50) NULL,
	[Marketing Group Owner First Name] [nvarchar](50) NULL,
	[Marketing Group Owner Name] [nvarchar](100) NULL,
	[Marketing Group Owner Email] [nvarchar](200) NULL, 
    CONSTRAINT [PK_GD_Account_Mktg_Group_Dim] PRIMARY KEY ([Marketing Group Dim Id])
) ON [PRIMARY]
GO

