CREATE TABLE [GDOut].[GD_Acct_Univ_Hier_Dim] (
    [Account Hierarchy Dim Id]  VARCHAR (18)   NOT NULL,
    [Created Date]              DATETIME       NULL,
    [Modified Date]             DATETIME       NULL,
    [Acct HQ 4 Id]              VARCHAR (18)   NULL,
    [Acct HQ 4 URL]             NVARCHAR (200) NULL,
    [Acct HQ 4 Name]            NVARCHAR (100) NULL,
    [Acct HQ 4 Record Type]     VARCHAR (50)   NULL,
    [Acct HQ 4 City]            NVARCHAR (50)  NULL,
    [Acct HQ 4 State]           NVARCHAR (100) NULL,
    [Acct HQ 4 Key Account]     NVARCHAR (50)  NULL,
    [Acct HQ 4 Owner Full Name] NVARCHAR (200) NULL,
    [Acct HQ 4 Owner Email]     NVARCHAR (200) NULL,
    [Acct HQ 3 Id]              VARCHAR (18)   NULL,
    [Acct HQ 3 URL]             NVARCHAR (200) NULL,
    [Acct HQ 3 Name]            NVARCHAR (200) NULL,
    [Acct HQ 3 Record Type]     VARCHAR (50)   NULL,
    [Acct HQ 3 City]            NVARCHAR (50)  NULL,
    [Acct HQ 3 State]           NVARCHAR (100) NULL,
    [Acct HQ 3 Key Account]     VARCHAR (50)   NULL,
    [Acct HQ 3 Owner Full Name] NVARCHAR (200) NULL,
    [Acct HQ 3 Owner Email]     NVARCHAR (200) NULL,
    [Acct HQ 2 Id]              VARCHAR (18)   NULL,
    [Acct HQ 2 URL]             NVARCHAR (200) NULL,
    [Acct HQ 2 Name]            NVARCHAR (200) NULL,
    [Acct HQ 2 Record Type]     VARCHAR (50)   NULL,
    [Acct HQ 2 City]            NVARCHAR (50)  NULL,
    [Acct HQ 2 State]           NVARCHAR (100) NULL,
    [Acct HQ 2 Key Account]     VARCHAR (50)   NULL,
    [Acct HQ 2 Owner Full Name] NVARCHAR (200) NULL,
    [Acct HQ 2 Owner Email]     NVARCHAR (200) NULL,
    [Acct HQ 1 Id]              VARCHAR (18)   NULL,
    [Acct HQ 1 URL]             NVARCHAR (200) NULL,
    [Acct HQ 1 Name]            NVARCHAR (200) NULL,
    [Acct HQ 1 Record Type]     VARCHAR (50)   NULL,
    [Acct HQ 1 City]            NVARCHAR (50)  NULL,
    [Acct HQ 1 State]           NVARCHAR (100) NULL,
    [Acct HQ 1 Key Account]     VARCHAR (50)   NULL,
    [Acct HQ 1 Owner Full Name] NVARCHAR (200) NULL,
    [Acct HQ 1 Owner Email]     NVARCHAR (200) NULL,
    [Acct HQ 1 Key]             VARCHAR (50)   NULL,
    [Acct HQ 1 Name Number]     NVARCHAR (100) NULL,
    [Acct HQ 2 Key]             NVARCHAR (50)  NULL,
    [Acct HQ 2 Name Number]     NVARCHAR (50)  NULL,
    [Acct HQ 3 Key]             NVARCHAR (50)  NULL,
    [Acct HQ 3 Name Number]     NVARCHAR (50)  NULL,
    [Acct HQ 4 Key]             NVARCHAR (50)  NULL,
    [Acct HQ 4 Name Number]     NVARCHAR (50)  NULL,
    [Acct HQ 1 URL2]            NVARCHAR (200) NULL,
    [Acct HQ 2 URL2]            NVARCHAR (200) NULL,
    [Acct HQ 3 URL2]            NVARCHAR (200) NULL,
    [Acct HQ 4 URL2]            NVARCHAR (200) NULL, 
    CONSTRAINT [PK_GD_Acct_Univ_Hier_Dim] PRIMARY KEY ([Account Hierarchy Dim Id])
);


