CREATE TABLE [GDOut].[GD_Account_Call_Fact](
	[Account Call Fact Id] [varchar](20) NOT NULL,
	[Account Call Fact URL] [varchar](200) NULL,
	[Account Call Fact Name] [varchar](100) NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Txn Date] [datetime] NULL,
	[Txn Alt Date] [datetime] NULL,
	[Create Date] [datetime] NULL,
	[Fiscal Date] [datetime] NULL,
	[Fiscal Month] [varchar](4) NULL,
	[Fiscal Year] [varchar](6) NULL,
	[Fiscal Date Dim Id] [datetime] NULL,
	[Account Dim Id] [varchar](20) NULL,
	[Acct Univ Dim Id] [varchar](20) NULL,
	[Contact Dim Id] [varchar](20) NULL,
	[Person Dim Id] [varchar](20) NULL,
	[Activity Goal Dim Id] [varchar](20) NULL,
	[Geography Dim Id] [varchar](20) NULL,
	[Product Dim Id] [varchar](20) NULL,
	[Transaction Type Id] [varchar](20) NULL,
	[Account Call Id] [varchar](20) NULL,
	[Account Call URL] [varchar](200) NULL,
	[Account Call Name] [varchar](100) NULL,
	[Account Call Notes] [varchar](250) NULL,
	[Account Call Status] [varchar](250) NULL,
	[Account Call Type] [varchar](200) NULL,
	[Account Call Key] [varchar](50) NULL,
	[Account Call Longitude] [varchar](100) NULL,
	[Account Call Latitude] [varchar](100) NULL,
	[Account Call Distance] [varchar](50) NULL,
	[Account Call Geocode] [varchar](100) NULL,
	[Account Call Date] [varchar](23) NULL,
	[Account Call Time] [varchar](12) NULL,
	[Account Call Custom 1] [varchar](200) NULL,
	[Account Call Custom 2] [varchar](200) NULL,
	[Account Call Custom 3] [varchar](200) NULL,
	[Account Call Custom 4] [varchar](200) NULL,
	[Account Call Custom 5] [varchar](200) NULL,
	[Account Call Custom Checkbox 1] [varchar](7) NULL,
	[Account Call Custom Checkbox 2] [varchar](7) NULL,
	[Account Call Custom Checkbox 3] [varchar](7) NULL,
	[Account Call Custom Fact 1] [varchar](200) NULL,
	[Account Call Custom Fact 2] [varchar](200) NULL,
	[Account Call Priority] [varchar](50) NULL,
	[Account Call Subject] [varchar](50) NULL,
	[Account Call Description] [varchar](700) NULL,
	[Task Id] [varchar](300) NULL,
	[Task URL] [varchar](300) NULL,
	[Task Status] [varchar](100) NULL,
	[Task Type] [varchar](54) NULL,
	[Task Call Type] [varchar](50) NULL,
	[Account Call Local Date] [varchar](12) NULL,
	[Account Team Dim Id] [varchar](20) NULL,
	[Sales Division Dim Id] [varchar](20) NULL,
	[Txn_Date_Id] [varchar](50) NULL,
	[Txn_Alt_Date_Id] [varchar](50) NULL,
	[Create_Date_Id] [varchar](50) NULL,
	[Fiscal_Date_Id] [varchar](50) NULL,
	[Image_Id] [varchar](20) NULL,
	[Image_Name] [varchar](100) NULL,
	[Image_URL] [varchar](200) NULL,
	[Image_Ind] [varchar](10) NULL,
	[Image_Description] [varchar](200) NULL,
	[Image_URL_Dashboard] [varchar](200) NULL,
	[Image_URL_Table] [varchar](100) NULL,
	[Spend Dim Id] [varchar](20) NULL, 
    CONSTRAINT [PK_GD_Account_Call_Fact] PRIMARY KEY ([Account Call Fact Id])
) ON [PRIMARY]
GO

