CREATE TABLE [GDOut].[GD_Acct_Univ_Owner_Dim] (
    [Person Dim Id]             VARCHAR (18)   NOT NULL,
    [Person Dim Name]           NVARCHAR (200) NULL,
    [Person Dim Granularity]    VARCHAR (20)   NULL,
    [Person Dim URL]            NVARCHAR (200) NULL,
    [Created Date]              DATETIME       NULL,
    [Modified Date]             DATETIME       NULL,
    [Person Id]                 VARCHAR (18)   NULL,
    [Person URL]                NVARCHAR (200) NULL,
    [Person Key 1]              NVARCHAR (200) NULL,
    [Person Key 2]              NVARCHAR (200) NULL,
    [Person Email Key]          NVARCHAR (200) NULL,
    [Person Full Name]          NVARCHAR (200) NULL,
    [Person Last Name]          NVARCHAR (100) NULL,
    [Person First Name]         NVARCHAR (100) NULL,
    [Person Salutation]         NVARCHAR (50)  NULL,
    [Person Record Type]        NVARCHAR (100) NULL,
    [Person Street]             NVARCHAR (100) NULL,
    [Person City]               NVARCHAR (100) NULL,
    [Person State]              NVARCHAR (20)  NULL,
    [Person Zip]                NVARCHAR (50)  NULL,
    [Person Country]            NVARCHAR (20)  NULL,
    [Person Phone]              NVARCHAR (20)  NULL,
    [Person Fax]                NVARCHAR (50)  NULL,
    [Person Mobile Phone]       NVARCHAR (20)  NULL,
    [Person Home Phone]         NVARCHAR (20)  NULL,
    [Person Work Phone]         NVARCHAR (20)  NULL,
    [Person Other Phone]        NVARCHAR (20)  NULL,
    [Person Email]              NVARCHAR (200) NULL,
    [Person Work Email]         NVARCHAR (200) NULL,
    [Person Title]              NVARCHAR (100) NULL,
    [Person Company]            NVARCHAR (100) NULL,
    [Person Department]         NVARCHAR (50)  NULL,
    [Person Division]           NVARCHAR (100) NULL,
    [Person Active Indicator]   VARCHAR (20)   NULL,
    [Person Do Not Email]       VARCHAR (10)   NULL,
    [Person Do Not Call]        VARCHAR (10)   NULL,
    [Person Level]              NVARCHAR (50)  NULL,
    [Person Source File]        NVARCHAR (50)  NULL,
    [Person Role Name]          NVARCHAR (100) NULL,
    [Person Profile Name]       NVARCHAR (100) NULL,
    [Person Manager Id]         VARCHAR (18)   NULL,
    [Person Manager URL]        NVARCHAR (200) NULL,
    [Person Manager Last Name]  NVARCHAR (100) NULL,
    [Person Manager First Name] NVARCHAR (100) NULL,
    [Person Manager Full Name]  NVARCHAR (200) NULL,
    [Person Manager Email]      NVARCHAR (200) NULL,
    [Person Owner Id]           VARCHAR (18)   NULL,
    [Person Owner URL]          NVARCHAR (200) NULL,
    [Person Owner Last Name]    NVARCHAR (50)  NULL,
    [Person Owner First Name]   NVARCHAR (50)  NULL,
    [Person Owner Full Name]    NVARCHAR (200) NULL,
    [Person Owner Email]        NVARCHAR (100) NULL,
    [Person Custom 1]           NVARCHAR (100) NULL,
    [Person Custom 2]           NVARCHAR (200) NULL,
    [Person Custom 3]           NVARCHAR (200) NULL,
    [Person Custom 4]           NVARCHAR (200) NULL,
    [Person Custom 5]           NVARCHAR (200) NULL,
    [Person Zip5]               NVARCHAR (50)  NULL, 
    CONSTRAINT [PK_GD_Acct_Univ_Owner_Dim] PRIMARY KEY ([Person Dim Id])
);


