CREATE TABLE [GDOut].[GD_Acct_Univ_Dim] (
    [Account Dim Id]                    char (18)  NOT NULL,
    [Account Dim Name]                  NVARCHAR (100)  NULL,
    [Account Dim Granularity]           VARCHAR (20)   NULL,
    [Account Dim URL]                   NVARCHAR (100)  NULL,
    [Account Hierarchy Dim Id]          char (18)  NULL,
    [Account Retail Dim Id]             char (18)  NULL,
    [Account Custom Dim Id]             char (18)  NULL,
    [Created Date]                      VARCHAR(10)      NULL,
    [Modified Date]                     VARCHAR(10)      NULL,
    [Company Key]                       VARCHAR (20)   NULL,
    [Company Name]                      NVARCHAR (100)  NULL,
    [Division Key]                      VARCHAR (20)   NULL,
    [Division Name]                     NVARCHAR(100)  NULL,
    [Region Key]                        VARCHAR (20)   NULL,
    [Region Name]                       NVARCHAR (100)  NULL,
    [Territory Id]                      char (18)  NULL,
    [Territory URL]                     NVARCHAR (100)  NULL,
    [Territory Key]                     VARCHAR (20)   NULL,
    [Territory Name]                    NVARCHAR (100)  NULL,
    [Territory Custom 1]                NVARCHAR(200) NULL,
    [Territory Custom 2]                NVARCHAR(200) NULL,
    [Account Owner Id]                  char (18)  NULL,
    [Account Owner URL]                 NVARCHAR(100)  NULL,
    [Account Owner Last Name]           NVARCHAR(50)  NULL,
    [Account Owner First Name]          NVARCHAR(50)   NULL,
    [Account Owner Full Name]           NVARCHAR (100)  NULL,
    [Account Owner Email]               NVARCHAR (200)  NULL,
    [Account Id]                        char (18)  NULL,
    [Account Level]                     VARCHAR (25)  NULL,
    [Account URL]                       NVARCHAR (100)  NULL,
    [Account URL2]                      NVARCHAR (100)  NULL,
    [Account Key]                       VARCHAR (20)  NULL,
    [Account Name]                      NVARCHAR (100)  NULL,
    [Account Name Number]               NVARCHAR (120) NULL,
    [Account Record Type]               CHAR (18)  NULL,
    [Account Street]                    NVARCHAR (70)  NULL,
    [Account City]                      NVARCHAR (50)  NULL,
    [Account State]                     NVARCHAR (25)  NULL,
    [Account Zip]                       NVARCHAR (10)  NULL,
    [Account Country]                   NVARCHAR (25)  NULL,
    [Account County]                    NVARCHAR (50)  NULL,
    [Account Phone]                     VARCHAR (20)  NULL,
    [Account Key Account]               VARCHAR (10)   NULL,
    [Account Groups]                    NVARCHAR (100)   NULL,
    [Account Custom 1]                  NVARCHAR (200)  NULL,
    [Account Custom 2]                  NVARCHAR (200) NULL,
    [Account Custom 3]                  NVARCHAR (200) NULL,
    [Account Custom 4]                  NVARCHAR (200) NULL,
    [Account Custom 5]                  NVARCHAR (200) NULL,
    [Account Segment Name]              NVARCHAR (200) NULL,
    [Account Segment Key]               CHAR (18) NULL,
    [Account Segment Channel]           NVARCHAR (50) NULL,
    [Account Banner Name]               NVARCHAR (100)  NULL,
    [Account Wine Indicator]            VARCHAR (10)   NULL,
    [Account Liquor Indicator]          VARCHAR (10)   NULL,
    [Account Beer Indicator]            VARCHAR (10)   NULL,
    [Account Franchise Indicator]       VARCHAR (10)   NULL,
    [Account Premise Type]              VARCHAR (20)  NULL,
    [Account Class of Trade]            VARCHAR (30)  NULL,
    [Account Food Type]                 VARCHAR (30)  NULL,
    [Account Trade Channel]             VARCHAR (50)  NULL,
    [Account Trade Sub Channel]         VARCHAR (50)  NULL,
    [Account Chain Ind]                 VARCHAR (50)  NULL,
    [Account On Premise Indicator]      VARCHAR (10)  NULL,
    [Account Store Status]              NVARCHAR(50)  NULL,
    [Account Active Indicator]          VARCHAR (10)   NULL,
    [Account Marketing Group Code]      VARCHAR (20) NULL,
    [Account Marketing Group Name]      NVARCHAR (100) NULL,
    [Account Marketing Group Ownership] CHAR (18) NULL,
    [Account Ultimate Parent Code]      NVARCHAR(50)        NULL,
    [Account Ultimate Parent Name]      NVARCHAR (100)  NULL,
    [Account Immediate Parent Name]     NVARCHAR (100)  NULL,
    [Account License Type]              VARCHAR (20) NULL,
    [Account Customer Priority]         NVARCHAR (20) NULL,
    [Account Format]                    NVARCHAR (100)  NULL,
    [Account Type]                      VARCHAR (20)  NULL,
    [Key Acct Chain 1 Dim Id]           CHAR (18)  NULL,
    [Key Acct Chain 2 Dim Id]           CHAR (18)        NULL,
    [Key Acct Chain Indicator]          VARCHAR (10)  NULL,
    [Marketing Group Dim Id]            CHAR (18)   NULL,
    [Acct Record Type Dim Id]           CHAR (18)   NULL,
    [Acct Segment Dim Id]               CHAR (18)   NULL,
    [Currency Dim Id]                   CHAR (3)   NULL,
    [Account Description]               NVARCHAR (200) NULL,
    [Account Custom Checkbox 1]         VARCHAR (10)   NULL,
    [Account Custom Checkbox 2]         VARCHAR (10)   NULL,
    [Account Custom 6]                  NVARCHAR (200)  NULL,
    [Account Custom 7]                  NVARCHAR (200)  NULL,
    [Account Custom 8]                  NVARCHAR (200)   NULL,
    [Account Custom 9]                  NVARCHAR (200)   NULL,
    [Account Custom 10]                 NVARCHAR (200)  NULL,
    [Account Credit Available]          VARCHAR (20) NULL,
    [Account Credit Limit]              VARCHAR (20) NULL,
    [Account Credit Status]             NVARCHAR (20) NULL,
    [Account License Expiration]        VARCHAR (10) NULL,
    [Account MSA Code]                  VARCHAR (5)   NULL,
    [Account MSA Name]                  VARCHAR (50)  NULL,
    [Account Resale Number]             NVARCHAR (100)  NULL,
    [Account Custom Date 1]             VARCHAR (10) NULL,
    [Account Custom Date 2]             VARCHAR (10) NULL,
    [Account Delivery Time]             NVARCHAR (30)  NULL,
    [Account Source File]               VARCHAR (100)  NULL,
    [Account Warehouse]                 NVARCHAR (100) NULL,
    [Account Distributor Rep]           NVARCHAR (100)  NULL,
    [Account Distributor Team]          NVARCHAR (100)  NULL,
    [Account Distributor Name]          NVARCHAR (100)  NULL,
    [Region Custom 1]                   NVARCHAR (200) NULL,
    [Region Custom 2]                   NVARCHAR (200) NULL,
    [Division Custom 1]                 NVARCHAR (200) NULL,
    [Division Custom 2]                 NVARCHAR (200) NULL,
    [Company Custom 1]                  NVARCHAR (200) NULL,
    [Company Custom 2]                  NVARCHAR (200) NULL,
    [Account Geocode Unavailable]       VARCHAR (10)   NULL,
    [Account Geocode]                   VARCHAR (38)  NULL,
    [Account Geocode Latitude]          VARCHAR (19)    NULL,
    [Account Geocode Longitude]         VARCHAR (19)    NULL,
    [Account Decision Maker Name]       NVARCHAR (100) NULL,
    [Account Decision Maker Email]      NVARCHAR (200) NULL,
    [Account FIPS County Geocode]       CHAR (14)  NULL,
    [Account FIPS County Name]          NVARCHAR (50)  NULL,
    [KPI Segment Dim Id]                CHAR (18)   NULL,
    [Account Shipping Street]           NVARCHAR (75)  NULL,
    [Account Shipping City]             NVARCHAR (50)  NULL,
    [Account Shipping State]            NVARCHAR (25)  NULL,
    [Account Shipping Zip]              NVARCHAR (10)  NULL,
    [Account Shipping Country]          NVARCHAR (25)   NULL,
    [Account Rank]                      VARCHAR (5)    NULL,
    [Territory Custom 3]                NVARCHAR (200) NULL,
    [Territory Custom 4]                NVARCHAR (200) NULL,
    [Territory Custom 5]                NVARCHAR (200) NULL,
    [Division Custom 3]                 NVARCHAR (200) NULL,
    [Division Custom 4]                 NVARCHAR (200) NULL,
    [Division Custom 5]                 NVARCHAR (200) NULL,
    [Account Beer Volume]               VARCHAR (7) NULL,
    [Account Liquor Volume]             VARCHAR (7) NULL,
    [Account Wine Volume]               VARCHAR (7) NULL,
    [Acct Type Dim Id]                  VARCHAR (15)  NULL,
    [Account Owner Dim Id]              char (18)  NULL,
    [Account Zip5]                      VARCHAR (5)   NULL,
    [Account Shipping Zip5]             VARCHAR (5)   NULL,
    [Company Id]                        char (18)  NULL,
    [Division Id]                       char (18)  NULL,
    [Region Id]                         char (18)  NULL,
    [Create_Date_Id]                    CHAR (5)   NULL, 
    CONSTRAINT [PK_GD_Acct_Univ_Dim] PRIMARY KEY ([Account Dim Id])
);

