CREATE TABLE [GDOut].[GD_Account_Set_Dim](
	[Account Set Dim Id]              VARCHAR(18)      NOT NULL,
	[Account Set Dim Name]            [nvarchar](100) NULL,
	[Account Set Dim URL]             [nvarchar](250) NULL,
	[Account Set Dim Granularity]     [varchar](50)   NULL,
	[Account Dim Id]                  VARCHAR(18)      NULL,
	[Acct Univ Dim Id]                VARCHAR(18)      NULL,
	[Created Date]                    [char](10)      NULL,
	[Modified Date]                   [char](10)      NULL,
	[Account Set Id]                  VARCHAR(18)      NULL,
	[Account Set Name]                [nvarchar](100) NULL,
	[Account Set URL]                 [nvarchar](250) NULL,
	[Account Set Test]                [varchar](10)   NULL,
	[Account Set Member Id]           VARCHAR(18)      NULL,
	[Account Set Member URL]          [nvarchar](250) NULL,
	[Account Set Member Name]         [nvarchar](200) NULL,
	[Account Set Account Name Number] [nvarchar](250) NULL, 
	[Account Set Status]              [varchar](50)   NULL,
	[Account Set Last Account Update] [char](10)      NULL,
	[Account Set Expiration Date]     [char](10)      NULL,
	[Account Set Channel]             [nvarchar](200) NULL,
	[Account Set Custom Text 1]       [nvarchar](200) NULL,
	[Account Set Custom Text 2]       [nvarchar](200) NULL,
	[Account Set Custom Text 3]       [nvarchar](200) NULL,
	[Account Set Custom Text 4]       [nvarchar](200) NULL,
	[Account Set Custom Text 5]       [nvarchar](200) NULL,
	[Account Set Description]         [nvarchar](200) NULL,
	[Account Set External Id]         [varchar](50)   NULL,
    CONSTRAINT [PK_GD_Account_Set_Dim] PRIMARY KEY ([Account Set Dim Id])
) ON [PRIMARY]
GO

