CREATE TABLE [GDOut].[GD_Contact_Dim](
	[Contact Dim Id] [char](18) NOT NULL,
	[Contact Dim Name] [nvarchar](110) NULL,
	[Contact Dim Granularity] [varchar](26) NULL,
	[Contact Dim URL] [nvarchar](100) NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Contact Id] [char](18) NULL,
	[Contact URL] [nvarchar](100) NULL,
	[Contact Customer Key] [varchar](60) NULL,
	[Contact Salesman Key] [varchar](60) NULL,
	[Contact Email Key] [varchar](100) NULL,
	[Contact Full Name] [nvarchar](50) NULL,
	[Contact Last Name] [nvarchar](50) NULL,
	[Contact First Name] [nvarchar](50) NULL,
	[Contact Salutation] [nvarchar](30) NULL,
	[Contact Record Type] [varchar](26) NULL,
	[Contact Street] [nvarchar](200) NULL,
	[Contact City] [nvarchar](27) NULL,
	[Contact State] [nvarchar](16) NULL,
	[Contact Zip] [nvarchar](6) NULL,
	[Contact Country] [nvarchar](3) NULL,
	[Contact Phone] [varchar](50) NULL,
	[Contact Fax] [varchar](23) NULL,
	[Contact Mobile Phone] [varchar](29) NULL,
	[Contact Home Phone] [varchar](37) NULL,
	[Contact Work Phone] [varchar](11) NULL,
	[Contact Other Phone] [varchar](11) NULL,
	[Contact Email] [nvarchar](200) NULL,
	[Contact Work Email] [nvarchar](100) NULL,
	[Contact Title] [nvarchar](30) NULL,
	[Contact Department] [nvarchar](34) NULL,
	[Contact Active Indicator] [nvarchar](25) NULL,
	[Contact Do Not Email] [varchar](20) NULL,
	[Contact Do Not Call] [varchar](28) NULL,
	[Contact Level] [varchar](3) NULL,
	[Contact Source File] [varchar](3) NULL,
	[Contact Manager Id] [char](18) NULL,
	[Contact Manager URL] [nvarchar](100) NULL,
	[Contact Manager Last Name] [nvarchar](50) NULL,
	[Contact Manager First Name] [nvarchar](50) NULL,
	[Contact Manager Full Name] [nvarchar](50) NULL,
	[Contact Manager Email] [nvarchar](max) NULL,
	[Contact Owner Id] [char](18) NULL,
	[Contact Owner URL] [nvarchar](60) NULL,
	[Contact Owner Last Name] [nvarchar](51) NULL,
	[Contact Owner First Name] [nvarchar](51) NULL,
	[Contact Owner Full Name] [nvarchar](51) NULL,
	[Contact Owner Email] [nvarchar](51) NULL,
	[Account Dim Id] [char](18) NULL,
	[Acct Univ Dim Id] [char](18) NULL,
	[Contact Role] [varchar](37) NULL,
	[Contact Custom 1] [nvarchar](200) NULL,
	[Contact Custom 2] [nvarchar](200) NULL,
	[Contact Custom 3] [nvarchar](200) NULL,
	[Contact Custom 4] [nvarchar](200) NULL,
	[Contact Custom 5] [nvarchar](200) NULL,
	[Contact Zip5] [nvarchar](200) NULL,
	CONSTRAINT [PK_GD_Contact_Dim] PRIMARY KEY ([Contact Dim Id])
) ON [PRIMARY]
GO