CREATE TABLE [GDOut].[GD_Distributor_Owner_Dim] (
    [Person Dim Id]             VARCHAR (18)   NOT NULL,
    [Person Dim Name]           VARCHAR (50)   NULL,
    [Person Dim Granularity]    VARCHAR (10)   NULL,
    [Person Dim URL]            NVARCHAR (200) NULL,
    [Created Date]              DATETIME       NULL,
    [Modified Date]             DATETIME       NULL,
    [Person Id]                 VARCHAR (18)   NULL,
    [Person URL]                NVARCHAR (200) NULL,
    [Person Key 1]              VARCHAR (30)   NULL,
    [Person Key 2]              VARCHAR (40)   NULL,
    [Person Email Key]          VARCHAR (40)   NULL,
    [Person Full Name]          VARCHAR (100)  NULL,
    [Person Last Name]          VARCHAR (50)   NULL,
    [Person First Name]         VARCHAR (50)   NULL,
    [Person Salutation]         VARCHAR (20)   NULL,
    [Person Record Type]        VARCHAR (20)   NULL,
    [Person Street]             NVARCHAR (50)  NULL,
    [Person City]               VARCHAR (50)   NULL,
    [Person State]              VARCHAR (10)   NULL,
    [Person Zip]                VARCHAR (20)   NULL,
    [Person Country]            VARCHAR (10)   NULL,
    [Person Phone]              VARCHAR (20)   NULL,
    [Person Fax]                VARCHAR (20)   NULL,
    [Person Mobile Phone]       VARCHAR (20)   NULL,
    [Person Home Phone]         VARCHAR (20)   NULL,
    [Person Work Phone]         VARCHAR (20)   NULL,
    [Person Other Phone]        VARCHAR (20)   NULL,
    [Person Email]              VARCHAR (40)   NULL,
    [Person Work Email]         VARCHAR (40)   NULL,
    [Person Title]              VARCHAR (40)   NULL,
    [Person Company]            VARCHAR (40)   NULL,
    [Person Department]         VARCHAR (30)   NULL,
    [Person Division]           VARCHAR (30)   NULL,
    [Person Active Indicator]   VARCHAR (20)   NULL,
    [Person Do Not Email]       VARCHAR (5)    NULL,
    [Person Do Not Call]        VARCHAR (5)    NULL,
    [Person Level]              VARCHAR (50)   NULL,
    [Person Source File]        VARCHAR (50)   NULL,
    [Person Role Name]          VARCHAR (30)   NULL,
    [Person Profile Name]       VARCHAR (30)   NULL,
    [Person Manager Id]         VARCHAR (18)   NULL,
    [Person Manager URL]        NVARCHAR (200) NULL,
    [Person Manager Last Name]  VARCHAR (60)   NULL,
    [Person Manager First Name] VARCHAR (50)   NULL,
    [Person Manager Full Name]  VARCHAR (100)  NULL,
    [Person Manager Email]      VARCHAR (100)  NULL,
    [Person Owner Id]           VARCHAR (18)   NULL,
    [Person Owner URL]          NVARCHAR (200) NULL,
    [Person Owner Last Name]    VARCHAR (50)   NULL,
    [Person Owner First Name]   VARCHAR (50)   NULL,
    [Person Owner Full Name]    VARCHAR (100)  NULL,
    [Person Owner Email]        VARCHAR (50)   NULL,
    [Person Custom 1]           NVARCHAR (200) NULL,
    [Person Custom 2]           NVARCHAR (200) NULL,
    [Person Custom 3]           NVARCHAR (200) NULL,
    [Person Custom 4]           NVARCHAR (200) NULL,
    [Person Custom 5]           NVARCHAR (200) NULL,
    [Person Zip5]               VARCHAR (20)   NULL, 
    CONSTRAINT [PK_GD_Distributor_Owner_Dim] PRIMARY KEY ([Person Dim Id])
);


