CREATE TABLE [GDOut].[GD_Depletion_Fact] (
    [Depletion Fact Id]            VARCHAR (20)   NOT NULL,
    [Depletion Fact URL]           NVARCHAR (200) NULL,
    [Depletion Fact Name]          VARCHAR (100)  NULL,
    [Depletion Fact Type]          VARCHAR (20)   NULL,
    [Created Date]                   DATETIME       NULL,
    [Modified Date]                  DATETIME       NULL,
    [Product Dim Id]               VARCHAR (20)   NULL,
    [Geography Dim Id]             VARCHAR (20)   NULL,
    [Transaction Type Id]          VARCHAR (5)    NULL,
    [Txn Date]                       DATETIME       NULL,
    [Fiscal Date]                    DATETIME       NULL,
    [Fiscal Year]                  VARCHAR (6)    NULL,
    [Fiscal Month]                 VARCHAR (4)    NULL,
    [Txn Alt Date]                   DATETIME       NULL,
    [Depletion Key]                VARCHAR (100)  NULL,
    [Depletion Source File]        VARCHAR (60)   NULL,
    [Depletion Physical Cases]       VARCHAR (50)   NULL,
    [Depletion 9L Cases]             VARCHAR (50)   NULL,
    [Depletion Full Case Equivalent] VARCHAR (50)   NULL,
    [Depletion Primary Volume]       VARCHAR (50)   NULL,
    [Depletion Secondary Volume]     VARCHAR (50)   NULL,
    [Depletion Opening Balance]      VARCHAR (50)   NULL,
    [Depletion Closing Balance]      VARCHAR (50)   NULL,
    [Depletion On Order]             NVARCHAR (50)  NULL,
    [Depltion Adjustments]           VARCHAR (50)   NULL,
    [Depletion In Bond]              VARCHAR (50)   NULL,
    [Depletion Receipts]             VARCHAR (50)   NULL,
    [Depletion Wholesale Sales]      VARCHAR (50)   NULL,
    [Depletion Transfers In]         VARCHAR (50)   NULL,
    [Depletion Transfers Out]        VARCHAR (50)   NULL,
    [Depletion Custom 1]           NVARCHAR (200) NULL,
    [Depletion Custom 2]           NVARCHAR (200) NULL,
    [Depletion Fact 1]               VARCHAR (50)   NULL,
    [Depletion Fact 2]               VARCHAR (50)   NULL,
    [Account Dim Id]               VARCHAR (20)   NULL,
    [Depletion Rpt Current Ind]    VARCHAR (3)    NULL,
    [Fiscal Date Dim Id]             DATETIME       NULL,
    [Depletion Dist Item Number]   VARCHAR (50)   NULL,
    [Acct Univ Dim Id]             VARCHAR (20)   NULL,
    [Depletion Source System]      VARCHAR (10)   NULL,
    [Start Date]                     DATETIME       NULL,
    [End Date]                       DATETIME       NULL,
    [Txn_Date_Id]                    VARCHAR (50)   NULL,
    [Txn_Alt_Date_Id]                VARCHAR (50)   NULL,
    [Fiscal_Date_Id]                 VARCHAR (50)   NULL,
    [Start_Date_Id]                  VARCHAR (50)   NULL,
    [End_Date_Id]                    VARCHAR (50)   NULL, 
    CONSTRAINT [PK_GD_Depletion_Fact] PRIMARY KEY ([Depletion Fact Id])
);


