CREATE TABLE [GDOut].[GD_Depletion_Fact] (
    [Depletion Fact Id]            VARCHAR (20)   NOT NULL,
    [Depletion Fact URL]           NVARCHAR (200) NULL,
    [Depletion Fact Name]          VARCHAR (100)  NULL,
    [Depletion Fact Type]          VARCHAR (20)   NULL,
    [Created Date]                   DATE       NULL,
    [Modified Date]                  DATE       NULL,
    [Product Dim Id]               VARCHAR (20)   NULL,
    [Geography Dim Id]             VARCHAR (20)   NULL,
    [Transaction Type Id]          VARCHAR (5)    NULL,
    [Txn Date]                       DATE       NULL,
    [Fiscal Date]                    DATE       NULL,
    [Fiscal Year]                  VARCHAR (6)    NULL,
    [Fiscal Month]                 VARCHAR (4)    NULL,
    [Txn Alt Date]                   DATE       NULL,
    [Depletion Key]                VARCHAR (100)  NULL,
    [Depletion Source File]        VARCHAR (60)   NULL,
    [Depletion Physical Cases]       DECIMAL(14, 4)   NULL,
    [Depletion 9L Cases]             DECIMAL(14, 4)   NULL,
    [Depletion Full Case Equivalent] DECIMAL(14, 4)   NULL,
    [Depletion Primary Volume]       DECIMAL(14, 4)   NULL,
    [Depletion Secondary Volume]     DECIMAL(14, 4)   NULL,
    [Depletion Opening Balance]      DECIMAL(14, 4)   NULL,
    [Depletion Closing Balance]      DECIMAL(14, 4)   NULL,
    [Depletion On Order]             DECIMAL(14, 4)  NULL,
    [Depletion Adjustments]           DECIMAL(14, 4)   NULL,
    [Depletion In Bond]              DECIMAL(14, 4)   NULL,
    [Depletion Receipts]             DECIMAL(14, 4)   NULL,
    [Depletion Wholesale Sales]      DECIMAL(14, 4)   NULL,
    [Depletion Transfers In]         DECIMAL(14, 4)   NULL,
    [Depletion Transfers Out]        DECIMAL(14, 4)   NULL,
    [Depletion Custom 1]           NVARCHAR (200) NULL,
    [Depletion Custom 2]           NVARCHAR (200) NULL,
    [Depletion Fact 1]               VARCHAR (50)   NULL,
    [Depletion Fact 2]               VARCHAR (50)   NULL,
    [Account Dim Id]               VARCHAR (20)   NULL,
    [Depletion Rpt Current Ind]    VARCHAR (3)    NULL,
    [Fiscal Date Dim Id]             DATE       NULL,
    [Depletion Dist Item Number]   VARCHAR (50)   NULL,
    [Acct Univ Dim Id]             VARCHAR (20)   NULL,
    [Depletion Source System]      VARCHAR (10)   NULL,
    [Start Date]                     DATE       NULL,
    [End Date]                       DATE       NULL,
    [Txn_Date_Id]                    VARCHAR (50)   NULL,
    [Txn_Alt_Date_Id]                VARCHAR (50)   NULL,
    [Fiscal_Date_Id]                 VARCHAR (50)   NULL,
    [Start_Date_Id]                  VARCHAR (50)   NULL,
    [End_Date_Id]                    VARCHAR (50)   NULL, 
    [Depletion Breakage] DECIMAL(14, 4) NULL, 
    [Depletion Military Off Premise] DECIMAL(14, 4) NULL, 
    [Depletion Military On Premise] DECIMAL(14, 4) NULL, 
    [Depletion Non Retail Sales] DECIMAL(14, 4) NULL, 
    [Depletion Samples] DECIMAL(14, 4) NULL, 
    [Depletion Sub Distributor Sales] DECIMAL(14, 4) NULL, 
    [Depletion Supplier Returns] DECIMAL(14, 4) NULL, 
    [Depletion Total Off Premise] DECIMAL(14, 4) NULL, 
    [Depletion Total On Premise] DECIMAL(14, 4) NULL, 
    [Depletion Transportation] DECIMAL(14, 4) NULL, 
    [Depletion Unclassified Sales] DECIMAL(14, 4) NULL, 
    CONSTRAINT [PK_GD_Depletion_Fact] PRIMARY KEY ([Depletion Fact Id])
);


