CREATE TABLE [GDOut].[GD_Event_Call_Fact] (
    [Event_Call_Fact_Key]     VARCHAR(50) NOT NULL,
    [Created Date]            CHAR(10)    NULL,
    [Modified Date]           CHAR(10)    NULL,
    [Start_Date]              CHAR(10)    NULL,
    [End_Date]                CHAR(10)    NULL,
    [Txn_Date]                CHAR(10)    NULL,
    [Create Date]             CHAR(10)    NULL,
    [Fiscal Date]             CHAR(10)    NULL,
    [Fiscal Month]            CHAR(2)     NULL,
    [Fiscal Year]             CHAR(4)     NULL,
    [Fiscal_Date_Dim_Id]      CHAR(10)    NULL,
    [Event Fact Id]           CHAR(18)    NULL DEFAULT '-1',
    [Account Call Fact Id]    CHAR(18)    NULL DEFAULT '-1',
    [Contact Dim Id]          CHAR(18)    NULL DEFAULT '-1',
    [Person Dim Id]           CHAR(18)    NULL DEFAULT '-1',
    [Account Dim Id]          CHAR(18)    NULL DEFAULT '-1',
    [Acct Univ Dim Id]        CHAR(18)    NULL DEFAULT '-1',
    [Product Dim Id]          CHAR(18)    NULL DEFAULT '-1',
    [Geography Dim Id]        CHAR(18)    NULL DEFAULT '-1',
    [Event_Call_Sequence]     VARCHAR(10) NULL,
    [Event_Call_Activity_Key] VARCHAR(50) NULL,
    [Event_Call_Date]         CHAR(10)    NULL,
    [Event_Call_Time]         CHAR(5)     NULL,
    [Event_Call_Week]         CHAR(2)     NULL,
    [Event_Call_Year]         CHAR(4)     NULL,
    [Start_Date_Id]           CHAR(5)     NULL,
    [End_Date_Id]             CHAR(5)     NULL,
    [Txn_Date_Id]             CHAR(5)     NULL,
    [Create_Date_Id]          CHAR(5)     NULL,
    [Fiscal_Date_Id]          CHAR(5)     NULL, 
    CONSTRAINT [PK_GD_Event_Call_Fact] PRIMARY KEY ([Event_Call_Fact_Key])
);


