CREATE TABLE [GDOut].[GD_Event_Fact] (
    [Event Fact Id]           CHAR     (18)   NOT NULL DEFAULT '-1',
    [Event Fact URL]          NVARCHAR (250)  NULL,
    [Created Date]            CHAR     (10)   NULL,
    [Modified Date]           CHAR     (10)   NULL,
    [Txn Date]                CHAR     (10)   NULL,
    [Txn Alt Date]            CHAR     (10)   NULL,
    [Create Date]             CHAR     (10)   NULL,
    [Fiscal_Date]             CHAR     (10)   NULL,
    [Fiscal_Month]            VARCHAR  (4)    NULL,
    [Fiscal_Year]             VARCHAR  (6)    NULL,
    [Fiscal Date Dim Id]      VARCHAR  (18)   NULL,
    [Account Dim Id]          CHAR     (18)   NULL DEFAULT '-1',
    [Acct Univ Dim Id]        CHAR     (18)   NULL DEFAULT '-1',
    [Contact Dim Id]          CHAR     (18)   NULL DEFAULT '-1',
    [Person Dim Id]           CHAR     (18)   NULL DEFAULT '-1',
    [Geography Dim Id]        CHAR     (18)   NULL DEFAULT '-1',
    [Product Dim Id]          CHAR     (18)   NULL DEFAULT '-1',
    [Transaction Type Id]     CHAR     (18)   NULL DEFAULT 'EVT',
    [Event Id]                VARCHAR  (20)   NULL,
    [Event URL]               NVARCHAR (250)  NULL,
    [Event Subject]           VARCHAR  (255)  NULL,
    [Event Location]          VARCHAR  (255)  NULL,
    [Event Is All Day]        VARCHAR  (6)    NULL,
    [Event Duration Min]      VARCHAR  (10)   NULL,
    [Event Date]              CHAR     (10)   NULL,
    [Event Start Time]        VARCHAR  (12)   NULL,
    [Event End Time]          VARCHAR  (12)   NULL,
    [Event Description]       NVARCHAR (2000) NULL,
    [Event Type]              NVARCHAR (200)  NULL,
    [Event Is Private]        VARCHAR  (10)   NULL,
    [Event Show As]           VARCHAR  (20)   NULL,
    [Event Is Group]          VARCHAR  (20)   NULL,
    [Event Group Type]        VARCHAR  (10)   NULL,
    [Event Is Recurrence]     VARCHAR  (10)   NULL,
    [Event Recurrence Type]   VARCHAR  (30)   NULL,
    [Event Is Past]           VARCHAR  (30)   NULL,
    [Event Key]               VARCHAR  (50)   NULL,
    [Event Approved]          VARCHAR  (10)   NULL,
    [Event Rpt Current Ind]   VARCHAR  (10)   NULL,
    [Event Rpt From Date]     CHAR     (10)   NULL,
    [Txn_Date_Id]             CHAR     (8)    NULL,
    [Txn_Alt_Date_Id]         CHAR     (8)    NULL,
    [Create_Date_Id]          CHAR     (8)    NULL,
    [Fiscal_Date_Id]          CHAR     (8)    NULL,
    [Rpt_From_Date_Id]        CHAR     (8)    NULL, 
    CONSTRAINT [PK_GD_Event_Fact] PRIMARY KEY ([Event Fact Id])
);


