CREATE TABLE [GDOut].[GD_Media_Fact](
	[Media Fact Id] [char](18),
	[Media Name] [nvarchar](100) NULL,
	[Media URL] [nvarchar](200) NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Person Dim Id] [char](18) NULL,
	[Account Dim Id] [char](18) NULL,
	[Acct Univ Dim Id] [char](18) NULL,
	[Product Dim Id] [char](18) NULL,
	[Txn Type Id] [nvarchar](3) NULL,
	[Txn Date] [datetime] NULL,
	[Fiscal Date] [datetime] NULL,
	[Fiscal Date Dim Id] [datetime] NULL,
	[Media Date Time] [datetime] NULL,
	[Media Date] [datetime] NULL,
	[Media Time] [datetime] NULL,
	[Media Key] [nvarchar](19) NULL,
	[Media Record Type] [varchar](6) NULL,
	[Media Attachments] [smallint] NULL,
	[Media Comments] [varchar](6) NULL,
	[Media Geocode] [varchar](35) NULL,
	[Media Latitude] [bigint] NULL,
	[Media Longitude] [bigint] NULL,
	[Media Distance] [int] NULL,
	[Media Heading] [varchar](max) NULL,
	[Media Location] [varchar](8) NULL,
	[Media Type] [varchar](13) NULL,
	[Media Competitor Name] [varchar](max) NULL,
	[Media Competitor Type] [varchar](max) NULL,
	[Media Attachment Id] [varchar](18) NULL,
	[Media Dashboard Image] [varchar](98) NULL,
	[Media Table Image] [varchar](83) NULL,
	[Media Product Id] [varchar](18) NULL,
	[Media Product Name] [varchar](28) NULL,
	[Media Product URL] [varchar](49) NULL,
	[Media Product Ownership] [varchar](5) NULL,
	[Media Product Type] [varchar](18) NULL,
	[Media Product Size Key] [varchar](max) NULL,
	[Txn_Date_Id] [int] NULL,
	[Fiscal_Date_Id] [int] NULL,
	 CONSTRAINT [PK_GD_Media_Fact] PRIMARY KEY ([Media Fact Id])
) ON [PRIMARY]
GO