CREATE TABLE [GDOut].[GD_Objective_Fact](
	[Objective Fact Id]                [char](18)      NOT NULL,
	[Created Date]                     [char](10)      NULL,
	[Modified Date]                    [char](10)      NULL,
	[Account Dim Id]                   [char](18)      NULL,
	[Acct Univ Dim Id]                 [char](18)      NULL,
	[Currency Dim Id]                  [char](18)      NULL,
	[Fiscal Date Dim Id]               [char](10)      NULL,
	[Geography Dim Id]                 [char](18)      NULL,
	[Product Dim Id]                   [char](18)      NULL,
	[Person Dim Id]                    [char](18)      NULL,
	[Spend Dim Id]                     [char](18)      NULL,
	[Survey Dim Id]                    [char](18)      NULL,
	[Survey Fact Id]                   [char](18)      NULL,
	[Account Call Fact Id]             [char](18)      NULL,
	[Txn Type Id]                      [varchar](10)   NULL,
	[Transaction Date]                 [char](10)      NULL,
	[Fiscal Date]                      [char](10)      NULL,
	[Fiscal Year]                      [char](4)       NULL,
	[Fiscal Month]                     [char](2)       NULL,
	[Start Date]                       [char](10)      NULL,
	[End Date]                         [char](10)      NULL,
	[Create Date]                      [char](10)      NULL,
	[Rpt From Date]                    [char](10)      NULL,
	[Rpt Thru Date]                    [char](10)      NULL,
	[Rpt Current Ind]                  [varchar](5)    NULL,
	[Objective Id]                     [char](18)      NULL,
	[Objective Name]                   [nvarchar](100) NULL,
	[Objective URL]                    [nvarchar](250) NULL,
	[Objective Ext Id]                 [varchar](30)   NULL,
	[Objective Priority]               [varchar](20)   NULL,
	[Objective Status]                 [nvarchar](25)  NULL,
	[Objective Type]                   [nvarchar](50)  NULL,
	[Objective Description]            [nvarchar](500) NULL,
	[Objective Details]                [nvarchar](500) NULL,
	[Objective Results]                [nvarchar](500) NULL,
	[Objective Custom 1]               [nvarchar](255) NULL,
	[Objective Custom 2]               [nvarchar](255) NULL,
	[Objective Custom 3]               [nvarchar](255) NULL,
	[Objective Custom 4]               [nvarchar](255) NULL,
	[Objective Custom 5]               [nvarchar](255) NULL,
	[Objective Custom Checkbox 1]      [varchar](10)   NULL,
	[Objective Custom Checkbox 2]      [varchar](10)   NULL,
	[Objective Custom Picklist 1]      [nvarchar](200) NULL,
	[Objective Custom Picklist 2]      [nvarchar](200) NULL,
	[Objective Custom Picklist 3]      [nvarchar](200) NULL,
	[Objective Custom Picklist 4]      [nvarchar](200) NULL,
	[Objective Case Per Year]          [decimal](8,2)  NULL,
	[Objective Custom Currency 1]      [money]         NULL,
	[Objective Custom Currency 2]      [money]         NULL,
	[Objective Custom Fact 1]          [decimal](12,8) NULL,
	[Objective Custom Fact 2]          [decimal](12,8) NULL,
	[Objective Sequence]               [nvarchar](10)  NULL,
	[Objective Product Level]          [varchar](15)   NULL,
	[Objective Product Name]           [nvarchar](100) NULL,
	[Objective Fact Granularity]       [varchar](30)   NULL,
	[Objective Plan Id]                [char](18)      NULL,
	[Objective Plan Name]              [nvarchar](100) NULL,
	[Objective Plan URL]               [varchar](250)  NULL,
	[Objective Plan Import]            [varchar](20)   NULL,
	[Objective Plan Ind]               [varchar](10)   NULL,
	[Objective Plan Description]       [nvarchar](255) NULL,
	[Txn Alt Date]                     [char](10)      NULL,
	[Objective Survey Question Points] [decimal](12,8) NULL,
	[Account Team Dim Id]              [char](18)      NULL,
	[Sales Division Dim Id]            [char](18)      NULL,
	[Txn_Date_Id]                      [char](5)       NULL,
	[Txn_Alt_Date_Id]                  [char](5)       NULL,
	[Fiscal_Date_Id]                   [char](5)       NULL,
	[Start_Date_Id]                    [char](5)       NULL,
	[End_Date_Id]                      [char](5)       NULL,
	[Create_Date_Id]                   [char](5)       NULL,
	[Rpt_From_Date_Id]                 [char](5)       NULL,
	[Rpt_Thru_Date_Id]                 [char](5)       NULL,
	[Product Set Dim Id]               [char](18)      NULL,
	[Sales Goal Fact Id]               [char](18)      NULL,
	CONSTRAINT [PK_GD_Objective_Fact] PRIMARY KEY ([Objective Fact Id])
) ON [PRIMARY]
GO