CREATE TABLE [GDOut].[GD_RAD_Fact](
	["RAD Fact Id"] [char](18),
	["RAD Fact Name"] [varchar](300) NULL,
	["RAD Fact URL"] [nvarchar](200) NULL,
	["RAD Fact Type"] [varchar](8) NULL,
	[Created Date] [date] NULL,
	[Modified Date] [date] NULL,
	["Account Dim Id"] [char](18) NULL,
	["Account Universe Dim Id"] [char](18) NULL,
	["Product Dim Id"] [char](18) NULL,
	["Geography Dim Id"] [char](18) NULL,
	["Transaction Type Id"] [varchar](5) NULL,
	[Txn Date] [date] NULL,
	[Fiscal Date] [date] NULL,
	["Fiscal Year"] [varchar](6) NULL,
	["Fiscal Month"] [varchar](4) NULL,
	[Txn Alt Date] [date] NULL,
	["RAD Key"] [varchar](49) NULL,
	["RAD Source File"] [varchar](28) NULL,
	["RAD POD Key"] [varchar](29) NULL,
	[RAD Physical Cases] [real] NULL,
	[RAD 9L Cases] [real] NULL,
	[RAD Full Case Equivalent] [real] NULL,
	[RAD Primary Volume] [smallint] NULL,
	[RAD Secondary Volume] [smallint] NULL,
	[RAD Extended Price 1] [real] NULL,
	[RAD Custom 1"] [varchar](max) NULL,
	[RAD Custom 2"] [varchar](max) NULL,
	[RAD Fact 1] [varchar](max) NULL,
	[RAD Fact 2] [varchar](max) NULL,
	[Person Dim Id"] [varchar](20) NULL,
	[RAD Rpt Current Ind"] [varchar](3) NULL,
	[Fiscal Date Dim Id] [datetime] NULL,
	["Sales Rep Dim Id"] [varchar](4) NULL,
	["Currency Dim Id"] [varchar](5) NULL,
	["RAD Invoice Number"] [varchar](max) NULL,
	["RAD Outlet Key"] [varchar](max) NULL,
	["RAD Dist Item Number"] [varchar](max) NULL,
	["RAD Sales Rep Code"] [varchar](max) NULL,
	["RAD Sales Rep Name"] [varchar](22) NULL,
	[RAD Bottle Deposit Amount] [varchar](max) NULL,
	[RAD Tax Amount] [varchar](max) NULL,
	[RAD Addl Charges Amount] [varchar](max) NULL,
	[RAD Extended Price 2] [varchar](max) NULL,
	["RAD POD Brand Key"] [varchar](39) NULL,
	["RAD POD Label Key"] [varchar](39) NULL,
	["RAD POD Item Key"] [varchar](39) NULL,
	[RAD Rpt From Date] [datetime] NULL,
	["RAD Source System"] [varchar](5) NULL,
	["Contact Dim Id"] [varchar](4) NULL,
	[Start Date] [date] NULL,
	[End Date] [date] NULL,
	["Account Team Dim Id"] [varchar](4) NULL,
	["Sales Division Dim Id"] [varchar](4) NULL,
	[Txn_Date_Id] [int] NULL,
	[Fiscal_Date_Id] [int] NULL,
	[Txn_Alt_Date_Id] [int] NULL,
	[Start_Date_Id] [int] NULL,
	[End_Date_Id] [int] NULL,
	[Rpt_From_Date_Id] [int] NULL,
	[Alt_Start_Date] [date] NULL,
	[Alt_End_Date] [date] NULL,
	[Alt_Start_Date_Id] [int] NULL,
	[Alt_End_Date_Id] [int] NULL,
	  CONSTRAINT [PK_GD_RAD_Fact] PRIMARY KEY (["RAD Fact Id"])
) ON [PRIMARY]
GO