CREATE TABLE [GDOut].[GD_Sales_Goal_Item](
	[Sales Goal Fact Id] [varchar](50) NOT NULL,
	[Sales Goal Id] [varchar](50) NULL,
	[Sales Goal Name] [varchar](300) NULL,
	[Created Date] [varchar](50) NULL,
	[Modified Date] [varchar](50) NULL,
	[Account] [varchar](50) NULL,
	[Account Dim Id] [varchar](50) NULL,
	[Active Ind] [varchar](50) NULL,
	[Brand] [varchar](50) NULL,
	[Brand-Size] [varchar](50) NULL,
	[Custom End Date] [varchar](50) NULL,
	[Division] [varchar](50) NULL,
	[End Date] [varchar](50) NULL,
	[Geography Dim Id] [varchar](50) NULL,
	[Item] [varchar](50) NULL,
	[Item_9L_Equivalent] [varchar](50) NULL,
	[Item_Full_Case_Equivalent] [varchar](50) NULL,
	[Item_Id] [varchar](50) NULL,
	[Item_Number] [varchar](50) NULL,
	[Item_Primary_Equivalent] [varchar](50) NULL,
	[Item_Secondary_Equivalent] [varchar](50) NULL,
	[Item_Units] [varchar](50) NULL,
	[Label] [varchar](50) NULL,
	[Label-Size] [varchar](50) NULL,
	[Product_Dim_Granularity] [varchar](50) NULL,
	[Product_Dim_Id] [varchar](50) NULL,
	[Program] [varchar](50) NULL,
	[Region] [varchar](50) NULL,
	[Sales Goal 9L Cases] [varchar](50) NULL,
	[Sales Goal Estimate] [varchar](50) NULL,
	[Sales Goal Estimate 9L Cases] [varchar](50) NULL,
	[Sales Goal Estimate Cases] [varchar](50) NULL,
	[Sales Goal Full Case Equivalent] [varchar](50) NULL,
	[Sales Goal Key] [varchar](50) NULL,
	[Sales Goal Mid Period 9L Cases] [varchar](50) NULL,
	[Sales Goal Mid Period Cases] [varchar](50) NULL,
	[Sales Goal Mid-Period] [varchar](50) NULL,
	[Sales Goal Period Type] [varchar](50) NULL,
	[Sales Goal Physical Cases] [varchar](50) NULL,
	[Sales Goal Primary Volume] [varchar](50) NULL,
	[Sales Goal Quantity] [varchar](50) NULL,
	[Sales Goal Quantity Type] [varchar](50) NULL,
	[Sales Goal Record Type] [varchar](50) NULL,
	[Sales Goal Secondary Volume] [varchar](50) NULL,
	[Sales Goal Txn Type] [varchar](50) NULL,
	[Sales Goal Type] [varchar](50) NULL,
	[Size] [varchar](50) NULL,
	[Start Date] [varchar](50) NULL,
	[Survey Bank] [varchar](50) NULL,
	[Survey Dim Id] [varchar](50) NULL,
	[Survey Plan] [varchar](50) NULL,
	[Territory] [varchar](50) NULL,
	[Txn Type] [varchar](50) NULL,
	[Txn Type Id] [varchar](50) NULL,
	[User] [varchar](50) NULL,
	[Sales Goal Category] [varchar](50) NULL,
	[Account Premise Type] [varchar](50) NULL,
	[Account Segment] [varchar](50) NULL,
	[Sales Driver] [varchar](50) NULL,
	[Sales Goal Weight] [varchar](50) NULL,
	[Sales Goal Custom 1] [varchar](50) NULL,
	[Sales Goal Custom 2] [varchar](50) NULL,
	[Sales Goal Custom 3] [varchar](50) NULL,
	[Sales Goal Custom 4] [varchar](50) NULL,
	[Sales Goal Custom 5] [varchar](50) NULL,
	[Sales Goal Custom Fact 1] [varchar](50) NULL,
	[Sales Goal Custom Fact 2] [varchar](50) NULL,
	[Sales Goal Custom Fact 3] [varchar](50) NULL,
	[Account Record Type Id] [varchar](50) NULL,
	[Sales Goal Fact Granularity] [varchar](50) NULL,
	[Objective Fact Id] [varchar](50) NULL,
	[Account Set Dim Id] [varchar](50) NULL,
	[Product Set Dim Id] [varchar](50) NULL,
	[Sales Division Dim Id] [varchar](50) NULL,
	[Account Type Dim Id] [varchar](50) NULL,
	[Sales Goal Reference Report Id] [varchar](50) NULL,
	[Sales Goal Status] [varchar](50) NULL,
	[Sales Goal Reported Result] [varchar](50) NULL,
	[Sales Goal Master Id] [varchar](50) NULL,
	[Sales Goal Master Ind] [varchar](50) NULL,
	[Sales Goal Plan Id] [varchar](50) NULL,
	[Sales Goal Plan Number] [varchar](50) NULL,
	[Sales Goal Plan Name] [varchar](1000) NULL,
	[Sales Goal Plan Description] [varchar](1000) NULL,
	[Sales Goal Plan Parent Id] [varchar](50) NULL,
	[Sales Goal Plan Ind] [varchar](50) NULL,
	[Sales Goal Product Name] [varchar](100) NULL, 
    CONSTRAINT [PK_GD_Sales_Goal_Item] PRIMARY KEY ([Sales Goal Fact Id])
)


