CREATE TABLE [GDOut].[GD_Spend_Fact](
[Spend Fact Id]						Char(18) NOT NULL,					
[Spend Fact URL]					nvarchar(100) NULL,                
[Spend Fact Name]					nvarchar(100) NULL,                
[Spend Fact Type]         			nvarchar(20) NULL,                 
[Created Date]                   	char (10) NULL,                    
[Modified Date]                    	char (10) NULL,                    
[Txn Date]                          char (10) NULL,                    
[Fiscal Year]                       int NULL,                          
[Fiscal Month]                      nvarchar(2) NULL,                          
[Fiscal Date]                       char (10) NULL,                    
[Fiscal Date Dim Id]                char (10) NULL,                    
[Txn Alt Date]                      char (10) NULL,                    
[Person Dim Id]                     char (18) NULL,                    
[Spend Dim Id]                      char (18) NULL,                    
[Geography Dim Id]                  char (18) NULL,                    
[Product Dim Id]                    char (18) NULL,                    
[Account Dim Id]                    char (18) NULL,                    
[Acct Univ Dim Id]                  char (18) NULL,                    
[Currency Dim Id]                   char (18) NULL,                    
[Txn Type Id]                       char (5) NULL,                     
[Spend Owner Id]                    char (18) NULL,                    
[Spend Owner URL]                   nvarchar(100) NULL,                
[Spend Owner Username]              nvarchar(50) NULL,                 
[Spend Owner Full Name]             nvarchar(100) NULL,                
[Spend Owner Last Name]             nvarchar(50) NULL,                 
[Spend Owner First Name]            nvarchar(50) NULL,                 
[Spend Owner Email]                 nvarchar(50) NULL,                 
[Spend Owner Key]                   nvarchar(50) NULL,                 
[Invoice Id]                        char (18) NULL,                    
[Invoice URL]                       nvarchar(100) NULL,                
[Invoice Name]                      nvarchar(30) NULL,                 
[Invoice Number]                    nvarchar(50) NULL,                 
[Invoice Notes]                     nvarchar(250) NULL,                
[Invoice Status]                    nvarchar(50) NULL,                 
[Invoice Amount]                    nvarchar(20) NULL,                             
[Invoice Type]                      nvarchar(20) NULL,                 
[Invoice Action Amount]             nvarchar(20) NULL,                             
[Invoice Action Reason]             Char(5),                           
[Invoice Payment Method]            nvarchar(10) NULL,                 
[Invoice Posting Date]              char(10) NULL,                     
[Invoice Custom Text 1]             nvarchar(50) NULL,                 
[Invoice Custom Text 2]             nvarchar(50) NULL,                 
[Invoice Custom Text 3]             nvarchar(50) NULL,                 
[Invoice Custom Text 4]             nvarchar(50) NULL,                 
[Invoice Custom Text 5]             nvarchar(50) NULL,                 
[Invoice Custom Picklist 1]         nvarchar(20) NULL,                 
[Invoice Custom Picklist 2]         nvarchar(20) NULL,                 
[Invoice Custom Number 1]           nvarchar(20) NULL,                 
[Invoice Custom Number 2]           nvarchar(20) NULL,                 
[Invoice Custom Currency 1]         nvarchar(20) NULL,                 
[Invoice Custom Currency 2]         nvarchar(20) NULL,                 
[Planned Spend Id]                  Char(18) NULL,                     
[Planned Spend URL]                 nvarchar(100) NULL,                
[Planned Spend Name]                nvarchar(100) NULL,                
[Planned Spend Description]         nvarchar(200) NULL,                
[Planned Spend Status]              nvarchar(10) NULL,                 
[Planned Spend Amount]              nvarchar(20) NULL,                             
[Planned Spend Type]                nvarchar(20) NULL,                 
[Planned Spend Custom 1]            nvarchar(100) NULL,                
[Planned Spend Custom 2]            nvarchar(100) NULL,                
[Planned Spend Custom 3]            nvarchar(100) NULL,                
[Planned Spend Custom 4]            nvarchar(100) NULL,                
[Planned Spend Custom 5]            nvarchar(100) NULL,                
[Planned Spend Custom Picklist 1]   nvarchar(10) NULL,                 
[Planned Spend Custom Picklist 2]   nvarchar(10) NULL,                 
[Planned Spend Custom Number 1]     nvarchar(10) NULL,                 
[Planned Spend Custom Number 2]     nvarchar(10) NULL,                 
[Planned Spend Custom Currency 1]   nvarchar(10) NULL,                 
[Planned Spend Custom Currency 2]   nvarchar(10) NULL,                 
[Planned Spend Custom Checkbox 1]   nvarchar(10) NULL,                 
[Planned Spend Custom Checkbox 2]   nvarchar(10) NULL,                 
[Expense Id]                        Char(18) NULL,                     
[Expense URL]                       nvarchar(100) NULL,                
[Expense Name]                      nvarchar(20) NULL,                 
[Expense Notes]                     nvarchar(200) NULL,                
[Expense Description]               nvarchar(300) NULL,                
[Expense Status]                    nvarchar(20) NULL,                 
[Expense Amount]                    nvarchar(20) NULL,                             
[Expense Approval Status]           nvarchar(20) NULL,                 
[Expense Linked Amount]             nvarchar(20) NULL,                             
[Expense POS Code]                  nvarchar(20) NULL,                 
[Expense POS Name]                  nvarchar(20) NULL,                 
[Expense Planned Amount]            nvarchar(20) NULL,                             
[Expense Quantity]                  nvarchar(10) NULL,                          
[Expense Type]                      nvarchar(20) NULL,                 
[Expense Link Type]                 nvarchar(20) NULL,                 
[Expense Spend Type]                nvarchar(50) NULL,                 
[Expense Custom 1]                  nvarchar(50) NULL,                 
[Expense Custom 2]                  nvarchar(50) NULL,                 
[Expense Custom 3]                  nvarchar(50) NULL,                 
[Expense Custom 4]                  nvarchar(50) NULL,                 
[Expense Custom 5]                  nvarchar(50) NULL,                 
[Expense Custom Picklist 1]         nvarchar(50) NULL,                 
[Expense Custom Picklist 2]         nvarchar(50) NULL,                 
[Expense Custom Picklist 3]         nvarchar(50) NULL,                 
[Expense Custom Picklist 4]         nvarchar(50) NULL,                 
[Expense Custom Number 1]           nvarchar(50) NULL,                 
[Expense Custom Number 2]           nvarchar(50) NULL,                 
[Expense Custom Currency 1]         nvarchar(50) NULL,                 
[Expense Custom Currency 2]         nvarchar(50) NULL,                 
[Spend Fact Custom Date 1]          Char(10) NULL,                     
[Spend Fact Custom Date 2]			Char(10) NULL,
[Txn_Date_Id]						int NULL,
[Fiscal_Date_Id]					int NULL,
[Txn_Alt_Date_Id]					int NULL
CONSTRAINT [PK_GD_Spend_Fact] PRIMARY KEY ([Spend Fact Id])
)
