CREATE TABLE [GDOut].[GD_Sales_Order_Fact](
	[Sales Order Fact Id]                               [char](18)      NOT NULL,
	[Sales Order Fact Name]                             [varchar](100)  NULL,
	[Sales Order Fact URL]                              [varchar](250)  NULL,
	[Sales Order Fact Type]                             [varchar](50)   NULL,
	[Created Date]                                      [char](10)      NULL,
	[Modified Date]                                     [char](10)      NULL,
	[Account Dim Id]                                    [char](18)      NULL DEFAULT '-1',
	[Acct Univ Dim Id]                                  [char](18)      NULL DEFAULT '-1',
	[Product Dim Id]                                    [char](18)      NULL DEFAULT '-1',
	[Geography Dim Id]                                  [char](18)      NULL DEFAULT '-1',
	[Person Dim Id]                                     [char](18)      NULL DEFAULT '-1',
	[Transaction Type Id]                               [char](18)      NULL DEFAULT '-1',
	[Transaction Date]                                  [char](10)      NULL,
	[Fiscal Date]                                       [char](10)      NULL,
	[Fiscal Year]                                       [char](4)       NULL,
	[Fiscal Month]                                      [char](2)       NULL,
	[Transaction Alt Date]                              [char](10)      NULL,
	[Start Date]                                        [char](10)      NULL,
	[End Date]                                          [char](10)      NULL,
	[Sales Order Id]                                    [char](18)      NULL,
	[Sales Order Name]                                  [varchar](100)  NULL,
	[Sales Order URL]                                   [varchar](250)  NULL,
	[Sales Order Key]                                   [varchar](100)  NULL,
	[Sales Order Number]                                [varchar](50)   NULL,
	[Sales Order Tracking Number]                       [varchar](50)   NULL,
	[Sales Order Will Call]                             [varchar](50)   NULL,
	[Sales Order Status]                                [varchar](100)  NULL,
	[Sales Order Type]                                  [varchar](100)  NULL,
	[Sales Order Item Id]                               [char](18)      NULL,
	[Sales Order Item Name]                             [varchar](100)  NULL,
	[Sales Order Item URL]                              [varchar](250)  NULL,
	[Sales Order Item Key]                              [varchar](100)  NULL,
	[Sales Order Item Line]                             [varchar](50)   NULL,
	[Sales Order Item POD Key]                          [varchar](100)  NULL,
	[Sales Order Item Price Level]                      [varchar](100)  NULL,
	[Sales Order Item Price]                            [varchar](50)   NULL,
	[Sales Order Item Extended Price]                   [varchar](50)   NULL,
	[Sales Order Item Unit]                             [varchar](50)   NULL,
	[Sales Order Item Quantity]                         [varchar](50)   NULL,
	[Sales Order Item Physical Cases]                   [varchar](50)   NULL,
	[Sales Order Item 9L Cases]                         [varchar](50)   NULL,
	[Sales Order Item Full Case Equivalent]             [varchar](50)   NULL,
	[Sales Order Item Primary Volume]                   [varchar](50)   NULL,
	[Sales Order Item Secondary Volume]                 [varchar](50)   NULL,
	[Fiscal Date Dim Id]                                [char](10)      NULL,
	[Sales Order POD Item Key]                          [varchar](100)  NULL,
	[Sales Order POD Label Key]                         [varchar](100)  NULL,
	[Sales Order POD Brand Key]                         [varchar](100)  NULL,
	[Currency Dim Id]                                   [char](18)      NULL DEFAULT 'USD',
	[Contact Dim Id]                                    [char](18)      NULL DEFAULT '-1',
	[Sales Order Item Qty per Carton]                   [varchar](50)   NULL,		
    [Sales Order Item Supplier Provided Promo Code]     [varchar](50)   NULL,
	[Sales Order Item Distributor Repack]               [varchar](50)   NULL,
	[Sales Order Item Invoice Item]                     [varchar](50)   NULL,
	[Sales Order Item Invoice Discount]                 [varchar](50)   NULL,
	[Sales Order Item Invoice Tax]                      [varchar](50)   NULL,
	[Sales Order Item Invoice Ext Price]                [varchar](50)   NULL,
	[Sales Order Item Supplier Discount Participation]  [varchar](50)   NULL,
	[Sales Order Item Supplier Depletion Allowance]     [varchar](50)   NULL,
	[Txn_Date_Id]                                       [varchar](10)   NULL,
	[Fiscal_Date_Id]                                    [varchar](10)   NULL,
	[Txn_Alt_Date_Id]                                   [varchar](10)   NULL,
	[Start_Date_Id]                                     [varchar](10)   NULL,
	[End_Date_Id]                                       [varchar](10)   NULL,
    CONSTRAINT [PK_GD_Sales_Order_Fact] PRIMARY KEY ([Sales Order Fact Id])
) ON [PRIMARY]
GO

