CREATE TABLE [GDOut].[GD_Sales_Goal_Fact](
	[Sales Goal Fact Id] [char](18) NOT NULL,
	[Sales Goal Fact Name] [nvarchar](150) NULL,
	[Sales Goal Fact URL] [nvarchar](200) NULL,
	[Sales Goal Fact Granularity] [nvarchar](30) NULL,
	[Account Dim Id] [char](18) NULL,
	[Acct Univ Dim Id] [char](18) NULL,
	[Geography Dim Id] [char](18) NULL,
	[Product Dim Id] [char](18) NULL,
	[Spend Dim Id] [char](18) NULL,
	[Txn Type Id] [char](18) NULL,
	[Survey Dim Id] [char](18) NULL,
	[Person Dim Id] [char](18) NULL,
	[Account Record Type Dim Id] [char](18) NULL,
	[Account Segment Dim Id] [char](18) NULL,
	[Sales Driver Dim Id] [nvarchar](20) NULL,
	[Created Date] [date] NULL,
	[Modified Date] [date] NULL,
	[Start_Date] [date] NULL,
	[End_Date] [date] NULL,
	[Txn Date] [date] NULL,
	[Fiscal Date] [date] NULL,
	[Fiscal Month] [nvarchar](5) NULL,
	[Fiscal Year] [nvarchar](5) NULL,
	[Fiscal Date Dim Id] [date] NULL,
	[Txn Alt Date] [date] NULL,
	[Sales Goal Id] [char](18) NULL,
	[Sales Goal Name] [nvarchar](100) NULL,
	[Sales Goal URL] [nvarchar](200) NULL,
	[Sales Goal Type] [nvarchar](50) NULL,
	[Sales Goal Record Type] [nvarchar](30) NULL,
	[Sales Goal Period Type] [varchar](30) NULL,
	[Sales Goal Category] [nvarchar](30) NULL,
	[Sales Goal Key] [nvarchar](30) NULL,
	[Sales Goal Physical Cases] [decimal](14,4) NULL,
	[Sales Goal 9L Cases] [decimal](14,4) NULL,
	[Sales Goal Primary Volume] [decimal](14,4) NULL,
	[Sales Goal Secondary Volume] [decimal](14,4) NULL,
	[Sales Goal Estimate Cases] [decimal](14,4) NULL,
	[Sales Goal Mid Period Cases] [decimal](14,4) NULL,
	[Sales Goal Full Case Equivalent] [decimal](14,4) NULL,
	[Sales Goal Estimate 9L Cases] [decimal](14,4) NULL,
	[Sales Goal Mid Period 9L Cases] [decimal](14,4) NULL,
	[Sales Goal Txn Type] [nvarchar](30) NULL,
	[Sales Goal Quantity Type] [varchar](30) NULL,
	[Sales Goal Quantity] [decimal](14,4) NULL,
	[Sales Goal Weight] [decimal](14,4) NULL,
	[Sales Goal Custom 1] [varchar](30) NULL,
	[Sales Goal Custom 2] [varchar](30) NULL,
	[Sales Goal Custom 3] [varchar](30) NULL,
	[Sales Goal Custom 4] [varchar](30) NULL,
	[Sales Goal Custom 5] [varchar](100) NULL,
	[Sales Goal Custom Fact 1] VARCHAR(30) NULL,
	[Sales Goal Custom Fact 2] [varchar](30) NULL,
	[Sales Goal Custom Fact 3] [varchar](30) NULL,
	[Account Type Dim Id] [char](18) NULL,
	[Account Set Dim Id]  [char](18) NULL,
	[Product Set Dim Id]  [char](18) NULL,
	[Sales Division Dim Id]  [char](18) NULL,
	[Sales Goal Reference Report Id]  [char](18) NULL,
	[Sales Goal Status] [varchar](30) NULL,
	[Sales Goal Reported Result] [decimal](14,4) NULL,
	[Sales Goal Master Id]  [char](18) NULL,
	[Sales Goal Master Ind] [varchar](30) NULL,
	[Sales Goal Plan Id] [char](18) NULL,
	[Sales Goal Plan Number] [nvarchar](50) NULL,
	[Sales Goal Plan Name] [nvarchar](250) NULL,
	[Sales Goal Plan URL] [nvarchar](250) NULL,
	[Sales Goal Plan Description] [nvarchar](350) NULL,
	[Sales Goal Plan Parent Id] [char](18) NULL,
	[Sales Goal Plan Ind] [varchar](10) NULL,
	[Sales Goal Product Name] [nvarchar](100) NULL,
	[Start_Date_Id]  [int] NULL,
	[End_Date_Id]  [int] NULL,
	[Txn_Date_Id]  [int] NULL,
	[Fiscal_Date_Id]  [int] NULL,
	[Txn_Alt_Date_Id]  [int] NULL,
	[Sales Goal Competitor Name] [nvarchar](100) NULL,
	[Sales Goal Currency Value] [decimal](14,4) NULL,
	[Sales Goal Minimum Value] [decimal](14,4) NULL,
	[Sales Goal Reference Ind] [varchar](10) NULL,
	[Sales Goal Reference Value] [decimal](14,4) NULL,
	[Sales Goal User Type] [nvarchar](30) NULL,
	[Competitor Dim Id] [char](18) NULL,
	[Sales Goal Min Qty] [decimal] (14,4) NULL,
	[Sales Goal Min Qty UOM] [varchar](30) NULL,
	[Alt_Start_Date] [date] NULL,
	[Alt_End_Date] [date] NULL,
	[Alt_Start_Date_Id]  [int] NULL,
	[Alt_End_Date_Id]  [int] NULL,
	[Sales Goal Adjustment] [varchar](50) NULL,
	[Sales Goal Adjustment Comment] [varchar](50) NULL 
    CONSTRAINT [PK_Sales_Goal_Fact_Id] PRIMARY KEY ([Sales Goal Fact Id])
) ON [PRIMARY]
GO
