create procedure Load_GD_Acct_Univ_Dim as
begin
	truncate table GDOut.GD_Acct_Univ_Dim

	insert into GDOut.GD_Acct_Univ_Dim
		select top 10 
			r.RetailerID as [Account Dim Id],
			r.RetailerLD as [Account Dim Name],
			'Account' as [Account Dim URL],
			r.LBSalesforceURL as [Account Dim URL],
			rhq.RetailerHQID as [Account Hierarchy Dim Id],
			r.RetailerID as [Account Retail Dim Id],
			r.RetailerID as [Account Custom Dim Id],
			r.SourceCreateDate as [Created Date],
			r.SourceModifiedDate as [Modified Date],
			-- Company, Territory, Division, and Region need to lookup through something, gvp__Territory_Assignment__c doesn't seem to have data
			-2 as [Company Key],
			'TODO' as [Company Name],
			-2 as [Division Key],
			'TODO' as [Division Name],
			-2 as [Region Key],
			'TODO' as [Region Name],
			-2 as [Territory Id],
			'TODO' as [Territory URL],
			'TD' as [Territory Key],
			'TODO' as [Territory Name],
			null as [Territory Custom 1],
			null as [Territory Custom 2],
			ro.RetailerOwnerID as [Account Owner ID],
			'TODO' as [Account Owner URL],
			ro.RetailerOwnerLastName as [Account Owner Last Name],
			ro.RetailerOwnerFirstName as [Account Owner First Name],
			ro.RetailerOwnerFirstName + ' ' + ro.RetailerOwnerLastName as [Account Owner Name],
			'TODO' as [Account Owner Email],
			r.RetailerID as [Account Id],
			'TODO' as [Account Level],
			r.LBSalesforceURL as [Account URL],
			r.LBSalesforceURL as [Account URL2],
			'TODO' as [Account Key],
			r.RetailerLD as [Account Name],
			'TODO' as [Account Name Number],
			pt.PremiseTypeLD as [Account Record Type],
			'TODO' as [Account Street],
			'TODO' as [Account City],
			'TODO' as [Account State],
			'TODO' as [Account Zip],
			'TODO' as [Account Country],
			'TODO' as [Account County],
			'TODO' as [Account Phone],
			'TODO' as [Account Key Account],
      'TODO' as [Account Groups],
			r.RetailerCustom1 as [Account Custom 1],
			r.RetailerCustom2 as [Account Custom 2],
			r.RetailerCustom3 as [Account Custom 3],
			'TODO' as [Account Custom 4],
			'TODO' as [Account Custom 5],
      'TODO' as [Account Segment Name],
      'TODO' as [Account Segment Key],
      'TODO' as [Account Segment Channel],
      'TODO' as [Account Banner Name],
      'TODO' as [Account Wine Indicator],
      'TODO' as [Account Liquor Indicator],
      'TODO' as [Account Beer Indicator],
      'TODO' as [Account Franchise Indicator],
      pt.PremiseTypeLD as [Account Premise Type],
      'TODO' as [Account Class of Trade],
      'TODO' as [Account Food Type],
      'TODO' as [Account Trade Channel],
      'TODO' as [Account Trade Sub Channel],
      'TODO' as [Account Chain Ind],
      pt.PremiseTypeLD as [Account On Premise Indicator],
      'TODO' as [Account Store Status],
      'TODO' as [Account Active Indicator],
      mg.MarketingGroupID as [Account Marketing Group Code],
      mg.MarketingGroupLD as [Account Marketing Group Name],
      'TODO' as [Account Marketing Group Ownership],
      'TODO' as [Account Ultimate Parent Code],
			-- find the highest numbered HQ that exists for the account
      case
				when rhq4.LBRetailerHQ4SKey > 0 then rhq4.RetailerHQ4LD
				when rhq3.LBRetailerHQ3SKey > 0 then rhq3.RetailerHQ3LD
				when rhq2.LBRetailerHQ2SKey > 0 then rhq2.RetailerHQ2LD
				when rhq.LBRetailerHQSKey > 0 then rhq.RetailerHQLD
				else null
			end as [Account Ultimate Parent Name],
      rhq.RetailerHQLD as [Account Immediate Parent Name],
      'TODO' as [Account License Type],
      'TODO' as [Account Customer Priority],
      'TODO' as [Account Format],
      'TODO' as [Account Type],
      'TODO' as [Key Acct Chain 1 Dim Id],
      'TODO' as [Key Acct Chain 2 Dim Id],
      'TODO' as [Key Acct Chain Indicator],
      mg.MarketingGroupID as [Marketing Group Dim Id],
      'TODO' as [Acct Record Type Dim Id],
      'TODO' as [Acct Segment Dim Id],
      'TODO' as [Currency Dim Id],
      'TODO' as [Account Description],
      'TODO' as [Account Custom Checkbox 1],
      'TODO' as [Account Custom Checkbox 2],
      'TODO' as [Account Custom 6],
      'TODO' as [Account Custom 7],
      'TODO' as [Account Custom 8],
      'TODO' as [Account Custom 9],
      'TODO' as [Account Custom 10],
      'TODO' as [Account Credit Available],
      'TODO' as [Account Credit Limit],
      'TODO' as [Account Credit Status],
      'TODO' as [Account License Expiration],
      'TODO' as [Account MSA Code],
      'TODO' as [Account MSA Name],
      'TODO' as [Account Resale Number],
      'TODO' as [Account Custom Date 1],
      'TODO' as [Account Custom Date 2],
      'TODO' as [Account Delivery Time],
      'TODO' as [Account Source File],
      'TODO' as [Account Warehouse],
      'TODO' as [Account Distributor Rep],
      'TODO' as [Account Distributor Team],
      'TODO' as [Account Distributor Name],
      'TODO' as [Region Custom 1],
      'TODO' as [Region Custom 2],
      'TODO' as [Division Custom 1],
      'TODO' as [Division Custom 2],
      'TODO' as [Company Custom 1],
      'TODO' as [Company Custom 2],
      'TODO' as [Account Geocode Unavailable],
      'TODO' as [Account Geocode],
      'TODO' as [Account Geocode Latitude],
      'TODO' as [Account Geocode Longitude],
      'TODO' as [Account Decision Maker Name],
      'TODO' as [Account Decision Maker Email],
      'TODO' as [Account FIPS County Geocode],
      'TODO' as [Account FIPS County Name],
      'TODO' as [KPI Segment Dim Id],
      'TODO' as [Account Shipping Street],
      'TODO' as [Account Shipping City],
      'TODO' as [Account Shipping State],
      'TODO' as [Account Shipping Zip],
      'TODO' as [Account Shipping Country],
      'TODO' as [Account Rank],
      'TODO' as [Territory Custom 3],
      'TODO' as [Territory Custom 4],
      'TODO' as [Territory Custom 5],
      'TODO' as [Division Custom 3],
      'TODO' as [Division Custom 4],
      'TODO' as [Division Custom 5],
      'TODO' as [Account Beer Volume],
      'TODO' as [Account Liquor Volume],
      'TODO' as [Account Wine Volume],
      'TODO' as [Acct Type Dim Id],
      'TODO' as [Account Owner Dim Id],
      'TODO' as [Account Zip5],
      'TODO' as [Account Shipping Zip5],
      'TODO' as [Company Id],
      'TODO' as [Division Id],
      'TODO' as [Region Id],
      'TODO' as [Create_Date_Id]
		from LiquorBarn_1_0..DimRetailer r
			inner join LiquorBarn_1_0..DimRetailerHQ rhq on rhq.LBRetailerHQSKey = r.LBRetailerHQSKey
			inner join LiquorBarn_1_0..DimRetailerHQ2 rhq2 on rhq2.LBRetailerHQ2SKey = rhq.LBRetailerHQ2SKey
			inner join LiquorBarn_1_0..DimRetailerHQ3 rhq3 on rhq3.LBRetailerHQ3SKey = rhq2.LBRetailerHQ3SKey
			inner join LiquorBarn_1_0..DimRetailerHQ4 rhq4 on rhq4.LBRetailerHQ4SKey = rhq3.LBRetailerHQ4SKey
			inner join LiquorBarn_1_0..DimRetailerOwner ro on ro.LBRetailerOwnerSKey = r.LBRetailerOwnerSKey
			inner join LiquorBarn_1_0..DimPremiseType pt on pt.LBPremiseTypeSKey = r.LBPremiseTypeSKey
			inner join LiquorBarn_1_0..DimMarketingGroup mg on mg.LBMarketingGroupSKey = r.LBMarketingGroupSKey
		where rhq.LBRetailerHQSKey <> -1




end