CREATE TABLE GVP.gvp__Account_Activity__c
(
	[Id]                                 char(18)      not null,
	IsDeleted                            varchar(10)   not null,
	CreatedById                          char(18)      not null,
	CreatedDate                          datetime      not null,
	LastActivityDate                     date          null,
	LastModifiedById                     char(18)      not null,
	LastModifiedDate                     datetime      not null,
	[Name]                               varchar(100)  not null,
	RecordTypeId                         char(18)      null,
	SystemModstamp                       datetime      not null,
	gvp__Account__c                      char(18)      null,
	gvp__Account_Call__c                 char(18)      null,
	gvp__Account_Call_Send_Email__c      varchar(10)   null,
	gvp__Account_Call_Send_Email_Date__c date          null,
	gvp__Account_Call_Status__c          varchar(100)  null,
	gvp__Account_KPI__c                  char(18)      null,
	gvp__Activity_Goal__c                char(18)      null,
	gvp__Brand__c                        char(18)      null,
	gvp__Checkbox_1__c                   char(10)      null,
	gvp__Checkbox_2__c                   char(10)      null,
	gvp__Checkbox_3__c                   char(10)      null,
	gvp__Checkbox_4__c                   char(10)      null,
	gvp__Compliance__c                   varchar(255)  null,
	gvp__Currency_1__c                   money         null,
	gvp__Currency_2__c                   money         null,
	gvp__Currency_3__c                   money         null,
	gvp__Currency_4__c                   money         null,
	gvp__Date_1__c                       date          null,
	gvp__Date_2__c                       date          null,
	gvp__Date_3__c                       date          null,
	gvp__Date_4__c                       date          null,
	gvp__DateTime_1__c                   datetime      null,
	gvp__DateTime_2__c                   datetime      null,
	gvp__DateTime_3__c                   datetime      null,
	gvp__DateTime_4__c                   datetime      null,
	gvp__Description__c                  nvarchar(255) null,
	gvp__End_Date__c                     datetime      null,
	gvp__External_Id__c                  nvarchar(64)  null,
	gvp__Is_Current__c                   varchar(50)   null,
	gvp__Item__c                         char(18)      null,
	gvp__Label__c                        char(18)      null,
	gvp__Number_1__c                     decimal(16,2) null,
	gvp__Number_2__c                     decimal(16,2) null,
	gvp__Number_3__c                     decimal(16,2) null,
	gvp__Number_4__c                     decimal(16,2) null,
	gvp__Number_5__c                     decimal(16,2) null,
	gvp__Number_6__c                     decimal(16,2) null,
	gvp__Number_7__c                     decimal(16,2) null,
	gvp__Number_8__c                     decimal(16,2) null,
	gvp__Number_9__c                     decimal(16,2) null,
	gvp__Number_10__c                    decimal(16,2) null,
	gvp__Picklist_1__c                   nvarchar(255) null,
	gvp__Picklist_2__c                   nvarchar(255) null,
	gvp__Picklist_3__c                   nvarchar(255) null,
	gvp__Picklist_4__c                   nvarchar(255) null,
	gvp__Price__c                        money         null,
	gvp__Program__c                      char(18)      null,
	gvp__Start_Date__c                   datetime      null,
	gvp__Status__c                       varchar(255)  null,
	gvp__Text_1__c                       nvarchar(255) null,
	gvp__Text_2__c                       nvarchar(255) null,
	gvp__Text_3__c                       nvarchar(255) null,
	gvp__Text_4__c                       nvarchar(255) null,
	gvp__Text_5__c                       nvarchar(255) null,
	gvp__Text_6__c                       nvarchar(255) null,
	gvp__Text_7__c                       nvarchar(255) null,
	gvp__Text_8__c                       nvarchar(255) null,
	gvp__Text_9__c                       nvarchar(255) null,
	gvp__Text_10__c                      nvarchar(255) null,
	CONSTRAINT [PK_gvp__Account_Activity__c] PRIMARY KEY ([Id])
);