CREATE TABLE [GVW].[AccountCallSequenceDim](
	[GVWAccountCallSequenceSKey] int identity(1,1),
	[ID] [varchar](20) NOT NULL,
	[Name] [varchar](50) NULL, 
	URL NVARCHAR (100)  NULL,
	Granularity NVARCHAR (30)  NULL,
	AccountCallSequenceID [varchar](20) NULL,
	AccountCallSequenceName [varchar](50) NULL,
	AccountCallSequenceSegment [varchar](100) NULL,
	AccountCallSequenceActive [varchar](10) NULL,
	GeographyExternalID [varchar](50) NULL,
	AccountCallSequenceStepOrderNumber [decimal](4, 1) NULL,
	ProfileName [nvarchar](100) NULL,
	RecordType [char](30) NULL,
	AccountCallSequenceStepRequired [varchar](10) NULL,
	AccountCallSequenceStepID [varchar](20) NULL,
	AccountCallSequenceStepName [varchar](50) NULL,
	AccountCallSequenceStepType [varchar](50) NULL,
	AccountCallSequenceStepSubtype [varchar](30) NULL,
	AccountCallSequenceURL NVARCHAR (100)  NULL,
	AccountCallSequenceStepURL NVARCHAR (100)  NULL,
	GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0',
    [GVWHash] VARCHAR(32) NOT NULL DEFAULT 0,
	CONSTRAINT [PK_AccountCallSequenceDim] PRIMARY KEY ([GVWAccountCallSequenceSKey])
);