CREATE TABLE [GVW].[Accounts_for_HQ3](
	[Account Id] [varchar](18) NOT NULL,
	[Account URL] [nvarchar](500) NULL,
	[Account Name] [varchar](200) NULL,
	[Account City] [varchar](200) NULL,
	[Account State] [varchar](200) NULL,
	[Account Key Account] [varchar](200) NULL,
	[Account Owner Id] [varchar](18) NULL,
	[Account Owner URL] [nvarchar](500) NULL,
	[Account Owner Last Name] [varchar](200) NULL,
	[Account Owner First Name] [varchar](200) NULL,
	[Account Owner Full Name] [varchar](200) NULL,
	[Account Owner Email] [varchar](200) NULL,
	[Account Level] [varchar](200) NULL,
	[Account Key] [varchar](200) NULL,
	[Account Name Number] [varchar](500) NULL,
	[Account Custom 1] [varchar](200) NULL,
	[Account Custom 2] [varchar](200) NULL,
	[Account Custom 3] [varchar](200) NULL,
	[Account Custom 4] [varchar](200) NULL,
	[Account Custom 5] [varchar](200) NULL,
	[Parent] [varchar](200) NULL,
	[Key Acct Chain 1] [varchar](200) NULL,
	[Key Acct Chain 2] [varchar](200) NULL,
	[Territory Key] [varchar](200) NULL,
	[Territory Name] [varchar](200) NULL,
	[RecType] [varchar](200) NULL,
	[Created Date] [varchar](200) NULL,
	[Modified Date] [varchar](200) NULL, 
    CONSTRAINT [PK_Accounts_for_HQ3] PRIMARY KEY ([Account Id])
);