CREATE TABLE [GVW].[AccountsforHQ3Dim](
	[GVWAccountsforHQ3SKey] int identity(1,1),
	[ID] [varchar](18) NOT NULL,
	[URL] [nvarchar](500) NULL,
	[Name] [varchar](200) NULL,
	[City] [varchar](200) NULL,
	[State] [varchar](200) NULL,
	[KeyAccount] [varchar](200) NULL,
	[OwnerID] [varchar](18) NULL,
	[OwnerURL] [nvarchar](500) NULL,
	[OwnerLastName] [varchar](200) NULL,
	[OwnerFirstName] [varchar](200) NULL,
	[OwnerFullName] [varchar](200) NULL,
	[OwnerEmail] [varchar](200) NULL,
	[Level] [varchar](200) NULL,
	[ExternalID] [varchar](200) NULL,
	[NameNumber] [varchar](500) NULL,
	[Custom1] [varchar](200) NULL,
	[Custom2] [varchar](200) NULL,
	[Custom3] [varchar](200) NULL,
	[Custom4] [varchar](200) NULL,
	[Custom5] [varchar](200) NULL,
	[Parent] [varchar](200) NULL,
	[KeyAcctChain1] [varchar](200) NULL,
	[KeyAcctChain2] [varchar](200) NULL,
	[TerritoryExternalID] [varchar](200) NULL,
	[TerritoryName] [varchar](200) NULL,
	[RecType] [varchar](200) NULL,
	[CreatedDate] [varchar](200) NULL,
	[ModifiedDate] [varchar](200) NULL, 
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
	GVWDeleted BIT NULL DEFAULT '0'
    CONSTRAINT [PK_AccountsforHQ3Dim] PRIMARY KEY (GVWAccountsforHQ3SKey)
);