CREATE TABLE [GVW].[AccountSetDim](
	[GVWAccountSetSKey] int identity(1,1),
	[ID]              VARCHAR(18)      NOT NULL,
	[Name]            [nvarchar](100) NULL,
	[URL]             [nvarchar](250) NULL,
	[Granularity]     [varchar](50)   NULL,
	[AccountDimID]                  VARCHAR(18)      NULL,
	[CreatedDate]                    [char](10)      NULL,
	[ModifiedDate]                   [char](10)      NULL,
	[Test]                [varchar](10)   NULL,
	[MemberID]           VARCHAR(18)      NULL,
	[MemberURL]          [nvarchar](250) NULL,
	[MemberName]         [nvarchar](200) NULL,
	[AccountNameNumber] [nvarchar](250) NULL, 
	[Status]              [varchar](50)   NULL,
	[LastAccountUpdate] [char](10)      NULL,
	[ExpirationDate]     [char](10)      NULL,
	[Channel]             [nvarchar](200) NULL,
	[CustomText1]       [nvarchar](200) NULL,
	[CustomText2]       [nvarchar](200) NULL,
	[CustomText3]       [nvarchar](200) NULL,
	[CustomText4]       [nvarchar](200) NULL,
	[CustomText5]       [nvarchar](200) NULL,
	[Description]         [nvarchar](200) NULL,
	[ExternalID]         [varchar](50)   NULL,
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
	GVWDeleted BIT NULL DEFAULT '0'
    CONSTRAINT [PK_AccountSetDim] PRIMARY KEY (GVWAccountSetSKey) 
);