CREATE TABLE [GVW].[Account_Hier_Dim](
	[Account Hierarchy Dim Id] [varchar](18) NOT NULL,
	[Created Date] [datetime] NULL,
	[Modified Date] [datetime] NULL,
	[Acct HQ 4 Id] [varchar](18) NULL,
	[Acct HQ 4 URL] [nvarchar](200) NULL,
	[Acct HQ 4 Name] [nvarchar](200) NULL,
	[Acct HQ 4 Record Type] [varchar](50) NULL,
	[Acct HQ 4 City] [nvarchar](50) NULL,
	[Acct HQ 4 State] [nvarchar](100) NULL,
	[Acct HQ 4 Key Account] [varchar](50) NULL,
	[Acct HQ 4 Owner Full Name] [nvarchar](200) NULL,
	[Acct HQ 4 Owner Email] [nvarchar](200) NULL,
	[Acct HQ 3 Id] [varchar](18) NULL,
	[Acct HQ 3 URL] [nvarchar](200) NULL,
	[Acct HQ 3 Name] [nvarchar](200) NULL,
	[Acct HQ 3 Record Type] [varchar](100) NULL,
	[Acct HQ 3 City] [nvarchar](100) NULL,
	[Acct HQ 3 State] [nvarchar](100) NULL,
	[Acct HQ 3 Key Account] [varchar](100) NULL,
	[Acct HQ 3 Owner Full Name] [nvarchar](200) NULL,
	[Acct HQ 3 Owner Email] [nvarchar](200) NULL,
	[Acct HQ 2 Id] [varchar](18) NULL,
	[Acct HQ 2 URL] [nvarchar](200) NULL,
	[Acct HQ 2 Name] [nvarchar](200) NULL,
	[Acct HQ 2 Record Type] [varchar](50) NULL,
	[Acct HQ 2 City] [nvarchar](100) NULL,
	[Acct HQ 2 State] [nvarchar](200) NULL,
	[Acct HQ 2 Key Account] [varchar](50) NULL,
	[Acct HQ 2 Owner Full Name] [nvarchar](200) NULL,
	[Acct HQ 2 Owner Email] [nvarchar](200) NULL,
	[Acct HQ 1 Id] [varchar](18) NULL,
	[Acct HQ 1 URL] [nvarchar](200) NULL,
	[Acct HQ 1 Name] [nvarchar](200) NULL,
	[Acct HQ 1 Record Type] [varchar](50) NULL,
	[Acct HQ 1 City] [nvarchar](100) NULL,
	[Acct HQ 1 State] [nvarchar](200) NULL,
	[Acct HQ 1 Key Account] [varchar](50) NULL,
	[Acct HQ 1 Owner Full Name] [nvarchar](200) NULL,
	[Acct HQ 1 Owner Email] [nvarchar](200) NULL,
	[Acct HQ 1 Key] [varchar](50) NULL,
	[Acct HQ 1 Name Number] [nvarchar](100) NULL,
	[Acct HQ 2 Key] [varchar](50) NULL,
	[Acct HQ 2 Name Number] [nvarchar](50) NULL,
	[Acct HQ 3 Key] [varchar](50) NULL,
	[Acct HQ 3 Name Number] [nvarchar](50) NULL,
	[Acct HQ 4 Key] [varchar](50) NULL,
	[Acct HQ 4 Name Number] [nvarchar](50) NULL,
	[Acct HQ 1 URL2] [nvarchar](200) NULL,
	[Acct HQ 2 URL2] [nvarchar](200) NULL,
	[Acct HQ 3 URL2] [nvarchar](200) NULL,
	[Acct HQ 4 URL2] [nvarchar](200) NULL, 
    CONSTRAINT [PK_Account_Hier_Dim] PRIMARY KEY ([Account Hierarchy Dim Id])
) ON [PRIMARY]
GO

