CREATE TABLE [GVW].[AccountTeamDim](
	[GVWAccountTeamSKey] int identity(1,1),
	[Id] VARCHAR(18) NOT NULL,
	[Name] [nvarchar](200) NULL,
	[URL] [nvarchar](200) NULL,
	[CreatedDate] [varchar](10) NULL,
	[ModifiedDate] [varchar](10) NULL,
	[AccountDimId] VARCHAR(18) NULL,
	[ManagerDimId] VARCHAR(18) NULL,
	[PersonDimId] VARCHAR(18) NULL,
	[AccountNameNumber] [nvarchar](50) NULL,
	[Custom1] [nvarchar](200) NULL,
	[Custom2] [nvarchar](200) NULL,
	[Custom3] [nvarchar](200) NULL,
	[Custom4] [nvarchar](200) NULL,
	[Custom5] [nvarchar](200) NULL,
	[Key] [varchar](50) NULL,
	[Manager1Id] VARCHAR(18) NULL,
	[Manager1Username] [nvarchar](100) NULL,
	[Manager1FullName] [nvarchar](200) NULL,
	[Manager1URL] [nvarchar](200) NULL,
	[Manager1LastName] [nvarchar](100) NULL,
	[Manager1FirstName] [nvarchar](100) NULL,
	[Manager1Email] [nvarchar](200) NULL,
	[Manager1Key] [varchar](50) NULL,
	[Manager2Id] VARCHAR(18) NULL,
	[Manager2Username] [nvarchar](100) NULL,
	[Manager2FullName] [nvarchar](200) NULL,
	[Manager2URL] [nvarchar](200) NULL,
	[Manager2LastName] [nvarchar](100) NULL,
	[Manager2FirstName] [nvarchar](100) NULL,
	[Manager2Email] [nvarchar](200) NULL,
	[Manager2Key] [varchar](50) NULL,
	[Manager3Id] VARCHAR(18) NULL,
	[Manager3Username] [nvarchar](100) NULL,
	[Manager3FullName] [nvarchar](200) NULL,
	[Manager3URL] [nvarchar](200) NULL,
	[Manager3LastName] [nvarchar](100) NULL,
	[Manager3FirstName] [nvarchar](100) NULL,
	[Manager3Email] [nvarchar](200) NULL,
	[Manager3Key] [varchar](50) NULL,
	[SalespersonId] VARCHAR(18) NULL,
	[SalespersonUsername] [nvarchar](100) NULL,
	[SalespersonFullName] [nvarchar](200) NULL,
	[SalespersonURL] [nvarchar](200) NULL,
	[SalespersonLastName] [nvarchar](100) NULL,
	[SalespersonFirstName] [nvarchar](100) NULL,
	[SalespersonEmail] [nvarchar](200) NULL,
	[SalespersonKey] [varchar](50) NULL,
	[SalesDivisionDimId] VARCHAR(18) NULL, 
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1)
    CONSTRAINT [PK_AccountTeamDim] PRIMARY KEY (GVWAccountTeamSKey) NOT NULL, 
    [GVWDeleted] BIT NULL
);