CREATE TABLE [GVW].[AcctUnivHierDim] (
	[GVWAcctUnivHierSKey] int identity(1,1),
    [ID]     VARCHAR(18)      NOT NULL,
    [CreatedDate]                 CHAR (10)      NULL,
    [ModifiedDate]                CHAR (10)      NULL,
    [AcctHQ4ID]                 VARCHAR(18)      NULL,
    [AcctHQ4URL]                VARCHAR (250)  NULL,
    [AcctHQ4Name]               VARCHAR (200)  NULL,
    [AcctHQ4RecordType]        VARCHAR (100)  NULL,
    [AcctHQ4City]               VARCHAR (100)  NULL,
    [AcctHQ4State]              VARCHAR (50)   NULL,
    [AcctHQ4KeyAccount]        VARCHAR (20)   NULL,
    [AcctHQ4OwnerFullName]    VARCHAR (200)  NULL,
    [AcctHQ4OwnerEmail]        VARCHAR (300)  NULL,
    [AcctHQ3ID]                 VARCHAR(18)      NULL,
    [AcctHQ3URL]                VARCHAR (250)  NULL,
    [AcctHQ3Name]               VARCHAR (200)  NULL,
    [AcctHQ3RecordType]        VARCHAR (100)  NULL,
    [AcctHQ3City]               VARCHAR (100)  NULL,
    [AcctHQ3State]              VARCHAR (50)   NULL,
    [AcctHQ3KeyAccount]        VARCHAR (20)   NULL,
    [AcctHQ3OwnerFullName]    VARCHAR (200)  NULL,
    [AcctHQ3OwnerEmail]        VARCHAR (300)  NULL,
    [AcctHQ2ID]                 VARCHAR(18)      NULL,
    [AcctHQ2URL]                VARCHAR (250)  NULL,
    [AcctHQ2Name]               VARCHAR (200)  NULL,
    [AcctHQ2RecordType]        VARCHAR (100)  NULL,
    [AcctHQ2City]               VARCHAR (100)  NULL,
    [AcctHQ2State]              VARCHAR (50)   NULL,
    [AcctHQ2KeyAccount]        VARCHAR (20)   NULL,
    [AcctHQ2OwnerFullName]    VARCHAR (200)  NULL,
    [AcctHQ2OwnerEmail]        VARCHAR (300)  NULL,
    [AcctHQ1ID]                 VARCHAR(18)      NULL,
    [AcctHQ1URL]                VARCHAR (250)  NULL,
    [AcctHQ1Name]               VARCHAR (200)  NULL,
    [AcctHQ1RecordType]        VARCHAR (100)  NULL,
    [AcctHQ1City]               VARCHAR (100)  NULL,
    [AcctHQ1State]              VARCHAR (50)   NULL,
    [AcctHQ1KeyAccount]        VARCHAR (20)   NULL,
    [AcctHQ1OwnerFullName]    VARCHAR (200)  NULL,
    [AcctHQ1OwnerEmail]        VARCHAR (300)  NULL,
    [AcctHQ1ExternalID]                VARCHAR (100)  NULL,
    [AcctHQ1NameNumber]        VARCHAR (200)  NULL,
    [AcctHQ2ExternalID]                VARCHAR (100)  NULL,
    [AcctHQ2NameNumber]        VARCHAR (200)  NULL,
    [AcctHQ3ExternalID]                VARCHAR (100)  NULL,
    [AcctHQ3NameNumber]        VARCHAR (200)  NULL,
    [AcctHQ4ExternalID]                VARCHAR (100)  NULL,
    [AcctHQ4NameNumber]        VARCHAR (200)  NULL,
    [AcctHQ1URL2]               VARCHAR (250)  NULL,
    [AcctHQ2URL2]               VARCHAR (250)  NULL,
    [AcctHQ3URL2]               VARCHAR (250)  NULL,
    [AcctHQ4URL2]               VARCHAR (250)  NULL, 
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
	  GVWDeleted BIT NULL DEFAULT '0',
    [GVWHash] VARCHAR(32) NOT NULL DEFAULT 0
  CONSTRAINT [PK_AcctUnivHierDim] PRIMARY KEY (GVWAcctUnivHiersKey)

);