CREATE TABLE [GVW].[Acct_HQ_Dim](
	[Acct HQ Dim Id] [varchar](18) NOT NULL,
	[Created Date] DATE NULL,
	[Modified Date] DATE NULL,
	[Acct HQ Id] [varchar](18) NULL,
	[Acct HQ URL] [nvarchar](200) NULL,
	[Acct HQ URL2] [nvarchar](200) NULL,
	[Acct HQ Name] [nvarchar](100) NULL,
	[Acct HQ Name Number] [nvarchar](200) NULL,
	[Acct HQ Record Type] [varchar](30) NULL,
	[Acct HQ Level] [nvarchar](20) NULL,
	[Acct HQ Key] [nvarchar](100) NULL,
	[Acct HQ City] [nvarchar](100) NULL,
	[Acct HQ State] [nvarchar](100) NULL,
	[Acct HQ Key Account] [nvarchar](10) NULL,
	[Acct HQ Custom 1] [nvarchar](200) NULL,
	[Acct HQ Custom 2] [nvarchar](200) NULL,
	[Acct HQ Custom 3] [nvarchar](200) NULL,
	[Acct HQ Custom 4] [nvarchar](200) NULL,
	[Acct HQ Custom 5] [nvarchar](200) NULL,
	[Acct HQ Owner Id] [varchar](18) NULL,
	[Acct HQ Owner URL] [nvarchar](200) NULL,
	[Acct HQ Owner Last Name] [nvarchar](100) NULL,
	[Acct HQ Owner First Name] [nvarchar](100) NULL,
	[Acct HQ Owner Full Name] [nvarchar](200) NULL,
	[Acct HQ Owner Email] [nvarchar](200) NULL, 
    CONSTRAINT [PK_Acct_HQ_Dim] PRIMARY KEY ([Acct HQ Dim Id])
) ON [PRIMARY]
GO

