CREATE TABLE [GVW].[AcctListingFact](
	[ID]             [varchar](100) NOT NULL,
	[Name]           [varchar](200) NULL,
	[URL]            [varchar](250) NULL,
	[Type]           [varchar](50)  NULL,
	[AcctListingType]                [varchar](50)  NULL,
	[AcctListingCompliance]          [varchar](50)  NULL,
	[AcctListingNew]                 [varchar](50)  NULL,
	[AcctListingCurrent]             [varchar](50)  NULL,
	[CreatedDate]                     [char](10)     NULL,
	[ModifiedDate]                    [char](10)     NULL,
	[TransactionTypeID]              VARCHAR(18)     NULL,
	[AcctHQID]                       VARCHAR(18)     NULL  DEFAULT '-1',
	[PersonDimID]                    VARCHAR(18)     NULL  DEFAULT '-1',
	[ProductDimID]                   VARCHAR(18)     NULL  DEFAULT '-1',
	[StartDate]                       [char](10)     NULL,
	[EndDate]                         [char](10)     NULL,
	[TransactionDate]                 [char](10)     NULL,
	[FiscalDate]                      [char](10)     NULL,
	[FiscalYear]                      [char](4)      NULL,
	[FiscalMonth]                     [char](2)      NULL,
	[AuthorizationID]                 VARCHAR(18)     NULL,
	[AuthorizationURL]                [varchar](250) NULL,
	[AuthorizationName]               [varchar](200) NULL,
	[AuthorizationStatus]             [varchar](50)  NULL,
	[AuthorizationMandated]           [varchar](50)  NULL,
	[AuthorizationSupported]          [varchar](50)  NULL,
	[AuthorizationPackageType]       [varchar](50)  NULL,
	[AuthorizationCustom1]           [varchar](255) NULL,
	[AuthorizationCustom2]           [varchar](255) NULL,
	[AuthorizationCustom3]           [varchar](255) NULL,
	[PlacementID]                     VARCHAR(18)     NULL,
	[PlacementURL]                    [varchar](250) NULL,
	[PlacementNumber]                 [varchar](50)  NULL,
	[PlacementDescription]            [varchar](255) NULL,
	[PlacementPrice]                  [varchar](50)  NULL,
	[PlacementDrinkName]             [varchar](200) NULL,
	[PlacementDisplayLocation]       [varchar](50)  NULL,
	[PlacementDisplayCases]          [varchar](50)  NULL,
	[PlacementScanAmount]            [varchar](50)  NULL,
	[PlacementPOSItemName]          [varchar](100) NULL,
	[PlacementPOSQuantity]           [varchar](50)  NULL,
	[PlacementPOSApproved]           [varchar](50)  NULL,
	[PlacementCustom1]               [varchar](255) NULL,
	[PlacementCustom2]               [varchar](255) NULL,
	[PlacementCustom3]               [varchar](255) NULL,
	[PlacementType]                   [varchar](50)  NULL,
	[AuthorizationCustomFact1]      [varchar](200) NULL,
	[AuthorizationCustomFact2]      [varchar](200) NULL,
	[PlacementCustomFact1]          [varchar](200) NULL,
	[PlacementCustomFact2]          [varchar](200) NULL,
	[AcctUnivDimID]                 VARCHAR(18)     NULL  DEFAULT '-1',
	[Granularity]    [varchar](50)  NULL,
	[FiscalDateDimID]               VARCHAR(18)     NULL,
	[AuthorizationKey]                [varchar](50)  NULL,
	[AuthorizationCustomText1]      [varchar](255) NULL,
	[AuthorizationCustomText2]      [varchar](255) NULL,
	[AuthorizationCustomText3]      [varchar](255) NULL,
	[AuthorizationCustomText4]      [varchar](255) NULL,
	[AuthorizationCustomText5]      [varchar](255) NULL,
	[AuthorizationCustomCheckbox1]  [varchar](50)  NULL,
	[AuthorizationCustomCheckbox2]  [varchar](50)  NULL,
	[AuthorizationCustomCurrency1]  [varchar](20)  NULL,
	[AuthorizationCustomCurrency2]  [varchar](20)  NULL,
	[PlacementKey]                    [varchar](50)  NULL,
	[PlacementCustomText1]          [varchar](255) NULL,
	[PlacementCustomText2]          [varchar](255) NULL,
	[PlacementCustomCheckbox1]      [varchar](50)  NULL,
	[PlacementCustomCheckbox2]      [varchar](50)  NULL,
	[CurrencyDimID]                  VARCHAR(18)     NULL  DEFAULT 'USD',
	[StartDateID]                    [VARCHAR](10)     NULL,
	[EndDateID]                      [VARCHAR](10)     NULL,
	[TxnDateID]                      [VARCHAR](10)     NULL,
	[FiscalDateID]                   [VARCHAR](10)     NULL,
	[SpendDimID]                     VARCHAR(18)     NULL  DEFAULT '-1', 
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
	GVWDeleted BIT NULL DEFAULT '0'
    CONSTRAINT [PK_AcctListingFact] PRIMARY KEY (ID)
);
