CREATE TABLE [GVW].[ActivityFact] (
    [ID]            VARCHAR (20)   NOT NULL,
    [Type]          VARCHAR (10)   NULL,
    [CreatedDate]                  CHAR(10)       NULL,
    [ModifiedDate]                 CHAR(10)       NULL,
    [ActivityGoalDimID]        VARCHAR (20)   NULL,
    [AccountDimID]              VARCHAR (30)   NULL,
    [ProductDimID]              VARCHAR (20)   NULL,
    [PersonDimID]               VARCHAR (20)   NULL,
    [TransactionType]            VARCHAR (20)   NULL,
    [TransactionDate]              DATE       NULL,
    [FiscalDate]                   DATE       NULL,
    [FiscalYear]                 VARCHAR (10)   NULL,
    [FiscalMonth]                VARCHAR (4)    NULL,
    [StartDate]                    DATE       NULL,
    [EndDate]                      DATE       NULL,
    [Name]               VARCHAR (100)   NULL,
    [URL]                NVARCHAR (200) NULL,
    [Compliance]         VARCHAR (50)   NULL,
    [Current]            VARCHAR (10)   NULL,
    [Description]        NVARCHAR(2000)  NULL,
    [Group]              VARCHAR (100)  NULL,
    [Subtype]            VARCHAR (300)  NULL,
    [Status]             VARCHAR (800)  NULL,
    [BTGListing]                 VARCHAR (700)  NULL,
    [DisplayLocation]            VARCHAR (700)  NULL,
    [EventBrandPromoted]        VARCHAR (700)  NULL,
    [EventERFReceived]          VARCHAR (100)  NULL,
    [EventFeaturedDrink]        VARCHAR (500)  NULL,
    [IncentiveResults]           VARCHAR (700)  NULL,
    [MegacallID]                 VARCHAR (300)  NULL,
    [MegacallName]               VARCHAR (100)  NULL,
    [MegacallURL]                NVARCHAR (200) NULL,
    [MegacallNotes]              VARCHAR (100)  NULL,
    [MegacallStatus]             VARCHAR (30)   NULL,
    [MegacallType]               VARCHAR (50)   NULL,
    [MenuDrinkName]             VARCHAR (100)  NULL,
    [ObjectiveResults]           VARCHAR (250)  NULL,
    [PresentationAction]         VARCHAR (50)   NULL,
    [PresentationProposedUsage] NVARCHAR (50)  NULL,
    [PresentationReaction]       NVARCHAR (50)  NULL,
    [PresentationTasted]         NVARCHAR (50)  NULL,
    [ProgramName]                VARCHAR (50)   NULL,
    [ProgramRecordType]         VARCHAR (20)   NULL,
    [POSApproved]                VARCHAR (20)   NULL,
    [POSItemName]               VARCHAR (100)   NULL,
    [POSQuantity]                  VARCHAR (50)   NULL,
    [ScanAdvertised]             VARCHAR (50)   NULL,
    [ScanDisplay]                VARCHAR (50)   NULL,
    [StaffTrainingPOS]          VARCHAR (50)   NULL,
    [StaffTrainingTasted]       VARCHAR (50)   NULL,
    [StaffTrainingTrained]        VARCHAR (50)   NULL,
    [TaskAccountCall]           VARCHAR (20)   NULL,
    [TaskCallType]              VARCHAR (30)   NULL,
    [TaskPriority]               VARCHAR (50)   NULL,
    [TaskSubject]                VARCHAR (250)  NULL,
    [PhysicalCases]       VARCHAR (50)   NULL,
    [Price]                NVARCHAR (50)  NULL,
    [Custom1]           NVARCHAR (300) NULL,
    [Custom2]           NVARCHAR (300) NULL,
    [Custom3]           NVARCHAR (300) NULL,
    [Custom4]           NVARCHAR (300) NULL,
    [Custom5]           NVARCHAR (300) NULL,
    [ActivityFact1]               VARCHAR (500)  NULL,
    [ActivityFact2]               VARCHAR (500)  NULL,
    [AuthorizationNew]           VARCHAR (500)  NULL,
    [AuthorizationMandated]      VARCHAR (60)   NULL,
    [AuthorizationSupported]     VARCHAR (50)   NULL,
    [PackageType]                VARCHAR (50)   NULL,
    [ScanAmount]                   VARCHAR (20)   NULL,
    [PlacementNumber]            VARCHAR (40)   NULL,
    [PlacementType]              VARCHAR (30)   NULL,
    [CreateDate]                   DATE       NULL,
    [FiscalDateDimID]            VARCHAR(10)       NULL,
    [CustomPicklist1]  NVARCHAR (200) NULL,
    [CustomPicklist2]  NVARCHAR (200) NULL,
    [CustomPicklist3]  VARCHAR (200)  NULL,
    [CustomPicklist4]  NVARCHAR (200) NULL,
    [CustomCheckbox1]  VARCHAR (20)   NULL,
    [CustomCheckbox2]  VARCHAR (20)   NULL,
    [CustomCurrency1]    NVARCHAR (30)  NULL,
    [CustomCurrency2]    NVARCHAR (30)  NULL,
    [MegacallExternalID]                VARCHAR (20)   NULL,
    [MegacallGeocode]            VARCHAR (30)   NULL,
    [MegacallLongitude]            NVARCHAR (40)  NULL,
    [MegacallLatitude]             NVARCHAR (40)  NULL,
    [MegacallDistance]             VARCHAR (30)   NULL,
    [MegacallContactedName]     VARCHAR (50)   NULL,
    [MegacallContactedEmail]    VARCHAR (100)  NULL,
    [MegacallContactedTitle]    VARCHAR (50)   NULL,
    [CurrencyDimID]             VARCHAR (18)   NULL,
    [ContactDimID]              VARCHAR (20)   NULL,
    [GeographyDimID]            VARCHAR (20)   NULL,
    [OrderCommitBottles]          VARCHAR (20)   NULL,
    [AccountTeamDimID]         VARCHAR (20)   NULL,
    [SalesDivisionDimID]       VARCHAR (30)   NULL,
    [TxnDateID]                   VARCHAR (20)   NULL,
    [FiscalDateID]                VARCHAR (20)   NULL,
    [StartDateID]                 VARCHAR (20)   NULL,
    [EndDateID]                   VARCHAR (20)   NULL,
    [CreateDateID]                VARCHAR (20)   NULL,
    [ImageID]                    VARCHAR (40)   NULL,
    [ImageName]                  VARCHAR (100)  NULL,
    [ImageURL]                   NVARCHAR (200) NULL,
    [ImageInd]                   VARCHAR (20)   NULL,
    [ImageDescription]           VARCHAR (100)  NULL,
    [ImageURLDashboard]         VARCHAR (200)  NULL,
    [ImageURLTable]             VARCHAR (100)   NULL,
    [SpendDimID]                VARCHAR (40)   NULL, 
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0'
	CONSTRAINT [PK_ActivityFact] PRIMARY KEY ([ID])
);

