CREATE TABLE [GVW].[EventCallFact] (
	[EventCallFactKey]        VARCHAR(75) NOT NULL,
    [CreatedDate]             CHAR(10)    NULL,
    [ModifiedDate]            CHAR(10)    NULL,
    [StartDate]               CHAR(10)    NULL,
    [EndDate]                 CHAR(10)    NULL,
    [TxnDate]                 CHAR(10)    NOT NULL,
    [FiscalDate]              CHAR(10)    NULL,
    [FiscalMonth]             CHAR(2)     NULL,
    [FiscalYear]              CHAR(4)     NULL,
    [FiscalDateDimID]         VARCHAR(10)    NULL,
    [EventFactID]           VARCHAR(18)    NULL DEFAULT '-1',
    [AccountCallFactID]     VARCHAR(18)    NULL DEFAULT '-1',
    [ContactDimID]          VARCHAR(18)    NULL DEFAULT '-1',
    [PersonDimID]           VARCHAR(18)    NOT NULL DEFAULT '-1',
    [AccountDimID]          VARCHAR(18)    NOT NULL DEFAULT '-1',
    [ProductDimID]          VARCHAR(18)    NULL DEFAULT '-1',
    [GeographyDimID]        VARCHAR(18)    NULL DEFAULT '-1',
    [EventCallSequence]       VARCHAR(10) NOT NULL,
    [EventCallActivityKey]    VARCHAR(50) NULL,
    [EventCallDate]         CHAR(10)    NULL,
    [EventCallTime]         CHAR(5)     NULL,
    [EventCallWeek]         CHAR(2)     NULL,
    [EventCallYear]         CHAR(4)     NULL,
    [StartDateID]           VARCHAR(8)     NULL,
    [EndDateID]             VARCHAR(8)     NULL,
    [TxnDateID]             VARCHAR(8)     NULL,
    [CreateDateID]          VARCHAR(5)     NULL,
    [FiscalDateID]          VARCHAR(5)     NULL, 
	GVWCreatedDate      Datetime    default getdate() NOT NULL,
    GVWLastModifiedDate Datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (1),
    GVWDeleted BIT NULL DEFAULT '0'
    CONSTRAINT [PK_EventCallFact] PRIMARY KEY ([AccountDimID], [PersonDimID], [EventCallSequence], [TxnDate])
);