CREATE TABLE [GVW].[FiscalDateDim] (
	[GVWFiscalDateSKey] int identity(1,1),
    [FiscalDateID]          VARCHAR (50) NULL,
    [FiscalDateLabel]       VARCHAR (50) NULL,
    [FDOrder]                VARCHAR (50) NULL,
    [FDNumber]               VARCHAR (50) NULL,
    [FDDoYNumber]           VARCHAR (50) NULL,
    [FDDoQNumber]           VARCHAR (50) NULL,
    [FDDoMNumber]           VARCHAR (50) NULL,
    [FDDoWNumber]           VARCHAR (50) NULL,
    [FDLabelShort]          VARCHAR (50) NULL,
    [FDLabelLong]           VARCHAR (50) NULL,
    [FWID]                   VARCHAR (50) NULL,
    [FWOrder]                VARCHAR (50) NULL,
    [FWNumber]               VARCHAR (50) NULL,
    [FWWoYNumber]           VARCHAR (50) NULL,
    [FWLabelShort]          VARCHAR (50) NULL,
    [FWLabelLong]           VARCHAR (50) NULL,
    [FWYLabelShort]         VARCHAR (50) NULL,
    [FWYLabelLong]          VARCHAR (50) NULL,
    [CMID]                   VARCHAR (50) NULL,
    [CMNumber]               VARCHAR (50) NULL,
    [FMID]                   VARCHAR (50) NULL,
    [FMOrder]                VARCHAR (50) NULL,
    [FMNumber]               VARCHAR (50) NULL,
    [FMMoYNumber]           VARCHAR (50) NULL,
    [FMMoQNumber]           VARCHAR (50) NULL,
    [FMLabelShort]          VARCHAR (50) NULL,
    [FMLabelMedium]         VARCHAR (50) NULL,
    [FMLabelMediumOrder]   VARCHAR (50) NULL,
    [FMLabelLong]           VARCHAR (50) NULL,
    [FMLabelLongOrder]     VARCHAR (50) NULL,
    [FMYLabelShort]         VARCHAR (50) NULL,
    [FMYLabelMedium]        VARCHAR (50) NULL,
    [FMYLabelMediumOrder]  VARCHAR (50) NULL,
    [FMYLabelLong]          VARCHAR (50) NULL,
    [FMYLabelLongOrder]    VARCHAR (50) NULL,
    [FQID]                   VARCHAR (50) NULL,
    [FQOrder]                VARCHAR (50) NULL,
    [FQNumber]               VARCHAR (50) NULL,
    [FQQoYNumber]           VARCHAR (50) NULL,
    [FQLabelShort]          VARCHAR (50) NULL,
    [FQLabelLong]           VARCHAR (50) NULL,
    [FQYLabelShort]         VARCHAR (50) NULL,
    [FQYLabelLong]          VARCHAR (50) NULL,
    [FYID]                   VARCHAR (50) NULL,
    [FYOrder]                VARCHAR (50) NULL,
    [FYNumber]               VARCHAR (50) NULL,
    [FYLabel]                VARCHAR (50) NULL,
    [FiscalDateText]        VARCHAR (50) NULL,
    [FiscalMonthText]       VARCHAR (50) NULL,
    [FDType]                 VARCHAR (50) NULL,
    [FDWorkdayInd]          VARCHAR (50) NULL,
    [FDWeekendInd]          VARCHAR (50) NULL,
    [FDHolIDayInd]          VARCHAR (50) NULL,
    [FDHolIDayLocalName]   VARCHAR (50) NULL,
    [FDHolIDayEnglishName] VARCHAR (50) NULL,
    [TxnDate]                VARCHAR (50) NULL,
    [FiscalDateOffset]      VARCHAR (50) NULL,
    [TxnDateID]             VARCHAR (50) NULL,
    [FiscalDateID2]         VARCHAR (50) NULL,
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0'
	CONSTRAINT [PK_FiscalDateDim] PRIMARY KEY ([GVWFiscalDateSKey])
);