CREATE TABLE [GVW].[Geography_Dim_All]
(
  [Geography Dim Id] [varchar](50) NOT NULL,
	[Geography Dim Name] [varchar](50) NULL,
	[Geography Dim Granularity] [varchar](50) NULL,
	[Geography Dim URL] [nvarchar](500) NULL,
	[Geography Hierarchy Dim Id] [varchar](50) NULL,
	[Created Date] [varchar](50) NULL,
	[Modified Date] [varchar](50) NULL,
	[Company Key] [varchar](50) NULL,
	[Company Name] [varchar](50) NULL,
	[Division Key] [varchar](50) NULL,
	[Division Name] [varchar](50) NULL,
	[Region Key] [varchar](50) NULL,
	[Region Name] [varchar](50) NULL,
	[Territory Id] [varchar](50) NULL,
	[Territory URL] [varchar](50) NULL,
	[Territory Key] [varchar](50) NULL,
	[Territory Name] [varchar](50) NULL,
	[Territory Custom 1] [varchar](50) NULL,
	[Territory Custom 2] [varchar](50) NULL,
	[Distributor Owner Id] [varchar](50) NULL,
	[Distributor Owner URL] [varchar](50) NULL,
	[Distributor Owner Last Name] [varchar](50) NULL,
	[Distributor Owner First Name] [varchar](50) NULL,
	[Distributor Owner Full Name] [varchar](50) NULL,
	[Distributor Owner Email] [varchar](50) NULL,
	[Distributor Id] [varchar](50) NULL,
	[Distributor Level] [varchar](50) NULL,
	[Distributor URL] [varchar](50) NULL,
	[Distributor URL2] [varchar](50) NULL,
	[Distributor Account Key] [varchar](50) NULL,
	[Distributor Name] [varchar](50) NULL,
	[Distributor Name Number] [varchar](50) NULL,
	[Distributor Record Type] [varchar](50) NULL,
	[Distributor Street] [varchar](50) NULL,
	[Distributor City] [varchar](50) NULL,
	[Distributor State] [varchar](50) NULL,
	[Distributor Zip] [varchar](50) NULL,
	[Distributor Country] [varchar](50) NULL,
	[Distributor County] [varchar](50) NULL,
	[Distributor Phone] [varchar](50) NULL,
	[Distributor Key Account] [varchar](50) NULL,
	[Distributor Groups] [varchar](50) NULL,
	[Distributor Custom 1] [varchar](50) NULL,
	[Distributor Custom 2] [varchar](50) NULL,
	[Distributor Custom 3] [varchar](50) NULL,
	[Distributor Custom 4] [varchar](50) NULL,
	[Distributor Custom 5] [varchar](50) NULL,
	[Division Id] [varchar](50) NULL,
	[Region Id] [varchar](50) NULL,
	[Currency Dim Id] [varchar](50) NULL,
	[Distributor Description] [varchar](50) NULL,
	[Distributor Custom Checkbox 1] [varchar](50) NULL,
	[Distributor Custom Checkbox 2] [varchar](50) NULL,
	[Distributor Custom 6] [varchar](50) NULL,
	[Distributor Custom 7] [varchar](50) NULL,
	[Distributor Custom 8] [varchar](50) NULL,
	[Distributor Custom 9] [varchar](50) NULL,
	[Distributor Custom 10] [varchar](50) NULL,
	[Distributor Custom Date 1] [varchar](50) NULL,
	[Distributor Custom Date 2] [varchar](50) NULL,
	[Distributor Source File] [varchar](50) NULL,
	[Region Custom 1] [varchar](50) NULL,
	[Region Custom 2] [varchar](50) NULL,
	[Division Custom 1] [varchar](50) NULL,
	[Division Custom 2] [varchar](50) NULL,
	[Company Custom 1] [varchar](50) NULL,
	[Company Custom 2] [varchar](50) NULL,
	[Distributor Shipping Street] [varchar](50) NULL,
	[Distributor Shipping City] [varchar](50) NULL,
	[Distributor Shipping State] [varchar](50) NULL,
	[Distributor Shipping Zip] [varchar](50) NULL,
	[Distributor Shipping Country] [varchar](50) NULL,
	[Distributor Rank] [varchar](50) NULL,
	[Territory Custom 3] [varchar](50) NULL,
	[Territory Custom 4] [varchar](50) NULL,
	[Territory Custom 5] [varchar](50) NULL,
	[Division Custom 3] [varchar](50) NULL,
	[Division Custom 4] [varchar](50) NULL,
	[Division Custom 5] [varchar](50) NULL,
	[Distributor Owner Dim Id] [varchar](50) NULL,
	[Distributor Zip5] [varchar](50) NULL,
	[Distributor Shipping Zip5] [varchar](50) NULL,
	[Company Id] [varchar](50) NULL,
	[Create_Date_Id] [varchar](50) NULL, 
    CONSTRAINT [PK_Geography_Dim_All] PRIMARY KEY ([Geography Dim Id])
)
