CREATE TABLE [GVW].[MediaFact](
	[ID] VARCHAR(18),
	[Name] [nvarchar](100) NULL,
	[URL] [nvarchar](200) NULL,
	[CreatedDate] CHAR(10) NULL,
	[ModifiedDate] CHAR(10) NULL,
	[PersonDimID] VARCHAR(18) NULL,
	[AccountDimID] VARCHAR(18) NULL,
	[ProductDimID] VARCHAR(18) NULL,
	[TxnTypeID] [nvarchar](3) NULL,
	[TxnDate] DATE NULL,
	[FiscalDate] DATE NULL,
	[FiscalDateDimID] VARCHAR(10) NULL,
	[DateTime] [datetime] NULL,
	[Date] CHAR(10) NULL,
	[Time] CHAR(8) NULL,
	[ExternalId] [nvarchar](19) NULL,
	[RecordType] [varchar](6) NULL,
	[Attachments] VARCHAR(18) NULL,
	[Comments] NVARCHAR(300) NULL,
	[Geocode] [varchar](100) NULL,
	[Latitude] DECIMAL(21, 18) NULL,
	[Longitude] DECIMAL(21, 18) NULL,
	[Distance] DECIMAL(9, 1) NULL,
	[Heading] DECIMAL(4, 1) NULL,
	[Location] [varchar](8) NULL,
	[Type] [varchar](50) NULL,
	[CompetitorName] [varchar](250) NULL,
	[CompetitorType] [varchar](250) NULL,
	[AttachmentID] [varchar](18) NULL,
	[DashboardImage] [varchar](120) NULL,
	[TableImage] [varchar](120) NULL,
	[ProductID] [varchar](18) NULL,
	[ProductName] [varchar](100) NULL,
	[ProductURL] [varchar](100) NULL,
	[ProductOwnership] [varchar](15) NULL,
	[ProductType] [varchar](50) NULL,
	[ProductSizeKey] [varchar](250) NULL,
	[TxnDateID] [int] NULL,
	[FiscalDateID] [int] NULL,
	[CompetitorDimID] VARCHAR(18),
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0'
	CONSTRAINT [PK_MediaFact] PRIMARY KEY ([ID])
);