CREATE TABLE [GVW].[PersonDim](
	[GVWPersonSKey] int identity(1,1),
	[ID] [varchar](50) NULL,
	[Name] [varchar](50) NULL,
	[Granularity] [varchar](50) NULL,
	[URL] [varchar](100) NULL,
	[CreatedDate] [varchar](50) NULL,
	[ModifiedDate] [varchar](50) NULL,
	[Key1] [varchar](75) NULL,
	[Key2] [varchar](75) NULL,
	[EmailKey] [varchar](75) NULL,
	[FullName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[FirstName] [varchar](50) NULL,
	[Salutation] [varchar](50) NULL,
	[RecordType] [varchar](50) NULL,
	[Street] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[State] [varchar](50) NULL,
	[Zip] [varchar](50) NULL,
	[Country] [varchar](50) NULL,
	[Phone] [varchar](50) NULL,
	[Fax] [varchar](50) NULL,
	[MobilePhone] [varchar](50) NULL,
	[HomePhone] [varchar](50) NULL,
	[WorkPhone] [varchar](50) NULL,
	[OtherPhone] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[WorkEmail] [varchar](50) NULL,
	[Title] [varchar](50) NULL,
	[Company] [varchar](50) NULL,
	[Department] [varchar](90) NULL,
	[Division] [varchar](80) NULL,
	[ActiveIndicator] [varchar](50) NULL,
	[DoNotEmail] [varchar](50) NULL,
	[DoNotCall] [varchar](50) NULL,
	[Level] [varchar](50) NULL,
	[SourceFile] [varchar](50) NULL,
	[RoleName] [varchar](100) NULL,
	[ProfileName] [varchar](50) NULL,
	[ManagerID] [varchar](50) NULL,
	[ManagerURL] [varchar](100) NULL,
	[ManagerLastName] [varchar](50) NULL,
	[ManagerFirstName] [varchar](50) NULL,
	[ManagerFullName] [varchar](50) NULL,
	[ManagerEmail] [varchar](50) NULL,
	[OwnerID] [varchar](50) NULL,
	[OwnerURL] [varchar](100) NULL,
	[OwnerLastName] [varchar](50) NULL,
	[OwnerFirstName] [varchar](50) NULL,
	[OwnerFullName] [varchar](50) NULL,
	[OwnerEmail] [varchar](50) NULL,
	[Custom1] [varchar](50) NULL,
	[Custom2] [varchar](50) NULL,
	[Custom3] [varchar](50) NULL,
	[Custom4] [varchar](50) NULL,
	[Custom5] [varchar](50) NULL,
	[Zip5] [varchar](50) NULL,
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0',
	GVWHash VARCHAR(32) NOT NULL DEFAULT 0, 
	CONSTRAINT [PK_PersonDim] PRIMARY KEY ([GVWPersonSKey])
);