CREATE TABLE [GVW].[Person_Dim](
	[Person Dim Id] [varchar](50) NULL,
	[Person Dim Name] [varchar](50) NULL,
	[Person Dim Granularity] [varchar](50) NULL,
	[Person Dim URL] [varchar](100) NULL,
	[Created Date] [varchar](50) NULL,
	[Modified Date] [varchar](50) NULL,
	[Person Id] [varchar](50) NULL,
	[Person URL] [varchar](100) NULL,
	[Person Key 1] [varchar](75) NULL,
	[Person Key 2] [varchar](75) NULL,
	[Person Email Key] [varchar](75) NULL,
	[Person Full Name] [varchar](50) NULL,
	[Person Last Name] [varchar](50) NULL,
	[Person First Name] [varchar](50) NULL,
	[Person Salutation] [varchar](50) NULL,
	[Person Record Type] [varchar](50) NULL,
	[Person Street] [varchar](50) NULL,
	[Person City] [varchar](50) NULL,
	[Person State] [varchar](50) NULL,
	[Person Zip] [varchar](50) NULL,
	[Person Country] [varchar](50) NULL,
	[Person Phone] [varchar](50) NULL,
	[Person Fax] [varchar](50) NULL,
	[Person Mobile Phone] [varchar](50) NULL,
	[Person Home Phone] [varchar](50) NULL,
	[Person Work Phone] [varchar](50) NULL,
	[Person Other Phone] [varchar](50) NULL,
	[Person Email] [varchar](50) NULL,
	[Person Work Email] [varchar](50) NULL,
	[Person Title] [varchar](50) NULL,
	[Person Company] [varchar](50) NULL,
	[Person Department] [varchar](50) NULL,
	[Person Division] [varchar](50) NULL,
	[Person Active Indicator] [varchar](50) NULL,
	[Person Do Not Email] [varchar](50) NULL,
	[Person Do Not Call] [varchar](50) NULL,
	[Person Level] [varchar](50) NULL,
	[Person Source File] [varchar](50) NULL,
	[Person Role Name] [varchar](100) NULL,
	[Person Profile Name] [varchar](50) NULL,
	[Person Manager Id] [varchar](50) NULL,
	[Person Manager URL] [varchar](100) NULL,
	[Person Manager Last Name] [varchar](50) NULL,
	[Person Manager First Name] [varchar](50) NULL,
	[Person Manager Full Name] [varchar](50) NULL,
	[Person Manager Email] [varchar](50) NULL,
	[Person Owner Id] [varchar](50) NULL,
	[Person Owner URL] [varchar](100) NULL,
	[Person Owner Last Name] [varchar](50) NULL,
	[Person Owner First Name] [varchar](50) NULL,
	[Person Owner Full Name] [varchar](50) NULL,
	[Person Owner Email] [varchar](50) NULL,
	[Person Custom 1] [varchar](50) NULL,
	[Person Custom 2] [varchar](50) NULL,
	[Person Custom 3] [varchar](50) NULL,
	[Person Custom 4] [varchar](50) NULL,
	[Person Custom 5] [varchar](50) NULL,
	[Person Zip5] [varchar](50) NULL
)