CREATE TABLE [GVW].[SalesGoalFact](
	[ID] VARCHAR(18) NOT NULL,
	[Name] [nvarchar](150) NULL,
	[URL] [nvarchar](200) NULL,
	[Granularity] [nvarchar](30) NULL,
	[AccountDimID] VARCHAR(18) NULL,
	[GeographyDimID] VARCHAR(18) NULL,
	[ProductDimID] VARCHAR(18) NULL,
	[SpendDimID] VARCHAR(18) NULL,
	[TxnTypeID] VARCHAR(18) NULL,
	[SurveyDimID] VARCHAR(18) NULL,
	[PersonDimID] VARCHAR(18) NULL,
	[AccountRecordTypeDimID] VARCHAR(18) NULL,
	[AccountSegmentDimID] VARCHAR(18) NULL,
	[SalesDriverDimID] [nvarchar](20) NULL,
	[CreatedDate] [char](10) NULL,
	[ModifiedDate] [char](10) NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[TxnDate] [date] NOT NULL,
	[FiscalDate] [date] NULL,
	[FiscalMonth] [nvarchar](5) NULL,
	[FiscalYear] [nvarchar](5) NULL,
	[FiscalDateDimID] [VARCHAR](10) NULL,
	[TxnAltDate] [date] NULL,
	[SalesGoalID] VARCHAR(18) NULL,
	[SalesGoalName] [nvarchar](100) NULL,
	[SalesGoalURL] [nvarchar](200) NULL,
	[SalesGoalType] [nvarchar](50) NULL,
	[SalesGoalRecordType] [nvarchar](30) NULL,
	[SalesGoalPeriodType] [varchar](30) NULL,
	[SalesGoalCategory] [nvarchar](30) NULL,
	[SalesGoalExternalID] [nvarchar](30) NULL,
	[SalesGoalPhysicalCases] [nvarchar](50) NULL,
	[SalesGoal9LCases] [nvarchar](50) NULL,
	[SalesGoalPrimaryVolume] [nvarchar](50) NULL,
	[SalesGoalSecondaryVolume] [nvarchar](50) NULL,
	[SalesGoalEstimateCases] [nvarchar](50) NULL,
	[SalesGoalMIDPeriodCases] [nvarchar](50) NULL,
	[SalesGoalFullCaseEquivalent] [nvarchar](50) NULL,
	[SalesGoalEstimate9LCases] [nvarchar](50) NULL,
	[SalesGoalMIDPeriod9LCases] [nvarchar](50) NULL,
	[SalesGoalTxnType] [nvarchar](30) NULL,
	[SalesGoalQuantityType] [varchar](30) NULL,
	[SalesGoalQuantity] [nvarchar](50) NULL,
	[SalesGoalWeight] [nvarchar](50) NULL,
	[SalesGoalCustom1] [varchar](30) NULL,
	[SalesGoalCustom2] [varchar](30) NULL,
	[SalesGoalCustom3] [varchar](30) NULL,
	[SalesGoalCustom4] [varchar](30) NULL,
	[SalesGoalCustom5] [varchar](100) NULL,
	[SalesGoalCustomFact1] VARCHAR(30) NULL,
	[SalesGoalCustomFact2] [varchar](30) NULL,
	[SalesGoalCustomFact3] [varchar](30) NULL,
	[AccountTypeDimID] VARCHAR(18) NULL,
	[AccountSetDimID]  VARCHAR(18) NULL,
	[ProductSetDimID]  VARCHAR(18) NULL,
	[SalesDivisionDimID]  VARCHAR(18) NULL,
	[SalesGoalReferenceReportID]  VARCHAR(18) NULL,
	[SalesGoalStatus] [varchar](30) NULL,
	[SalesGoalReportedResult] [nvarchar](50) NULL,
	[SalesGoalMasterID]  VARCHAR(18) NULL,
	[SalesGoalMasterInd] [varchar](30) NULL,
	[SalesGoalPlanID] VARCHAR(18) NULL,
	[SalesGoalPlanNumber] [nvarchar](50) NULL,
	[SalesGoalPlanName] [nvarchar](250) NULL,
	[SalesGoalPlanURL] [nvarchar](250) NULL,
	[SalesGoalPlanDescription] [nvarchar](350) NULL,
	[SalesGoalPlanParentID] VARCHAR(18) NULL,
	[SalesGoalPlanInd] [varchar](10) NULL,
	[SalesGoalProductName] [nvarchar](100) NULL,
	[StartDateID]  [int] NULL,
	[EndDateID]  [int] NULL,
	[TxnDateID]  [int] NULL,
	[FiscalDateID]  [int] NULL,
	[TxnAltDateID]  [int] NULL,
	[SalesGoalCompetitorName] [nvarchar](100) NULL,
	[SalesGoalCurrencyValue] [nvarchar](50) NULL,
	[SalesGoalMinimumValue] [nvarchar](50) NULL,
	[SalesGoalReferenceInd] [varchar](10) NULL,
	[SalesGoalReferenceValue] [nvarchar](50) NULL,
	[SalesGoalUserType] [nvarchar](30) NULL,
	[CompetitorDimID] VARCHAR(18) NULL,
	[SalesGoalMinQty] [nvarchar](50) NULL,
	[SalesGoalMinQtyUOM] [varchar](30) NULL,
	[AltStartDate] [date] NULL,
	[AltEndDate] [date] NULL,
	[AltStartDateID]  [int] NULL,
	[AltEndDateID]  [int] NULL,
	[SalesGoalAdjustment] [varchar](50) NULL,
	[SalesGoalAdjustmentComment] [varchar](50) NULL,
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0',
	GVWHash VARCHAR(32) NOT NULL DEFAULT 0,
	CONSTRAINT [PK_SalesGoalFact] PRIMARY KEY ([ID])
);
