CREATE TABLE [GVW].[SalesOrderFact](
	[ID]                               VARCHAR(18)      NOT NULL,
	[Name]                             [varchar](100)  NULL,
	[URL]                              [varchar](250)  NULL,
	[Type]                             [varchar](50)   NULL,
	[CreatedDate]                                      [char](10)      NULL,
	[ModifiedDate]                                     [char](10)      NULL,
	[AccountDimID]                                    VARCHAR(18)      NULL DEFAULT '-1',
	[ProductDimID]                                    VARCHAR(18)      NULL DEFAULT '-1',
	[GeographyDimID]                                  VARCHAR(18)      NULL DEFAULT '-1',
	[PersonDimID]                                     VARCHAR(18)      NULL DEFAULT '-1',
	[TransactionTypeID]                               VARCHAR(18)      NULL DEFAULT '-1',
	[TransactionDate]                                  [char](10)      NULL,
	[FiscalDate]                                       [char](10)      NULL,
	[FiscalYear]                                       [char](4)       NULL,
	[FiscalMonth]                                      [char](2)       NULL,
	[TransactionAltDate]                              [char](10)      NULL,
	[StartDate]                                        [char](10)      NULL,
	[EndDate]                                          [char](10)      NULL,
	[SalesOrderID]                                    VARCHAR(18)      NULL,
	[SalesOrderName]                                  [varchar](100)  NULL,
	[SalesOrderURL]                                   [varchar](250)  NULL,
	[SalesOrderExternalID]                                   [varchar](100)  NULL,
	[SalesOrderNumber]                                [varchar](50)   NULL,
	[SalesOrderTrackingNumber]                       [varchar](50)   NULL,
	[SalesOrderWillCall]                             [varchar](50)   NULL,
	[SalesOrderStatus]                                [varchar](100)  NULL,
	[SalesOrderType]                                  [varchar](100)  NULL,
	[SalesOrderItemID]                               [VARCHAR](18)      NULL,
	[SalesOrderItemName]                             [varchar](100)  NULL,
	[SalesOrderItemURL]                              [varchar](250)  NULL,
	[SalesOrderItemExternalID]                              [varchar](100)  NULL,
	[SalesOrderItemLine]                             [varchar](50)   NULL,
	[SalesOrderItemPODExternalID]                          [varchar](100)  NULL,
	[SalesOrderItemPriceLevel]                      [varchar](100)  NULL,
	[SalesOrderItemPrice]                            [varchar](50)   NULL,
	[SalesOrderItemExtendedPrice]                   [varchar](50)   NULL,
	[SalesOrderItemUnit]                             [varchar](50)   NULL,
	[SalesOrderItemQuantity]                         [varchar](50)   NULL,
	[SalesOrderItemPhysicalCases]                   [varchar](50)   NULL,
	[SalesOrderItem9LCases]                         [varchar](50)   NULL,
	[SalesOrderItemFullCaseEquivalent]             [varchar](50)   NULL,
	[SalesOrderItemPrimaryVolume]                   [varchar](50)   NULL,
	[SalesOrderItemSecondaryVolume]                 [varchar](50)   NULL,
	[FiscalDateDimID]                                [VARCHAR](10)      NULL,
	[SalesOrderPODItemExternalID]                          [varchar](100)  NULL,
	[SalesOrderPODLabelExternalID]                         [varchar](100)  NULL,
	[SalesOrderPODBrandExternalID]                         [varchar](100)  NULL,
	[CurrencyDimID]                                   VARCHAR(18)      NULL DEFAULT 'USD',
	[ContactDimID]                                    VARCHAR(18)      NULL DEFAULT '-1',
	[SalesOrderItemQtyperCarton]                   [varchar](50)   NULL,		
    [SalesOrderItemSupplierProvIDedPromoCode]     [varchar](50)   NULL,
	[SalesOrderItemDistributorRepack]               [varchar](50)   NULL,
	[SalesOrderItemInvoiceItem]                     [varchar](50)   NULL,
	[SalesOrderItemInvoiceDiscount]                 [varchar](50)   NULL,
	[SalesOrderItemInvoiceTax]                      [varchar](50)   NULL,
	[SalesOrderItemInvoiceExtPrice]                [varchar](50)   NULL,
	[SalesOrderItemSupplierDiscountParticipation]  [varchar](50)   NULL,
	[SalesOrderItemSupplierDepletionAllowance]     [varchar](50)   NULL,
	[TxnDateID]                                       [varchar](10)   NULL,
	[FiscalDateID]                                    [varchar](10)   NULL,
	[TxnAltDateID]                                   [varchar](10)   NULL,
	[StartDateID]                                     [varchar](10)   NULL,
	[EndDateID]                                       [varchar](10)   NULL,
    GVWCreatedDate      Datetime    default getdate() NOT NULL,
    GVWLastModifiedDate Datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0'
	CONSTRAINT [PK_SalesOrderFact] PRIMARY KEY ([ID]), 
    [GVWHash] VARCHAR(32) NOT NULL DEFAULT 0
);
