CREATE TABLE [GVW].[ShipmentFact](
	[ID] VARCHAR(20) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[URL] [nvarchar](200) NULL,
	[Type] [varchar](6) NULL,
	[CreatedDate] [nvarchar](10) NULL,
	[ModifiedDate] [nvarchar](10) NULL,
	[ProductDimID] VARCHAR(18) NOT NULL,
	[GeographyDimID] VARCHAR(18) NULL,
	[TransactionTypeID] [varchar](5) NULL,
	[TxnDate] [nvarchar](10) NOT NULL,
	[FiscalDate] [nvarchar](10) NULL,
	[FiscalYear] [varchar](6) NULL,
	[FiscalMonth] [varchar](4) NULL,
	[TxnAltDate] [nvarchar](10) NULL,
	[ExternalID] [varchar](255) NULL,
	[OrderType] [nvarchar](100) NULL,
	[Status] [nvarchar](100) NULL,
	[PhysicalCases] [decimal](11, 3) NULL,
	[9LCases] [decimal](14, 6) NULL,
	[FullCaseEquivalent] [decimal](14, 6) NULL,
	[PrimaryVolume] [decimal](14, 6) NULL,
	[SecondaryVolume] [decimal](14, 6) NULL,
	[ExtendedPrice1] [money] NULL,
	[ExtendedPrice2] [money] NULL,
	[Custom1] [nvarchar](200) NULL,
	[Custom2] [nvarchar](200) NULL,
	[Fact1] [decimal](15, 8) NULL,
	[Fact2] [decimal](15, 8) NULL,
	[AccountDimID] VARCHAR(18) NOT NULL,
	[RptCurrentInd] [varchar](3) NULL,
	[FiscalDateDimID] [nvarchar](10) NULL,
	[CurrencyDimID] VARCHAR(18) NULL,
	[SourceSystem] [varchar](60) NULL,
	[OrderNumber] [varchar](30) NOT NULL,
	[InvoiceNumber] [varchar](50) NULL,
	[StartDate] [nvarchar](10) NULL,
	[EndDate] [nvarchar](10) NULL,
	[TxnDateID] [varchar](50) NULL,
	[FiscalDateID] [varchar](50) NULL,
	[TxnAltDateID] [varchar](50) NULL,
	[StartDateID] [varchar](50) NULL,
	[EndDateID] [varchar](50) NULL,
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0', 
    [GVWHash] VARCHAR(32) NOT NULL DEFAULT 0
	CONSTRAINT [PK_ShipmentFact] PRIMARY KEY ([ID], [TxnDate], [OrderNumber], [AccountDimID], [ProductDimID])
);