CREATE TABLE [GVW].[SpendDim](
[GVWSpendSKey] int identity(1,1),
[ID]					VARCHAR(18) NOT NULL,				
[URL]                 nvarchar(100) NULL,            
[Name]                nvarchar(100) NULL,            
[Granularity]         varchar(20) NULL,              
[CreatedDate]                  char (10) NULL,                
[ModifiedDate]                 char (10) NULL,                
[CreatedByID]                 VARCHAR(18) NULL,                
[PersonDimID]                 VARCHAR(18) NULL,                
[GeographyDimID]              VARCHAR(18) NULL,                
[ProductDimID]                varchar (37) NULL,                
[AccountDimID]                VARCHAR(18) NULL,                
[AcctUnivDimID]              VARCHAR(18) NULL,                
[CurrencyDimID]               VARCHAR(18) NULL,                
[StartDate]                    char (10) NULL,                
[EndDate]                      char (10) NULL,                
[BudgetID]                     VARCHAR(18) NULL,                
[BudgetURL]                    nvarchar(100) NULL,            
[BudgetName]                   nvarchar(100) NULL,            
[BudgetTargetAmount]          nvarchar(20) NULL,             
[BudgetDescription]            nvarchar(100) NULL,            
[BudgetExternalID]                    nvarchar(100) NULL,            
[BudgetTimePd]                nvarchar(10) NULL,             
[BudgetRecType]                nvarchar(30) NULL,             
[BudgetCostCenter]            nvarchar(20) NULL,             
[BudgetSpendType]             nvarchar(20) NULL,             
[BudgetCustom1]               nvarchar(20) NULL,             
[BudgetCustom2]               nvarchar(20) NULL,             
[BudgetCustom3]               nvarchar(20) NULL,             
[BudgetCustom4]               nvarchar(20) NULL,             
[BudgetCustom5]               nvarchar(20) NULL,             
[BudgetCustomPicklist1]      nvarchar(20) NULL,             
[BudgetCustomPicklist2]      nvarchar(20) NULL,             
[BudgetCustomNumber1]        nvarchar(20) NULL,             
[BudgetCustomNumber2]        nvarchar(20) NULL,             
[BudgetCustomCurrency1]      nvarchar(20) NULL,             
[BudgetCustomCurrency2]      nvarchar(20) NULL,             
[BudgetOwnerID]               VARCHAR(18) NULL,                
[BudgetOwnerURL]              nvarchar(100) NULL,            
[BudgetOwnerUsername]         nvarchar(100) NULL,            
[BudgetOwnerFullName]        nvarchar(50) NULL,             
[BudgetOwnerLastName]        nvarchar(50) NULL,             
[BudgetOwnerFirstName]       nvarchar(100) NULL,            
[BudgetOwnerEmail]            nvarchar(100) NULL,            
[BudgetOwnerExternalID]              nvarchar(100) NULL,            
[BudgetPlanID]                VARCHAR(18) NULL,                
[BudgetPlanURL]               nvarchar(100) NULL,            
[BudgetPlanName]              nvarchar(100) NULL,            
[BudgetPlanExternalID]               nvarchar(100) NULL,            
[BudgetPlanTargetAmount]     nvarchar(20) NULL,             
[BudgetPlanBrandExternalID]         nvarchar(20) NULL,             
[BudgetPlanBrandName]        nvarchar(100) NULL,            
[BudgetPlanCostCenter]       nvarchar(100) NULL,             
[BudgetPlanSpendType]        nvarchar(100) NULL,             
[BudgetPlanCustomText1]     nvarchar(100) NULL,             
[BudgetPlanCustomText2]     nvarchar(100) NULL,             
[BudgetPlanCustomText3]     nvarchar(100) NULL,             
[BudgetPlanCustomText4]     nvarchar(100) NULL,             
[BudgetPlanCustomText5]     nvarchar(100) NULL,             
[BudgetPlanCustomPicklist1] nvarchar(100) NULL,             
[BudgetPlanCustomPicklist2] nvarchar(100) NULL,             
[BudgetPlanCustomNumber1]   nvarchar(100) NULL,             
[BudgetPlanCustomNumber2]   nvarchar(100) NULL,             
[BudgetPlanCustomCurrency1] nvarchar(100) NULL,             
[BudgetPlanCustomCurrency2] nvarchar(100) NULL,             
[ProgramID]                    VARCHAR(18) NULL,                
[ProgramURL]                   nvarchar(100) NULL,            
[ProgramName]                  nvarchar(100) NULL,            
[ProgramCode]                  nvarchar(150) NULL,             
[ProgramDescription]           nvarchar(350) NULL,             
[ProgramStatus]                nvarchar(100) NULL,             
[ProgramType]                  nvarchar(100) NULL,             
[ProgramCost]                  nvarchar(100) NULL,             
[ProgramRecType]               nvarchar(100) NULL,             
[ProgramCostCenter]           nvarchar(100) NULL,             
[ProgramSpendType]            nvarchar(100) NULL,             
[ProgramCustomText1]         nvarchar(100) NULL,             
[ProgramCustomText2]         nvarchar(100) NULL,             
[ProgramCustomText3]         nvarchar(100) NULL,             
[ProgramCustomText4]         nvarchar(100) NULL,             
[ProgramCustomText5]         nvarchar(100) NULL,             
[ProgramCustomPicklist1]     nvarchar(100) NULL,             
[ProgramCustomPicklist2]     nvarchar(100) NULL,             
[ProgramCustomNumber1]       nvarchar(100) NULL,             
[ProgramCustomNumber2]       nvarchar(100) NULL,             
[ProgramCustomCurrency1]     nvarchar(20) NULL,             
[ProgramCustomCurrency2]     nvarchar(20) NULL,             
[SpendProductLevel]           nvarchar(30) NULL,             
[SpendBrandName]              nvarchar(50) NULL,             
[SpendLabelName]              nvarchar(50) NULL,             
[SpendItemName]               nvarchar(50) NULL,             
[ContactDimID]                VARCHAR(18) NULL,                
[CustomDate1]       nvarchar(50) NULL,             
[CustomDate2]       nvarchar(50) NULL,             
[StartDateID]                 nvarchar(5) NULL,              
[EndDateID]                   nvarchar(5) NULL,              
[ProgramEstVolume]            nvarchar(50) NULL,             
[ProgramCosttoDist]          nvarchar(50) NULL,             
[ProgramCosttoBrand]         nvarchar(50) NULL,             
GVWCreatedDate      Datetime    default getdate() NOT NULL,
GVWLastModifiedDate Datetime    default getdate() NOT NULL,
GVWSourceID  INT default (-1),
GVWDeleted BIT NULL DEFAULT '0'
CONSTRAINT [PK_SpendDim] PRIMARY KEY ([GVWSpendSKey])
);