CREATE TABLE [GVW].[SurveyFact](
	[ID]                    VARCHAR(18)      NOT NULL,
	[Name]                  [varchar](200)  NULL,
	[URL]                   [varchar](250)  NULL,
	[Type]                  [varchar](200)  NULL,
	[Granularity]           [varchar](100)  NULL,
	[CreatedDate]                      [varchar](50)   NULL,
	[ModifiedDate]                     [varchar](50)   NULL,
	[TxnTypeID]                       VARCHAR(18)      NULL,
	[SurveyDimID]                     VARCHAR(18)      NULL DEFAULT '-1',
	[AccountDimID]                    VARCHAR(18)      NULL DEFAULT '-1',
	[AccountUniverseDimID]           VARCHAR(18)      NULL DEFAULT '-1',
	[PersonDimID]                     VARCHAR(18)      NULL DEFAULT '-1',
	[ProductDimID]                    [varchar](50)   NULL DEFAULT '-1',
	[StartDate]                        [varchar](50)   NULL,
	[EndDate]                          [varchar](50)   NULL,
	[TxnDate]                          [varchar](50)   NULL,
	[FiscalDate]                       [varchar](50)   NULL,
	[FiscalYear]                       [varchar](50)   NULL,
	[FiscalMonth]                      [varchar](50)   NULL,
	[SurveyID]                         VARCHAR(18)      NULL,
	[SurveyURL]                        [varchar](250)  NULL,
	[SurveyName]                       [varchar](100)  NULL,
	[SurveyRecordType]                [varchar](100)  NULL,
	[SurveyAnswerID]                  VARCHAR(18)      NULL,
	[SurveyAnswerURL]                 [varchar](250)  NULL,
	[SurveyAnswerName]                [varchar](100)  NULL,
	[SurveyAnswerCheckbox]            [varchar](100)  NULL,
	[SurveyAnswerCurrency]            [varchar](50)   NULL,
	[SurveyAnswerNumber]              [varchar](100)  NULL,
	[SurveyAnswerPercent]             [varchar](50)   NULL,
	[SurveyAnswerText]                [varchar](300)  NULL,
	[SurveyAnswerOrder]               [varchar](100)  NULL,
	[SurveyAnswerPoints]              [varchar](50)   NULL,
	[SurveyAnswerMostRecent]         [varchar](50)   NULL,
	[SurveyStatus]                     [varchar](200)  NULL,
	[SurveyExternalID]                        [varchar](200)  NULL,
	[SurveyAnswerMatchTargetPoints] [varchar](50)   NULL,
	[FiscalDateDimID]                [varchar](50)   NULL,
	[SurveyAnswerExternalID]                 [varchar](200)  NULL,
	[SurveyAnswerCustomCurrency1]   [varchar](50)   NULL,
	[SurveyAnswerCustomFact1]       [varchar](50)   NULL,
	[SurveyAnswerCustomFact2]       [varchar](50)   NULL,
	[SurveyAnswerCustomFact3]       [varchar](50)   NULL,
	[SurveyAnswerCustomFact4]       [varchar](50)   NULL,
	[SurveyAnswerCustomFact5]       [varchar](50)   NULL,
	[SurveyAnswerCustomText1]       [varchar](255)  NULL,
	[SurveyAnswerCustomText2]       [varchar](255)  NULL,
	[SurveyAnswerCustomText3]       [varchar](255)  NULL,
	[SurveyAnswerCustomText4]       [varchar](255)  NULL,
	[SurveyAnswerCustomText5]       [varchar](255)  NULL,
	[CurrencyDimID]                   VARCHAR(18)      NULL DEFAULT 'USD',
	[SurveyDistance]                   [varchar](50)   NULL,
	[SurveyLatitude]                   [varchar](50)   NULL,
	[SurveyLongitude]                  [varchar](50)   NULL,
	[SurveyGeocode]                    [varchar](100)  NULL,
	[SurveyRptCurrentInd]            [varchar](50)   NULL,
	[SurveyRptFromDate]              [varchar](50)   NULL,
	[SurveyOrderFact]                 [varchar](100)  NULL,
	[SurveyAuditedInd]                [varchar](50)   NULL,
	[SurveyAuditedID]                 VARCHAR(18)      NULL,
	[SurveyAuditNotes]                [varchar](300)  NULL,
	[SurveyAuditStatus]               [varchar](100)  NULL,
	[SurveyAuditAnswerID]            VARCHAR(18)      NULL,
	[ImageID]                          VARCHAR(18)      NULL,
	[ImageName]                        [varchar](200)  NULL,
	[ImageURL]                         [varchar](250)  NULL,
	[ImageInd]                         [varchar](50)   NULL,
	[ImageDescription]                 [varchar](300)  NULL,
	[ImageURLDashboard]               [varchar](300)  NULL,
	[ImageURLTable]                   [varchar](300)  NULL,
	[SurveySource]                     [varchar](200)  NULL,
	[SurveyMobileInd]                 [varchar](50)   NULL,
	[SurveyPreviousID]                VARCHAR(18)      NULL,
	[SurveyPreviousInd]               [varchar](50)   NULL,
	[AccountTeamDimID]               VARCHAR(18)      NULL,
	[SalesDivisionDimID]             VARCHAR(18)      NULL,
	[StartDateID]                     [varchar](50)   NULL,
	[EndDateID]                       [varchar](50)   NULL,
	[TxnDateID]                       [varchar](50)   NULL,
	[FiscalDateID]                    [varchar](50)   NULL,
	[RptFromDateID]                  [varchar](50)   NULL,
	[SurveySurveyCustomCurrency1]   [varchar](50)   NULL,
	[SurveySurveyCustomCurrency2]   [varchar](50)   NULL,
	[SurveySurveyCustomDate1]       [varchar](50)   NULL,
	[SurveySurveyCustomDate2]       [varchar](50)   NULL,
	[SurveySurveyCustomNumber1]     [varchar](100)  NULL,
	[SurveySurveyCustomNumber2]     [varchar](100)  NULL,
	[SurveySurveyCustomPicklist1]   [varchar](100)  NULL,
	[SurveySurveyCustomPicklist2]   [varchar](100)  NULL,
	[SurveySurveyCustomText1]       [varchar](255)  NULL,
	[SurveySurveyCustomText2]       [varchar](255)  NULL,
	[SurveySurveyCustomText3]       [varchar](255)  NULL,
	[SurveySurveyCustomText4]       [varchar](255)  NULL,
	[SurveySurveyCustomText5]       [varchar](255)  NULL,
	[CompetitorDimID]                 VARCHAR(18)      NULL DEFAULT '-1',
	[SpendDimID]                      VARCHAR(18)      NULL DEFAULT '-1',
	[SurveyAnswerAttachments]         [varchar](100)  NULL,
	[SurveyAnswerValue]               [varchar](100)  NULL,
	[SurveyAnswerConditionalInd]     [varchar](50)   NULL,
	[SurveyAnswerMultipleInd]        [varchar](50)   NULL,
	[SurveyAnswerReferenceTo]        [varchar](200)  NULL,
	[SurveyAnsweredInd]               [varchar](50)   NULL,
	[AltStartDate]                    [varchar](50)   NULL,
	[AltEndDate]                      [varchar](50)   NULL,
	[AltStartDateID]                 [varchar](50)   NULL,
	[AltEndDateID]                   [varchar](50)   NULL,
    GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0'
	CONSTRAINT [PK_SurveyFact] PRIMARY KEY ([ID])
);