CREATE TABLE GVW.VisitSequenceFact(
    ID           VARCHAR(18)      NOT NULL,
	Name         varchar(250)  NULL,
	CreatedDate                   char(10)      NULL,
	ModifiedDate                  char(10)      NULL,
	TxnDate                       char(10)      NULL,
	TxnAltDate                   char(10)      NULL,
	FiscalDate                    char(10)      NULL,
	FiscalMonth                   char(2)       NULL,
	FiscalYear                    char(4)       NULL,
	FiscalDateDimID             Char(10)      NULL,
	Date    			          char(10)      NULL,
	LocalDate   			      char   (10)   NULL,
	LocalDateID                 varchar(10)   NULL,
	StatusComplete			  varchar(10)   NULL,
	CreateDateID                 varchar(10)   NULL,
	TxnDateID                    varchar(10)   NULL,
	TxnAltDateID                varchar(10)   NULL,
	StartDate 				DATE		 NULL, 
    EndDate				    DATE 		NULL, 
	FiscalDateID                 varchar(10)   NULL,
	VisitSequenceDimID			VARCHAR(18) NULL,
	AccountCallID					VARCHAR(18) NULL,
	GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0',
	GVWHash VARCHAR(32) NOT NULL DEFAULT 0, 
	CONSTRAINT PK_VisitSequenceFact PRIMARY KEY (ID)
);
