CREATE TABLE [GVW].[VisitSequenceDim](
	[GVWVisitSequenceSKey] int identity(1,1),
	[ID] [varchar](20) NOT NULL,
	[Name] [varchar](50) NULL, 
	URL NVARCHAR (100)  NULL,
	Granularity NVARCHAR (30)  NULL,
	VisitSequenceID [varchar](20) NULL,
	VisitSequenceName [varchar](50) NULL,
	VisitSequenceSegment [varchar](100) NULL,
	VisitSequenceActive [varchar](10) NULL,
	GeographyExternalID [varchar](50) NULL,
	VisitSequenceStepOrderNumber [decimal](4, 1) NULL,
	ProfileName [nvarchar](100) NULL,
	RecordType [char](30) NULL,
	VisitSequenceStepRequired [varchar](10) NULL,
	VisitSequenceStepID [varchar](20) NULL,
	VisitSequenceStepName [varchar](50) NULL,
	VisitSequenceStepType [varchar](50) NULL,
	VisitSequenceStepSubtype [varchar](30) NULL,
	VisitSequenceURL NVARCHAR (100)  NULL,
	VisitSequenceStepURL NVARCHAR (100)  NULL,
	GVWCreatedDate       datetime    default getdate() NOT NULL,
    GVWLastModifiedDate  datetime    default getdate() NOT NULL,
    GVWSourceID  INT default (-1),
    GVWDeleted BIT NULL DEFAULT '0',
    [GVWHash] VARCHAR(32) NOT NULL DEFAULT 0,
	CONSTRAINT [PK_VisitSequenceDim] PRIMARY KEY ([GVWVisitSequenceSKey])
);