CREATE TABLE ERPIn.[Product]
(
  Item_Number           varchar(255) not null, 
  Item_Name             varchar(80) not null,
  Label_Key             varchar(80) not null,
  Label_Name            varchar(80) not null,
  Varietal_Name         varchar(50),
  Product_Type          varchar(20),
  Product_Line          varchar(50),
  Brand_Key             varchar(255) not null,
  Brand_Name            varchar(80) not null,
  Brand_Ownership       varchar(50),
  Designation           varchar(50),
  Supplier_Key          varchar(255) not null,
  Supplier_Name         varchar(80) not null,
  Size_Key              varchar(255) not null,
  Size_Name             varchar(80) not null,
  Size_Volume           FLOAT not null,
  Units_per_Case        DECIMAL(5, 1) not null,
  Vintage               varchar(100),
  Active_Flag           varchar(10),
  ABV                   decimal(10,6),
  Item_Key              varchar(255) not null,
  gvp__Custom_1__c      varchar(80),
  Package_Type          varchar(20) NOT NULL DEFAULT '',
  Container             varchar(20),
  Primary_Conversion    decimal(15,3),
  Secondary_Conversion  decimal(15,3),
  Label_Custom_1        varchar(80),
  Label_Custom_2        varchar(80)

    CONSTRAINT [PK_Product] PRIMARY KEY ([Item_Number]), 
    [Item_Description] VARCHAR(100) NULL, 
    [Unit_of_Measurement] VARCHAR(10) NULL, 
    [Custom_Fact_1] DECIMAL(12, 6) NULL, 
    [Item_Custom_Picklist_1] VARCHAR(100) NULL, 
    [Custom_2] VARCHAR(255) NULL, 
    [Custom_3] VARCHAR(255) NULL, 
    [Custom_4] VARCHAR(255) NULL, 
    [Custom_5] VARCHAR(255) NULL, 
    [Active_PMT] VARCHAR(10) NULL, 
    [Active_LSB] VARCHAR(10) NULL, 
    [Active_LMWA] VARCHAR(10) NULL, 
    [Country] VARCHAR(50) NULL, 
    [Region] VARCHAR(50) NULL, 
    [Region_Sub] VARCHAR(50) NULL, 
    [Label_Custom_Picklist_1] VARCHAR(100) NULL, 
    [Organic] VARCHAR(10) NULL, 
    [Gluten_Free] VARCHAR(10) NULL, 
    [Preservative_Free] VARCHAR(10) NULL, 
    [Vegan_Friendly] VARCHAR(10) NULL, 
    [Lower_Carb] VARCHAR(10) NULL, 
    [Product_Style] VARCHAR(255) NULL, 
    [Product_Category] VARCHAR(255) NULL, 
    [Product_Group] VARCHAR(100) NULL, 
    [LM_Item_Number] VARCHAR(100) NULL, 
    [LSB_Item_Number] VARCHAR(100) NULL, 
    [PMT_Item_Number] VARCHAR(100) NULL, 
    [Positioning] VARCHAR(255) NULL
)