CREATE TABLE [SFIn].[ContentDistribution] (
    [Id]                                        char (18)   NOT NULL,
    [CreatedDate]                               DATETIME NOT NULL,
    [CreatedById]                               CHAR (18) NOT NULL,
	[OwnerId]                                   CHAR (18) NOT NULL,
    [LastModifiedDate]                          DATETIME  NULL,
    [LastModifiedById]                          CHAR (18) NULL,
    [SystemModstamp]                            DATETIME NULL,
    [Name]                                      NVARCHAR (250)  NULL,
    [IsDeleted]                                 VARCHAR (10) NOT NULL,
	[ContentVersionId]							CHAR (18) NULL,
	[ContentDocumentId]							CHAR (18) NULL,
	[RelatedRecordId]							CHAR (18) NULL,
    [PreferencesAllowPDFDownload]               VARCHAR (10) NULL,
	[PreferencesAllowOriginalDownload]          VARCHAR (10) NULL,
	[PreferencesPasswordRequired]               VARCHAR (10) NULL,
	[PreferencesNotifyOnVisit]                  VARCHAR (10) NULL,
	[PreferencesLinkLatestVersion]              VARCHAR (10) NULL,
	[PreferencesAllowViewInBrowser]             VARCHAR (10) NULL,
	[PreferencesExpires]          				VARCHAR (10) NULL,
	[PreferencesNotifyRndtnComplete]            VARCHAR (10) NULL,
    [ExpiryDate]                      	        DATETIME NULL,
	[Password]         						    VARCHAR (50) NULL,
	[ViewCount]									INT NULL,
	[FirstViewDate]                    	        DATETIME NULL,
    [LastViewDate]                      	    DATETIME NULL,
	[DistributionPublicUrl]						NVARCHAR (250) NULL,
    CONSTRAINT [PK_ContentDistribution] PRIMARY KEY ([Id])
);
GO
