CREATE TABLE [SFIn].[gvp__Survey_Bank__c]
(
  [Id] char(18) NOT NULL, 
  OwnerId char(18) not null,
	IsDeleted varchar(10) not null,
	Name nvarchar(100) not null,
	CreatedDate datetime not null,
	CreatedById char(18) not null,
	LastModifiedDate datetime not null,
	LastModifiedById char(18) not null,
	SystemModstamp datetime not null,
	LastViewedDate datetime null,
	LastReferencedDate datetime null,
	gvp__Category__c nvarchar(100) not null,
	gvp__Multiple_Answers__c varchar(10) not null,
	gvp__Product_Only__c nvarchar(100) not null,
	gvp__Question_Text__c nvarchar(200) not null,
	gvp__Type__c nvarchar(100) not null,
	gvp__Question_List__c nvarchar(300) null,
	gvp__Sales_Driver__c nvarchar(100) null,
	gvp__External_Id__c varchar(20) null,
	gvp__Custom_Fact_1__c decimal(12,8) null,
	gvp__Custom_Fact_2__c decimal(12,8) null,
	gvp__Custom_Fact_3__c decimal(12,8) null,
	gvp__Custom_Fact_4__c decimal(12,8) null,
	gvp__Custom_Fact_5__c decimal(12,8) null,
	gvp__Custom_Text_1__c nvarchar(200) null,
	gvp__Custom_Text_2__c nvarchar(200) null,
	gvp__Custom_Text_3__c nvarchar(200) null,
	gvp__Custom_Text_4__c nvarchar(200) null,
	gvp__Custom_Text_5__c nvarchar(200) null,
	gvp__Name_With_Symbol__c nvarchar(200) not null,
	gvp__Reference_To__c nvarchar(100) null
    CONSTRAINT [PK_gvp__Survey_Bank__c] PRIMARY KEY ([Id]) 
)
