CREATE TABLE [SFIn].[gvp__Activity_Goal__c]
(
	[Id] char(18) NOT NULL ,
	OwnerId char(18) not null,
	IsDeleted varchar(10) not null,
	Name nvarchar(100) not null,
	CreatedDate datetime not null,
	CreatedById char(18) not null,
	LastModifiedDate datetime not null,
	LastModifiedById char(18) not null,
	SystemModstamp datetime not null,
	LastActivityDate date null,
	LastViewedDate datetime null,
	LastReferencedDate datetime null,
	gvp__Account_Calls_Goal__c decimal(4,1) null,
	gvp__Account_Calls_Made__c decimal(4,1) null,
	gvp__Account_Calls_vs_Goal__c decimal(4,3) null,
	gvp__By_the_Glass_Feature_Goal__c decimal(4,1) null,
	gvp__By_the_Glass_Features__c decimal(4,1) null,
	gvp__By_the_Glass_vs_Goal__c decimal(4,3) null,
	gvp__Cocktail_Menu_Feature_Goal__c decimal(4,1) null,
	gvp__Cocktail_Menu_Features__c decimal(4,1) null,
	gvp__Cocktail_Menus_vs_Goal__c decimal(4,3) null,
	gvp__Display_Goal__c decimal(4,1) null,
	gvp__Displays_Secured__c decimal(4,1) null,
	gvp__Displays_vs_Goal__c decimal(4,3) null,
	gvp__Order_Commitment_Goal__c decimal(4,1) null,
	gvp__Order_Commitments_Taken__c decimal(4,1) null,
	gvp__Order_Commitments_vs_Goal__c decimal(4,3) null,
	gvp__POS_Placement_Goal__c decimal(4,1) null,
	gvp__POS_Placements__c decimal(4,1) null,
	gvp__POS_Placements_vs_Goal__c decimal(4,3) null,
	gvp__Presentation_Goal__c decimal(4,1) null,
	gvp__Presentations_Made__c decimal(4,1) null,
	gvp__Presentations_vs_Goal__c decimal(4,3) null,
	gvp__Retail_Ad_Goal__c decimal(4,1) null,
	gvp__Retail_Ads_Placed__c decimal(4,1) null,
	gvp__Retail_Ads_vs_Goal__c decimal(4,3) null,
	gvp__Staff_Training_Conducted__c decimal(4,1) null,
	gvp__Staff_Training_Goal__c decimal(4,1) null,
	gvp__Staff_Trainings_vs_Goal__c decimal(4,3) null,
	gvp__Well_Placement_Goal__c decimal(4,1) null,
	gvp__Wells_Secured__c decimal(4,1) null,
	gvp__Wells_vs_Goal__c decimal(4,3) null,
	gvp__Wine_List_Placement_Goal__c decimal(4,1) null,
	gvp__Wine_List_Placements__c decimal(4,1) null,
	gvp__Wine_List_Placements_vs_Goal__c decimal(4,3) null,
	gvp__Goal_End_Date__c date not null,
	gvp__Goal_Start_Date__c date not null,
	gvp__User__c char(18) not null,
	gvp__Off_Premise_Event_Goal__c decimal(4,1) null,
	gvp__Off_Premise_Events_Executed__c decimal(4,1) null,
	gvp__Off_Premise_Events_vs_Goal__c decimal(4,3) null,
	gvp__On_Premise_Event_Goal__c decimal(4,1) null,
	gvp__On_Premise_Events_Executed__c decimal(4,1) null,
	gvp__On_Premise_Events_vs_Goal__c decimal(4,3) null,
	gvp__External_Id__c varchar(20) null, 
    CONSTRAINT [PK_gvp__Activity_Goal__c] PRIMARY KEY ([Id])
)
