CREATE TABLE [SFIn].[gvp__Invoice__c]
(
  [Id] char(18) NOT NULL, 
	IsDeleted varchar(10) not null,
	Name nvarchar(100) not null,
	RecordTypeId char(18) not null,
	CreatedDate datetime not null,
	CreatedById char(18) not null,
	LastModifiedDate datetime not null,
	LastModifiedById char(18) not null,
	SystemModstamp datetime not null,
	LastActivityDate date null,
	LastViewedDate datetime null,
	LastReferencedDate datetime null,
	gvp__Account__c char(18) not null,
	gvp__Action_Amount__c money null,
	gvp__Action_Comments__c nvarchar(100) null,
	gvp__Action_Date__c date null,
	gvp__Action_Reason__c nvarchar(100) not null,
	gvp__Invoice_Amount__c money not null,
	gvp__Invoice_Balance__c money not null,
	gvp__Invoice_Date__c date not null,
	gvp__Invoice_Number__c varchar(20) not null,
	gvp__Notes__c nvarchar(200) null,
	gvp__Reason_for_Short_Pay__c nvarchar(200) null,
	gvp__Sales_Order__c char(18) null,
	gvp__Total_Chargebacks__c money not null,
	gvp__Balance__c money not null,
	gvp__Budget_Plan__c char(18) null,
	gvp__Budget__c char(18) null,
	gvp__Line_Item_Total__c money not null,
	gvp__Program_Code__c varchar(20) null,
	gvp__Program__c char(18) null,
	gvp__Invoice_Owner__c char(18) not null,
	gvp__Status__c nvarchar(100) not null,
	gvp__Attachments__c decimal(4,1) null,
	gvp__Currency_Code__c nvarchar(100) null,
	gvp__Custom_Currency_1__c money null,
	gvp__Custom_Currency_2__c money null,
	gvp__Custom_Date_1__c date null,
	gvp__Custom_Date_2__c date null,
	gvp__Custom_Number_1__c decimal(12,8) null,
	gvp__Custom_Number_2__c decimal(12,8) null,
	gvp__Custom_Picklist_1__c nvarchar(200) null,
	gvp__Custom_Picklist_2__c nvarchar(200) null,
	gvp__Custom_Text_1__c nvarchar(200) null,
	gvp__Custom_Text_2__c nvarchar(200) null,
	gvp__Custom_Text_3__c nvarchar(200) null,
	gvp__Custom_Text_4__c nvarchar(200) null,
	gvp__Custom_Text_5__c nvarchar(200) null,
	gvp__Payment_Method__c nvarchar(100) null,
	gvp__Posting_Date__c date null
    CONSTRAINT [PK_gvp__Invoice__c] PRIMARY KEY ([Id]) 
)
