CREATE TABLE [dbo].[TempDimRetailer] (
    [RetailerID]              char (18)     NOT NULL,
    [RetailerLN]              NVARCHAR (100)    NOT NULL,
    [RetailerDBA]             NVARCHAR (100)    NULL,
    [BDNID]                   VARCHAR (13)     NULL,
    [ExternalID]              VARCHAR (20)     NULL,
    [DistributorAccountID]    VARCHAR (20)     NULL,
    [LBSalesforceURL]         NVARCHAR(100)    NOT NULL,
    [LBPremiseTypeSKey]       INT              NOT NULL,
    [LBRetailerOwnerSKey]     INT              NOT NULL,
    [LBRetailerHQSKey]        INT              NOT NULL,
    [LBDistributorSKey]       INT              NULL,
    [DistributorRep]          NVARCHAR (100)    NULL,
    [DistributorTeam]         NVARCHAR (50)     NULL,
    [BillingStreet]           NVARCHAR (75)     NULL,
    [LBBillingCitySKey]       INT              NULL,
    [BillingPostalCode]       VARCHAR (9)      NULL,
    [ShippingStreet]          NVARCHAR (75)     NULL,
    [LBShippingCitySKey]      INT              NULL,
    [ShippingPostalCode]      VARCHAR (9)      NULL,
    [SegmentKey]              VARCHAR (50)     NULL,
    [SegmentChannel]          VARCHAR (50)     NULL,
    [BannerName]              NVARCHAR (50)     NULL,
    [WineFlag]                INT              NULL,
    [LiquorFlag]              INT              NULL,
    [BeerFlag]                INT              NULL,
    [FranchiseFlag]           INT              NULL,
    [LBFoodTypeSKey]          INT              NULL,
    [LBTradeChannelSKey]      INT              NULL,
    [ActiveFlag]              INT              NULL,
    [LBStatusSKey]            INT              NULL,
    [LBMarketingGroupSKey]    INT              NULL,
    [LicenseType]             VARCHAR (20)     NULL,
    [CustomerPriority]        INT              NULL,
    [AccountFormat]           VARCHAR (20)     NULL,
    [LBAccountTypeSKey]       INT              NULL,
    [KeyAccountChainFlag]     INT              NULL,
    [RetailerCustomCheckbox1] INT              NULL,
    [RetailerCustomCheckbox2] INT              NULL,
    [CreditAvailable]         MONEY            NULL,
    [CreditLimit]             MONEY            NULL,
    [CreditStatus]            VARCHAR (20)     NULL,
    [LicenseExpiration]       DATETIME         NULL,
    [LBMSASKey]               VARCHAR (20)     NULL,
    [DeliveryTime]            VARCHAR (25)     NULL,
    [SourceFile]              VARCHAR (50)     NULL,
    [Warehouse]               NVARCHAR (50)     NULL,
    [Latitude]                DECIMAL (14, 11) NULL,
    [Longitude]               DECIMAL (14, 11) NULL,
    [GeocodePrecision]        NVARCHAR (20)     NULL,
    [DecisionMakerName]       NVARCHAR (50)     NULL,
    [DecisionMakerEmail]      NVARCHAR (100)    NULL,
    [KPISegment]              char (18)     NULL,
    [AccountRank]             INT              NULL,
    [ConsumerDemographic]     NVARCHAR (100)    NULL,
    [PrimaryContact]          NVARCHAR (50)     NULL,
    [PrimaryContactEmail]     NVARCHAR (100)    NULL,
    [CompanySize]             NVARCHAR (50)     NULL,
    [LicenseNumber]           VARCHAR (20)     NULL,
    [NumberOfLocations]       INT              NULL,
    [FamilyOwnerCode]         VARCHAR (20)     NULL,
    [FIPSStateCode]           INT              NULL,
    [FIPSCountyCode]          INT              NULL,
    [OutletNumber]            VARCHAR (10)     NULL,
    [OutletPlaceName]         NVARCHAR (25)     NULL,
    [NumberOfFTE]             DECIMAL (5, 2)   NULL,
    [NumberOfRegisters]       INT              NULL,
    [SquareFootage]           DECIMAL (8, 2)   NULL,
    [AnnualVolume]            DECIMAL (8, 4)   NULL,
    [WeeklyVolume]            DECIMAL (7, 4)   NULL,
    [OwnerStateFIPSCode]      INT              NULL,
    [OwnerCountyFIPSCode]     INT              NULL,
    [OwnerState]              CHAR (2)         NULL,
    [RetailerCustom1]         NVARCHAR (256)    NULL,
    [RetailerCustom2]         NVARCHAR (256)    NULL,
    [RetailerCustom3]         NVARCHAR (256)    NULL,
    [RetailerCustom4]         NVARCHAR (256)    NULL,
    [RetailerCustom5]         NVARCHAR (256)    NULL,
    [RetailerCustom6]         NVARCHAR (256)    NULL,
    [RetailerCustom7]         NVARCHAR (256)    NULL,
    [RetailerCustom8]         NVARCHAR (256)    NULL,
    [RetailerCustom9]         NVARCHAR (256)    NULL,
    [RetailerCustom10]        NVARCHAR (256)    NULL,
    [RetailerCustomDate1]     DATETIME         NULL,
    [RetailerCustomDate2]     DATETIME         NULL,
    [BDNDateofData]           CHAR(6)         NULL,
    [BDNLastUpdate]           DATE         NULL,
    [BDNAddDate]              DATE         NULL,
    [BDNChangeDate]           DATE         NULL,
    [LBExistsInSFFlag]        INT              NOT NULL,
    [LBSourceID]              INT              NOT NULL,
    [LBRowHash]               VARBINARY (16)   NULL,
    [SourceCreateDate]        DATETIME         NULL,
    [SourceModifiedDate]      DATETIME         NULL
);

