CREATE TABLE [dbo].[TempDimRetailer] (
    [RetailerID]              char (18)     NOT NULL,
    [RetailerLD]              VARCHAR (100)    NOT NULL,
    [RetailerDBA]             VARCHAR (100)    NULL,
    [BDNID]                   VARCHAR (13)     NULL,
    [ExternalID]              VARCHAR (20)     NULL,
    [DistributorAccountID]    VARCHAR (20)     NULL,
    [LBSalesforceURL]         NVARCHAR(100)    NOT NULL,
    [LBPremiseTypeSKey]       INT              NOT NULL,
    [LBRetailerOwnerSKey]     INT              NOT NULL,
    [LBRetailerHQSKey]        INT              NOT NULL,
    [LBDistributorSKey]       INT              NULL,
    [DistributorRep]          VARCHAR (100)    NULL,
    [DistributorTeam]         VARCHAR (50)     NULL,
    [BillingStreet]           VARCHAR (75)     NULL,
    [LBBillingCitySKey]       INT              NULL,
    [BillingPostalCode]       VARCHAR (9)      NULL,
    [ShippingStreet]          VARCHAR (75)     NULL,
    [LBShippingCitySKey]      INT              NULL,
    [ShippingPostalCode]      VARCHAR (9)      NULL,
    [SegmentKey]              VARCHAR (50)     NULL,
    [SegmentChannel]          VARCHAR (50)     NULL,
    [BannerName]              VARCHAR (50)     NULL,
    [WineFlag]                INT              NULL,
    [LiquorFlag]              INT              NULL,
    [BeerFlag]                INT              NULL,
    [FranchiseFlag]           INT              NULL,
    [LBFoodTypeSKey]          INT              NULL,
    [LBTradeChannelSKey]      INT              NULL,
    [ActiveFlag]              INT              NULL,
    [LBStatusSKey]            INT              NULL,
    [LBMarketingGroupSKey]    INT              NULL,
    [LicenseType]             VARCHAR (20)     NULL,
    [CustomerPriority]        INT              NULL,
    [AccountFormat]           VARCHAR (20)     NULL,
    [LBAccountTypeSKey]       INT              NULL,
    [KeyAccountChainFlag]     INT              NULL,
    [RetailerCustomCheckbox1] INT              NULL,
    [RetailerCustomCheckbox2] INT              NULL,
    [CreditAvailable]         MONEY            NULL,
    [CreditLimit]             MONEY            NULL,
    [CreditStatus]            VARCHAR (20)     NULL,
    [LicenseExpiration]       DATETIME         NULL,
    [LBMSASKey]               VARCHAR (20)     NULL,
    [DeliveryTime]            VARCHAR (25)     NULL,
    [SourceFile]              VARCHAR (50)     NULL,
    [Warehouse]               VARCHAR (50)     NULL,
    [Latitude]                DECIMAL (14, 11) NULL,
    [Longitude]               DECIMAL (14, 11) NULL,
    [GeocodePrecision]        VARCHAR (20)     NULL,
    [DecisionMakerName]       VARCHAR (50)     NULL,
    [DecisionMakerEmail]      VARCHAR (100)    NULL,
    [KPISegment]              char (18)     NULL,
    [AccountRank]             INT              NULL,
    [ConsumerDemographic]     VARCHAR (100)    NULL,
    [PrimaryContact]          VARCHAR (50)     NULL,
    [PrimaryContactEmail]     VARCHAR (100)    NULL,
    [CompanySize]             VARCHAR (50)     NULL,
    [LicenseNumber]           VARCHAR (20)     NULL,
    [NumberOfLocations]       INT              NULL,
    [FamilyOwnerCode]         VARCHAR (20)     NULL,
    [FIPSStateCode]           INT              NULL,
    [FIPSCountyCode]          INT              NULL,
    [OutletNumber]            VARCHAR (10)     NULL,
    [OutletPlaceName]         VARCHAR (25)     NULL,
    [NumberOfFTE]             DECIMAL (5, 2)   NULL,
    [NumberOfRegisters]       INT              NULL,
    [SquareFootage]           DECIMAL (8, 2)   NULL,
    [AnnualVolume]            DECIMAL (8, 4)   NULL,
    [WeeklyVolume]            DECIMAL (7, 4)   NULL,
    [OwnerStateFIPSCode]      INT              NULL,
    [OwnerCountyFIPSCode]     INT              NULL,
    [OwnerState]              CHAR (2)         NULL,
    [RetailerCustom1]         VARCHAR (256)    NULL,
    [RetailerCustom2]         VARCHAR (256)    NULL,
    [RetailerCustom3]         VARCHAR (256)    NULL,
    [RetailerCustom4]         VARCHAR (256)    NULL,
    [RetailerCustom5]         VARCHAR (256)    NULL,
    [RetailerCustom6]         VARCHAR (256)    NULL,
    [RetailerCustom7]         VARCHAR (256)    NULL,
    [RetailerCustom8]         VARCHAR (256)    NULL,
    [RetailerCustom9]         VARCHAR (256)    NULL,
    [RetailerCustom10]        VARCHAR (256)    NULL,
    [RetailerCustomDate1]     DATETIME         NULL,
    [RetailerCustomDate2]     DATETIME         NULL,
    [BDNDateofData]           DATETIME         NULL,
    [BDNLastUpdate]           DATETIME         NULL,
    [BDNAddDate]              DATETIME         NULL,
    [BDNChangeDate]           DATETIME         NULL,
    [LBExistsInSFFlag]        INT              NOT NULL,
    [LBSourceID]              INT              NOT NULL,
    [LBRowHash]               VARBINARY (16)   NULL,
    [SourceCreateDate]        DATETIME         NULL,
    [SourceModifiedDate]      DATETIME         NULL
);

