
CREATE TABLE [SRSIn].[ORDDA](
	[RECORDTYPE] [varchar](6) NOT NULL,
	[DISTID] [varchar](8) NOT NULL,
	[ORLINE#] [numeric](7, 0) NULL,
	[ORDATE] [varchar](8) NOT NULL,
	[ORCUST] [varchar](15) NOT NULL,
	[ORDITM] [varchar](10) NULL,
	[ORSITM] [varchar](10) NOT NULL,
	[ORSLSREPID] [varchar](10) NULL,
	[ORWHSE] [varchar](8) NOT NULL,
	[ORCODEDT] [numeric](8, 0) NULL,
	[ORMODE] [numeric](2, 0) NULL,
	[ORORDSYS] [varchar](20) NULL,
	[ORTRTYPE] [varchar](1) NULL,
	[ORINV#] [varchar](25) NULL,
	[ORIDAT] [numeric](8, 0) NULL,
	[ORAVAIL] [varchar](1) NULL,
	[ORQTY] [numeric](7, 0) NOT NULL,
	[ORUOM] [varchar](1) NOT NULL,
	[OROOSQTY] [numeric](7, 0) NULL,
	[OROOSUOM] [varchar](1) NULL,
	[ORFRNEXT] [numeric](13, 0) NULL,
	[ORTOTSLS] [numeric](13, 0) NULL,
	[OREXTDEP] [numeric](13, 0) NULL,
	[ORREPACK] [varchar](1) NOT NULL,
	[ORCRTDATE] [numeric](7, 0) NOT NULL,
	[ORCRTTIME] [numeric](6, 0) NOT NULL,
	[ORPARENT] [varchar](8) NULL,
	[FILENAME] VARCHAR(100) NOT NULL
) 