CREATE TABLE [SRSIn].[OUT](
	[RECORDTYPE] [varchar](6) NOT NULL,
	[DISTID] [varchar](25) NOT NULL,
	[VIPSRS] [varchar](5) NULL,
	[ROCUST] [varchar](15) NOT NULL,
	[RODBA] [varchar](35) NOT NULL,
	[ROLNAM] [varchar](35) NULL,
	[ROADDR1] [varchar](35) NOT NULL,
	[ROADDR2] [varchar](35) NULL,
	[ROCITY] [varchar](30) NOT NULL,
	[ROSTATE] [varchar](2) NOT NULL,
	[ROZIP9] [varchar](9) NULL,
	[ROCTRY] [varchar](3) NULL,
	[ROPHONE] [numeric](20, 0) NULL,
	[ROCHN] [varchar](10) NULL,
	[ROCHN2] [varchar](10) NULL,
	[ROCOT] [varchar](2) NOT NULL,
	[ROFWN] [varchar](1) NULL,
	[ROCSTS] [varchar](1) NULL,
	[RODISP] [varchar](2) NULL,
	[ROETHN] [varchar](2) NULL,
	[ROIVOL] [varchar](1) NULL,
	[ROLIFE] [varchar](1) NULL,
	[ROOCC] [varchar](2) NULL,
	[ROPAGE] [varchar](2) NULL,
	[ROPTYPE] [varchar](1) NULL,
	[ROWMVT] [varchar](2) NULL,
	[ROSMVT] [varchar](2) NULL,
	[ROMMVT] [varchar](2) NULL,
	[ROSELL] [varchar](1) NULL,
	[ROSM1] [varchar](5) NOT NULL,
	[ROSM2] [varchar](5) NULL,
	[ROSTORE] [varchar](10) NULL,
	[ROSTS] [varchar](1) NOT NULL,
	[TERR01TERR30] [varchar](1) NULL,
	[TDOUTCD] [varchar](7) NULL,
	[TDMGROUP] [varchar](6) NULL,
	[VIPID] [varchar](10) NULL,
	[VIPMALT] [varchar](1) NULL,
	[ROBUYER] [varchar](35) NULL,
	[ROLICTYPE] [varchar](1) NULL,
	[ROWHSE] [varchar](8) NULL,
	[ROPARENT] [varchar](25) NULL,
	[ROLICENSE] [varchar](15) NULL,
	[ROOPEN] [numeric](8, 0) NULL,
	[ROCLOSED] [numeric](8, 0) NULL,
	[ROSEASOP] [numeric](2, 0) NULL,
	[ROSEASCL] [numeric](2, 0) NULL,
	[ROPLANO] [varchar](1) NULL
)