CREATE TABLE SRSIn.[OUTDA]
(
  RECORDTYPE  varchar(6)    NOT NULL,
  DISTID      varchar(25)    NOT NULL,
  VIPSRS      varchar(5),
  ROCUST      varchar(15)    NOT NULL,
  RODBA       varchar(35)    NOT NULL,
  ROLNAM      varchar(35),
  ROADDR1     varchar(35)    NOT NULL,
  ROADDR2     varchar(35),
  ROCITY      varchar(30)    NOT NULL,
  ROSTATE     varchar(2)    NOT NULL,
  ROZIP9      varchar(9),
  ROCTRY      varchar(3),
  ROPHONE     varchar(20),
  ROCHN       varchar(10),
  ROCHN2      varchar(10),
  ROCOT       varchar(2)    NOT NULL,
  ROFWN       varchar(1),
  ROCSTS      varchar(1),
  RODISP      varchar(2),
  ROETHN      varchar(2),
  ROIVOL      varchar(1),
  ROLIFE      varchar(1),
  ROOCC       varchar(2),
  ROPAGE      varchar(2),
  ROPTYPE     varchar(1),
  ROWMNT      varchar(2),
  ROSMVT      varchar(2),
  ROMMVT      varchar(2),
  ROSELL      varchar(1),
  ROSM1       varchar(5)    NOT NULL,
  ROSM2       varchar(5),
  ROSTORE     varchar(10),
  ROSTS       varchar(1)    NOT NULL,
  TERR01      varchar(1),
  TERR02      varchar(1),
  TERR03      varchar(1),
  TDOUTCD     varchar(7),
  TDMGROUP    varchar(6),
  VIPID       varchar(10),
  VIPMALT     varchar(1),
  ROBUYER     varchar(35),
  ROLICTYPE   varchar(1),
  ROWHSE      varchar(8),
  ROPARENT    varchar(25),
  ROLICENSE   varchar(15),
	[FILENAME] VARCHAR(100) NOT NULL
)
