CREATE TABLE SRSIn.[SLSDA]
(
  RECORDTYPE  varchar(6)    NOT NULL,
  DISTID      varchar(8)    NOT NULL,
  VIPSRS      varchar(5),
  RSIDAT      varchar(8)    NOT NULL,
  RSINV       varchar(25)   NOT NULL,
  RSCUST      varchar(15)   NOT NULL,
  RSITEM      varchar(10)   NOT NULL,
  RSQTY       int           NOT NULL,
  RSUOM       varchar(1)    NOT NULL,
  RSFRONT     money         NOT NULL,
  RSFRUOM     varchar(1)    NOT NULL,
  RSNET       money         NOT NULL,
  RSNETUOM    varchar(1)    NOT NULL,
  RSFMDT      varchar(8)    NOT NULL,
  RSTODT      varchar(8)    NOT NULL,
  VIPID       int,
  RSDITEM     varchar(10),
  RSNET4      money,
  RSDEPOS     money,
  RSCRV       money,
  RSLOCTAX    money,
  RSADDCHG    money,
  RSSLSREPID  varchar(5),
  RSREPACK    varchar(1),
  RSWHSE      varchar(8),
  RSPARENT    varchar(25), 
    CONSTRAINT [PK_SLSDA] PRIMARY KEY ([DISTID], [RSIDAT], [RSINV], [RSITEM])
)
