CREATE TABLE SRSIn.[VOCHAIN]
(
	RECORDTYPE [varchar](6) NOT NULL,
	VPCHN [varchar](10) NOT NULL,
	VPCHNM [varchar](50) NOT NULL,
	VPCHNTYP [varchar](1) NOT NULL,
	VPPARCHN [varchar](10) NULL,
	VPPARNM [varchar](35) NULL,
	[FILENAME] VARCHAR(100) NOT NULL
)
