CREATE TABLE SRSIn.[VOCOT]
(
	RECORDTYPE [varchar](6) NOT NULL,
	VPCOTCD [varchar](2) NOT NULL,
	VPCOT [varchar](25) NOT NULL,
	VPSUBCHNLCD [varchar](2) NOT NULL,
	VPSUBCHNL [varchar](25) NOT NULL,
	BDNPREM [varchar](1) NOT NULL,
	BDNPREMD [varchar](25) NOT NULL,
	BDNLICTYPE [varchar](1) NOT NULL,
	BDNLICTYPED [varchar](25) NOT NULL

)
