CREATE TABLE SRSIn.[VOOWNDESC]
(
	RECORDTYPE [varchar](6) NOT NULL,
	VPCHNHCD Numeric(5) NOT NULL,
	VPCHNHNM [varchar](35) NOT NULL,
	VPCHNHADR [varchar](35)NULL,
	VPCHNHCITY [varchar](35)NULL,
	VPCHNHST [varchar](2)NULL,
	VPCHNHZIP [varchar](9)NULL,
	VPCHNHPHN [varchar](20)NULL,
	[FILENAME] VARCHAR(100) NOT NULL
)
