CREATE TABLE [dbo].[DimRetailer] (
    [LWRetailerSKey]          INT              IDENTITY (1, 1) NOT NULL,
    [RetailerID]              char (18)     NOT NULL,
    [RetailerLD]              VARCHAR (100)    NOT NULL,
    [RetailerDBA]             VARCHAR (100)    NULL,
    [BDNID]                   VARCHAR (20)     NULL,
    [ExternalID]              VARCHAR (20)     NULL,
    [DistributorAccountID]    VARCHAR (20)     NULL,
    [LWSalesforceURL]         NVARCHAR(100)    NOT NULL,
    [LWPremiseTypeSKey]       INT              NOT NULL,
    [LWRetailerOwnerSKey]     INT              NOT NULL,
    [LWRetailerHQSKey]        INT              NOT NULL,
    [LWDistributorSKey]       INT              NULL,
    [DistributorRep]          VARCHAR (100)    NULL,
    [DistributorTeam]         VARCHAR (50)     NULL,
    [BillingStreet]           VARCHAR (75)     NULL,
    [LWBillingCitySKey]       INT              NULL,
    [BillingPostalCode]       VARCHAR (9)      NULL,
    [ShippingStreet]          VARCHAR (75)     NULL,
    [LWShippingCitySKey]      INT              NULL,
    [ShippingPostalCode]      VARCHAR (9)      NULL,
    [SegmentKey]              VARCHAR (50)     NULL,
    [SegmentChannel]          VARCHAR (50)     NULL,
    [BannerName]              VARCHAR (50)     NULL,
    [WineFlag]                INT              NULL,
    [LiquorFlag]              INT              NULL,
    [BeerFlag]                INT              NULL,
    [FranchiseFlag]           INT              NULL,
    [LWFoodTypeSKey]          INT              NULL,
    [LWTradeChannelSKey]      INT              NULL,
    [ActiveFlag]              INT              NULL,
    [LWStatusSKey]            INT              NULL,
    [LWMarketingGroupSKey]    INT              NULL,
    [LicenseType]             VARCHAR (20)     NULL,
    [CustomerPriority]        INT              NULL,
    [AccountFormat]           VARCHAR (20)     NULL,
    [LWAccountTypeSKey]       INT              NULL,
    [KeyAccountChainFlag]     INT              NULL,
    [RetailerCustomCheckbox1] INT              NULL,
    [RetailerCustomCheckbox2] INT              NULL,
    [CreditAvailable]         MONEY            NULL,
    [CreditLimit]             MONEY            NULL,
    [CreditStatus]            VARCHAR (20)     NULL,
    [LicenseExpiration]       DATETIME         NULL,
    [LWMSASKey]               VARCHAR (20)     NULL,
    [DeliveryTime]            VARCHAR (25)     NULL,
    [SourceFile]              VARCHAR (50)     NULL,
    [Warehouse]               VARCHAR (50)     NULL,
    [Latitude]                DECIMAL (14, 11) NULL,
    [Longitude]               DECIMAL (14, 11) NULL,
    [GeocodePrecision]        VARCHAR (20)     NULL,
    [DecisionMakerName]       VARCHAR (50)     NULL,
    [DecisionMakerEmail]      VARCHAR (100)    NULL,
    [KPISegment]              char (18)     NULL,
    [AccountRank]             INT              NULL,
    [ConsumerDemographic]     VARCHAR (100)    NULL,
    [PrimaryContact]          VARCHAR (75)     NULL,
    [PrimaryContactEmail]     VARCHAR (100)    NULL,
    [CompanySize]             VARCHAR (50)     NULL,
    [LicenseNumber]           VARCHAR (20)     NULL,
    [NumberOfLocations]       INT              NULL,
    [FamilyOwnerCode]         VARCHAR (20)     NULL,
    [FIPSStateCode]           INT              NULL,
    [FIPSCountyCode]          INT              NULL,
    [OutletNumber]            VARCHAR (10)     NULL,
    [OutletPlaceName]         VARCHAR (25)     NULL,
    [NumberOfFTE]             DECIMAL (5, 2)   NULL,
    [NumberOfRegisters]       INT              NULL,
    [SquareFootage]           DECIMAL (8, 2)   NULL,
    [AnnualVolume]            DECIMAL (7, 2)   NULL,
    [WeeklyVolume]            DECIMAL (7, 2)   NULL,
    [OwnerStateFIPSCode]      INT              NULL,
    [OwnerCountyFIPSCode]     INT              NULL,
    [OwnerState]              CHAR (2)         NULL,
    [RetailerCustom1]         VARCHAR (200)    NULL,
    [RetailerCustom2]         VARCHAR (200)    NULL,
    [RetailerCustom3]         VARCHAR (200)    NULL,
    [RetailerCustom4]         VARCHAR (200)    NULL,
    [RetailerCustom5]         VARCHAR (200)    NULL,
    [RetailerCustom6]         VARCHAR (200)    NULL,
    [RetailerCustom7]         VARCHAR (200)    NULL,
    [RetailerCustom8]         VARCHAR (200)    NULL,
    [RetailerCustom9]         VARCHAR (200)    NULL,
    [RetailerCustom10]        VARCHAR (200)    NULL,
    [RetailerCustomDate1]     DATETIME         NULL,
    [RetailerCustomDate2]     DATETIME         NULL,
    [BDNDateofData]           DATETIME         NULL,
    [BDNLastUpdate]           DATETIME         NULL,
    [BDNAddDate]              DATETIME         NULL,
    [BDNChangeDate]           DATETIME         NULL,
    [LWExistsInSFFlag]        INT              NOT NULL,
    [LWSourceID]              INT              NOT NULL,
    [SourceCreateDate]        DATETIME         NULL,
    [SourceModifiedDate]      DATETIME         NULL,
    [LWCreateDate]            DATETIME         CONSTRAINT [DF_DimRetailer_LWCreateDate] DEFAULT (getdate()) NOT NULL,
    [LWModifiedDate]          DATETIME         CONSTRAINT [DF_DimRetailer_LWModifiedDate] DEFAULT (getdate()) NOT NULL,
    [LWRowHash]               VARBINARY (16)   NULL,
    CONSTRAINT [PK_LWRetailerSKey] PRIMARY KEY CLUSTERED ([LWRetailerSKey] ASC)
);

