CREATE TABLE [dbo].[DimSupplier] (
    [LBSupplierSKey]     INT            IDENTITY (1, 1) NOT NULL,
    [SupplierID]         char (18)   NOT NULL,
    [SupplierLD]         VARCHAR (100)  NOT NULL,
    [ExternalID]         VARCHAR (20)   NULL,
    [LBSalesforceURL]    VARCHAR (100)  NOT NULL,
    [Street]             VARCHAR (75)   NULL,
    [City]               VARCHAR (50)   NOT NULL,
    [LBStateSKey]        INT            NOT NULL,
    [PostalCode]         VARCHAR (9)    NULL,
    [LBCountrySKey]      INT            NOT NULL,
    [SupplierCustom1]    VARCHAR (256)  NULL,
    [SupplierCustom2]    VARCHAR (256)  NULL,
    [SupplierCustom3]    VARCHAR (256)  NULL,
    [SupplierCustom4]    VARCHAR (256)  NULL,
    [SupplierCustom5]    VARCHAR (256)  NULL,
    [LBExistsInSFFlag]   INT            NULL,
    [LBSourceID]         INT            NULL,
    [SourceCreateDate]   DATETIME       NOT NULL,
    [SourceModifiedDate] DATETIME       NOT NULL,
    [LBCreateDate]       DATETIME       CONSTRAINT [DF_DimSupplier_LBCreateDate] DEFAULT (getdate()) NOT NULL,
    [LBModifiedDate]     DATETIME       CONSTRAINT [DF_DimSupplier_LBModifiedDate] DEFAULT (getdate()) NOT NULL,
    [LBRowHash]          VARBINARY (16) NULL,
    CONSTRAINT [PK_DimSupplier] PRIMARY KEY CLUSTERED ([LBSupplierSKey] ASC)
);

