CREATE TABLE [dbo].[FactDepletion]
(
  LWDepletionDistributorSKey	int				not null default -1,
  LWDepletionItemSKey			int				not null default -1,
  LWDepletionSizeSKey			int				not null default -1,
  LWDepletionTerritorySKey		int				not null default -1,
  LWDepletionTxnTypeSKey		int				not null default -1,
  DepletionKey					varchar(95)		not null default '-1',
  CasesYTD						decimal(9,4)	null,
  DepletionDate					date			null,
  PhysicalCases					decimal(9,4)	null,
  X9LCases						decimal(14, 4)	null,
  Adjustments					decimal(14,4)	null,
  ClosingBalance				decimal(14, 4)	null,
  InBond						decimal(9,4)	null,
  OnOrder						decimal(9,4)	null,
  OpeningBalance				decimal(14, 4)	null,
  Receipts						decimal(9,4)	null,
  TransfersIn					decimal(9,4)	null,
  TransfersOut					decimal(9,4)	null,
  WholesaleSales				decimal(10,4)	null,
  SourceFile					varchar(80)		null,
  Custom1						nvarchar(200)	null,
  Custom2						nvarchar(200)	null,
  CustomFact1					decimal(14,4)	null,
  CustomFact2					decimal(14,4)	null,
  DistributorItemNumber			varchar(20)		null,
  SourceSystem					nvarchar(20)	null,
  [LWSourceID]					INT				NOT NULL DEFAULT -1, 
  [SourceCreateDate]			DATETIME		NULL, 
  [SourceModifiedDate]			DATETIME		NULL, 
  [LWCreateDate]				DATETIME		NOT NULL DEFAULT (getdate()), 
  [LWModifiedDate]				DATETIME		NOT NULL DEFAULT (getdate()),
  [LWRowHash]					BINARY(16)		NOT NULL,
CONSTRAINT [PK_FactDepletion] PRIMARY KEY ([LWDepletionDistributorSKey],[LWDepletionItemSKey],[DepletionKey])
)
