CREATE TABLE [dbo].[FactShipment]
(
  LWShipmentDistributorSKey		int				not null default -1,
  LWShipmentProductSizeSKey		int				not null default -1,
  LWShipmentTerritorySKey		int				not null default -1,
  LWShipmentTxnTypeSKey			int				not null default -1,
  ShipmentKey					varchar(100)	not null default '-1',
  OrderType						nvarchar(100)	null,
  OrderStatus					nvarchar(100)	null,
  DeliveryDate					date			null,
  OrderDate						date			null,
  PhysicalCases					decimal(11,3)	null,
  X9LCases						decimal(11,3)	null,
  FullCaseEquivalent			decimal(11,3)	null,
  PrimaryVolume					decimal(11,3)	null,
  SecondaryVolume				decimal(11,3)	null,
  ExtPrice1						money			null,
  ExtPrice2						money			null,
  OrderNumber					varchar(30)		null,
  InvoiceNumber					varchar(50)		null,
  Custom1						nvarchar(200)	null,
  Custom2						nvarchar(200)	null,
  CustomFact1					decimal(15,8)	null,
  CustomFact2					decimal(15,8)	null,
  SourceSystem					varchar(20)		null,
  [LWSourceID]					INT				NOT NULL DEFAULT -1, 
  [SourceCreateDate]			DATETIME		NULL, 
  [SourceModifiedDate]			DATETIME		NULL, 
  [LWCreateDate]				DATETIME		NOT NULL DEFAULT (getdate()), 
  [LWModifiedDate]				DATETIME		NOT NULL DEFAULT (getdate()),
  [LWRowHash]					BINARY(16)		NOT NULL,
CONSTRAINT [PK_FactShipment] PRIMARY KEY ([LWShipmentDistributorSKey],[LWShipmentProductSizeSKey],[ShipmentKey])
)
